### ISSUE TITLE
Перегруппировать разделы в консоли сайта

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#100]
Сейчас есть 2 раздела в консоли: Инструменты / МойСклад и Настройки / МойСклад.
Надо сделать один раздел МойСклад, к нему иконку https://www.flaticon.com/free-icon/stock_1326071#term=warehouse&page=1&position=77

И далее внутри 2 подраздела: Настройки и Управление.

**Comment by artikus11** [comment]
@uptimizt Я ж делал подобное) Правда там еще сами настройки распределялись по табам. Ты хочешь пока просто собрать в один раздел?

**Comment by artikus11** [comment]
@uptimizt Не могу реквесты делать. Ты видимо ветки удалил или закрыл. Залил в мастер по этому тикету. Посмотри

**Comment by uptimizt** [comment]
@artikus11 да все ветки удалил, думаю мастера хватит + теги по версиям.

получилось круто :)

**Comment by artikus11** [comment]
@uptimizt едрить, вот ты схему придумал)))

> ты можешь сделать реверс? так чтобы Настройки были как доп пункт и назывались Настройки. а Управление - было по умолчанию. Птм что в реальной жизни чаще в управление входят, а Настройки редко

Да, можно и так сделать. Только дефолтная страница все равно будет называться Мой склад

**Comment by artikus11** [comment]
@uptimizt Сделал реверс, но чет реквесты ругаются. Глянь там

**Comment by uptimizt** [comment]
@artikus11 все норм. это он говорит что без согласования дальше не пустит :)

**Comment by artikus11** [comment]
@uptimizt  Ага, понятно)
