### ISSUE TITLE
Правки заголовков и кнопок в Управлении

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#104]
1. надо поправить заголовки: Товары, Модификации и вариации, Комплекты, Заказы, Изображения. Сейчас много слов и мало смысла. Надо просто меньше слов. Проще.
2. Кнопки все сделать синими и назвать все просто Выполнить

![image](https://user-images.githubusercontent.com/1852897/49344189-00d76700-f685-11e8-8cda-0ca8f97a56d9.png)

**Comment by artikus11** [comment]
@uptimizt Модификации и вариации - не одно и то же? Может так Модификации (вариации)

**Comment by artikus11** [comment]
@uptimizt чего на гитлабе не проверяешь реквесты?

**Comment by uptimizt** [comment]
За основу можно взять стили от сюда:
![image](https://user-images.githubusercontent.com/1852897/49701980-43a8ba00-fc04-11e8-805f-13a79c11fb73.png)

**Comment by artikus11** [comment]
Пулл реквесты проверь, уже сделано)
