### ISSUE TITLE
Если родитель имеет цену ноль, то он скрывается, но при этом в вариациях цены есть

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#106]
Иногда бывает так, что родительская цена равно 0, но при этом в модификациях цены есть. При том для скрытия товаров идет проверка на цену родителя. Надо как-то это изменить или проверять вариацию на цену... https://github.com/wpcraft-ru/wooms/blob/master/inc/class-import-products.php#L124

**Comment by artikus11** [comment]
@uptimizt В МС. У клинта в родителе ноль стоит а для каждой вариации своя цена

**Comment by uptimizt** [comment]
Возможно стоит добавить опцию "Скрывать товар при 0 цене". Чтобы каждый сам выбирал как ему надо.

**Comment by artikus11** [comment]
@uptimizt Хм, ну если по аналогии с настройкой самой Вуки, то да, может и надо, у всех товары по разному создаются

**Comment by uptimizt** [comment]
в 4.11 поправлено
