### ISSUE TITLE
Опция выбора группы - не влияет на начало обмена

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#108]
1. выбрал группу Запчасти для колясок
2. запустил синк
3. на сайте появилась группа основных товаров (которой быть не должно)

![image](https://user-images.githubusercontent.com/1852897/49754292-be3a0e00-fcc6-11e8-9188-d7ab2b7bc2a6.png)

**Comment by uptimizt** [comment]
@artikus11 есть идеи?

**Comment by artikus11** [comment]
@uptimizt То есть до синка этой группы не было?

**Comment by uptimizt** [comment]
Вот. Это группа верхнего уровня для Колясочных, которые были выбраны для обмена.
![image](https://user-images.githubusercontent.com/1852897/49890801-09cef200-fe56-11e8-9d6f-903daacab52e.png)

**Comment by artikus11** [comment]
Получается что идет синк из дочерней группы. Родительская все равно будет создаваться, а после синка она будет удалятся. А иначе как определить структуру рубрик, что бы в случае чего восстановить все рубрики. По другому не придумал как это сделать

@uptimizt

**Comment by uptimizt** [comment]
Переписал метод. Теперь при создании выбранная группа и все что выше не попадает на сайт.
