### ISSUE TITLE
Загрузка изображения у модификаций Товара

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#116]
Цитата ХД: 1598

> Добрый день, приобрел ваш плагин расширенной версии, всё вроде бы корректно работает, за исключением того, что требуется с "мойсклад" так же выгружать товар->модификация->картинка, возможно ли получить данную функцию?

**Comment by artikus11** [comment]
Ждать надо. МС обещали в новой версии АПИ сделать возможность загрузки, но релиза АПИ ждем с августа

**Comment by uptimizt** [comment]
the duplicate https://github.com/wpcraft-ru/wooms/issues/116
