### ISSUE TITLE
Выбор варианта предзаказа при нулевых остатках. 

### ISSUE THREAD

**Issue by ekhrabroff** [wpcraft-ru/wooms#119]
Здравствуйте. 

Прошу ввести в функционал возможность выбрать, в настройках, тип предзаказа при нулевых остатках: "разрешить, но уведомить клиента". Как это реализовано в карточке товара Woocommerce. 

На данный момент в WooMS можно либо разрешать, либо не разрешать предзаказы. Хочется чтобы клиент на сайте видел, что товара сейчас нет в наличии но его можно заказать. А сейчас если товар отсутствует, клиент видит что товар есть, при включенном предзаказе. При этом он может заказать и сразу оплатить отсутствующий товар. Не у всех есть возможность ждать поставку и придется возвращать деньги.

**Comment by ekhrabroff** [comment]
![2019-01-24_23-52-45](https://user-images.githubusercontent.com/46093062/51707937-8fd48000-2033-11e9-949c-1d657f5b30f5.png)
![2019-01-24_23-55-12](https://user-images.githubusercontent.com/46093062/51707939-8fd48000-2033-11e9-8b1b-2a6ee3bb14cf.png)

**Comment by ekhrabroff** [comment]
![2019-01-24_23-58-21](https://user-images.githubusercontent.com/46093062/51708057-f48fda80-2033-11e9-9faf-42f6cd29e225.png)

**Comment by uptimizt** [comment]
@ekhrabroff в типовом варианте такой опции не вижу. это какой то плагин?

**Comment by artikus11** [comment]
@uptimizt есть такая опция, но если управление запасами идет на уровне товара

![image](https://user-images.githubusercontent.com/16116688/51855156-f9ab9d00-2345-11e9-89f4-bed63c0c4867.png)

**Comment by uptimizt** [comment]
поправил в 4.2 - скоро релиз
