### ISSUE TITLE
Кейс - доп поле Бренд в МойСклад нужно связать как общий атрибут Бренд в WooCommerce

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#127]
ХД 1785

**Comment by r0mkan** [comment]
Добрый день, 

Бренд в моем складе сделан справочником. 
В WP попробовал добавить атрибут Бренд - не помогло. 

<img width="1680" alt="screenshot 2019-01-26 at 13 11 40" src="https://user-images.githubusercontent.com/47137401/52049209-ca807000-257f-11e9-9efe-97b808e16462.png">
<img width="1680" alt="screenshot 2019-01-26 at 13 12 50" src="https://user-images.githubusercontent.com/47137401/52049210-cb190680-257f-11e9-9564-d26c0ced705c.png">
<img width="1680" alt="screenshot 2019-01-26 at 13 13 42" src="https://user-images.githubusercontent.com/47137401/52049212-cb190680-257f-11e9-94e1-0170bef284c0.png">

**Comment by seredniy** [comment]
@r0mkan а в самих товарах атрибут "бренд" добавился? Я так понимаю, но добавляется как "индивидуальный атрибут".

Посмотрите на вклатку "Атрибуты" при редактировании одного из таких товаров)

**Comment by r0mkan** [comment]
Да, добавился как индивидуальный атрибут. 

<img width="1680" alt="screenshot 2019-01-31 at 17 54 00" src="https://user-images.githubusercontent.com/47137401/52049875-7bd3d580-2581-11e9-907c-a785a780e059.png">

**Comment by uptimizt** [comment]
@r0mkan @seredniy в версии 4.2 сделал. пробуем

**Comment by r0mkan** [comment]
Объясните механику как правильно сделать. 
Я обновил до 4.2. Удалил все атрибуты из WP. 
Сделал ручную синхронизацию с мойсклад - атрибутов у товаров не появилось. 

Нужно до синхронизации создать в WP атрибут с точно таким же названием как справочник в мой склад и тогда они соединятся?

**Comment by uptimizt** [comment]
@r0mkan по умолчанию должен создаваться обычный индивидуальный атрибут.
Но если на сайте есть общий атрибут с таким названием то будет создан общий.

**Comment by uptimizt** [comment]
механика не интуитивно не понятная. но пока по быстрому так. потом сделаем понятней

**Comment by uptimizt** [comment]
@r0mkan @seredniy будет круто если отпишите здесь по результату и дадите ссылки на примеры работы

**Comment by seredniy** [comment]
@uptimizt 
![image](https://user-images.githubusercontent.com/11270429/52167652-fa1dac80-2726-11e9-9669-6e3f1d12c0b1.png)

в тестовом товаре почему-то теперь атрибуты дублируются (цвет как общий атрибут и цвет как индивидуальный, например)

**Comment by uptimizt** [comment]
@seredniy если удалить то снова создаться?

**Comment by seredniy** [comment]
@uptimizt Сейчас удалю и запущу импорт. Отпишусь сразу как дойдет до этого товара...)

**Comment by uptimizt** [comment]
у меня там есть код, который удаляет индивидуальный, если нашел общий.
но если они были созданы ранее с другим слагом, то может быть ошибка. которая решается пересозданием.
либо мб ошибка в коде, тогда будем править.

**Comment by seredniy** [comment]
> либо мб ошибка в коде, тогда будем править.

Так мне удалить что? Я пока вообще сам товар удалил.

У меня из доп.полей в Моем Складе только Бренд - остальные на скриншоте - это из модификаций взято

**Comment by uptimizt** [comment]
@seredniy удалить товар - это тоже норм.
можешь скинуть снимок карточки товара? чтобы видеть доп поля и модификации?

**Comment by r0mkan** [comment]
@uptimizt 
Я не понимаю, что я не так делаю, но у меня атрибуты ни как индивидуальные ни как общие не появляются в WP. 

В моем складе у товара есть поле Бренд. Оно сделано как справочник. 
Пробовал удалять товар, потом синхронизировать. 
потом добавить атрибут с таким же именем в WP , удалить товар и синхронизировать 
Потом создать в атрибуте бренд в WP именно тот бренд который должен быть в списке. 
Удалить товар и синхронизировать. 
Никак не появился атрибут на сайте. 

<img width="1510" alt="screenshot 2019-02-03 at 19 34 55" src="https://user-images.githubusercontent.com/47137401/52177194-06ba0780-27f0-11e9-83b7-23fc050150b9.png">
<img width="1680" alt="screenshot 2019-02-03 at 19 49 53" src="https://user-images.githubusercontent.com/47137401/52177195-07529e00-27f0-11e9-948f-58bfdccfec40.png">

**Comment by uptimizt** [comment]
@r0mkan тут мб 2 проблемы:
- опция работы с атрибутами в настройках включена?
- у вас слаг бренда на сайте - brand. это может не совпадать с автоматом, который думает что надо как brend.

последняя проблема пока решается так что руками slug не правим и позволяет сайту самому его определить. тогда связь будет. это особенность работы базовых механик.

но проблема ясна и я уже думаю над тем как ее обойти. в след версиях сделаем более понятный и надежный вариант.

**Comment by r0mkan** [comment]
@uptimizt 
опция включена. 
Я пробовал сначала не правя руками, но синхронизации не было. и только после этого поменял на brand

**Comment by uptimizt** [comment]
ok, я переписал эту часть. теперь будет по русскому названию без конвертации сравнивать.
@r0mkan отправил на почту

**Comment by artikus11** [comment]
Если я правильно понял, то Бренды в МС это отдельная сущьность, зачем их вообще в атрибуты пихать? Может лучшк создавать отдельную таксономию при наличии Брендов в МС , как обычно и делается?

@uptimizt

**Comment by seredniy** [comment]
@artikus11  тогда мы теряем возможность стандартной фильтрации вуки по этим атрибутам.

**Comment by artikus11** [comment]
Спорное достоинство. Да, штатная сортировка вуки теряется зато получаем сортировку из ядра по таксам. Любой виджет будет работать, а если таксономию назвать brend то еще и куча готовых плагинов под Вуку под это найдется

@seredniy

**Comment by uptimizt** [comment]
@artikus11 есть 2 веские причины:
1. это очень круто дает SEO трафик по бренд запросам, а их много, тк появляются страницы по брендам
2. это дает подбор без костылей и смарт фильтры, которые улучшают UX, конверсию и доходы

**Comment by uptimizt** [comment]
> Да, штатная сортировка вуки теряется зато получаем сортировку из ядра по таксам.
общие атрибуты это и есть таксономии WP. просто они генерятся на основе настроек вуки
@artikus11

**Comment by artikus11** [comment]
Опять спорно. Атрибут это таже таксономия, только более сложная. При отдельной таксе страницы появляются ничуть не хуже, только с ними работать проще. 
И подбор будет без костылей, почемуто использование рубрик не является костылем, а использовпние брендп отднльной таксой уже костыль. Странно как то

@uptimizt

**Comment by uptimizt** [comment]
@artikus11 это называется Бритва Оккама. Если задачу можно решить через А+Б и через А+Б+В, то верным считается первое решение, тк требуется меньше компонентов. Лишний компонент от которого можно отказаться без значимых потерь - это костыль.
Мы можем отказаться от лишнего плагина брендов? Можем. Значит обязаны отказаться.
Да, ты можешь использовать отдельный плагин. Если на то есть веские причины, то это не костыль. Но тебе придется пилить отдельную интеграцию к складу, к SEO, к механике фасетного отбора по продуктам и т д. Если у тебя много свободных денег и времени - это может быть решением.
Но большинство Клиентов решение без костыля устраивает, там сразу все что нужно идет из коробки, не нужно танцевать с бубном, делать кучу лишних интеграций и мучиться с программистами.
Птм мы просто следуем принципу Бритвы Оккама. В соответствии с которым это костыль, который можно выкинуть из решения.

**Comment by artikus11** [comment]
Я знаю что такое Бритва Оккама, но в данном случае сей принцип не применяется, так как это не самое простое решение. Спорить не буду, твой плагин, тебе и решение принимать...
@uptimizt

**Comment by Alexande07** [comment]
Здравствуйте. требуется выгрузка цен, акций, в сторону приложения и загрузка от туда заказа он поддерживает? и какой транспорт используется при обмене, для того как развернуть 1с, если через веб сервис, поддерживается онлайн передача, плагин сам реализовывает модель сервиса?  Плагин выполнен как что? требуется снимать конфигурацию с поддержки ? если не изменяет то можем 1 с аренду взять
