### ISSUE TITLE
Импорт одиночного товара

### ISSUE THREAD

**Issue by seredniy** [wpcraft-ru/wooms#129]
Можно ли добавить возможность обновить избранный товар? Т.е. не весь процесс, а отдельный товар по его UUID, например?

Что-то типа такого:

![image](https://user-images.githubusercontent.com/11270429/52167915-4b2f9f80-272b-11e9-890c-2f45695e0d7d.png)

**Comment by uptimizt** [comment]
да, хорошая идея. сам о таком уже давно думаю :)
надеюсь скоро появятся ресурсы и запилим.

**Comment by uptimizt** [comment]
@seredniy в новой версии сделал. в тест режиме. когда будет релиз пока не ясно.
если что могу отдельно релиз кандидат скинуть.

**Comment by uptimizt** [comment]
@seredniy есть возможность потестировать со своей стороны?
