### ISSUE TITLE
Как добавить товару информацию о том, на каком складе он в наличии? 

### ISSUE THREAD

**Issue by seredniy** [wpcraft-ru/wooms#139]
Добрый день! Хотелось бы при синхронизации отмечать в товаре с помощью доп. поля то, на каком складе он есть в наличии?

т. е. Чтобы потом можно было выводить в карточке товара что-то типа: "Футболка на складе в Москве"

**Comment by uptimizt** [comment]
Есть 2 базовых хук фильтра: wooms_product_save и wooms_save_variation
Они передают объект продукта или вариации. С данными из МойСклад.
Пример как это работает в базовой комплектации с остатками есть в классе WooMS\Products\Stocks (WooMS XT - plugins/wooms-extra/inc/class-products-stocks.php).

Там же видно что плагин формирует запрос к МойСклад https://online.moysklad.ru/api/remap/1.1/report/stock/all - получает от туда данные и записывает в продукт WooCommerce.

Взяв за основу эти хуки и эту логику, можно ее модернизировать. Записать эти данные в метаполе, и далее вывести на странице продукта.

@seredniy

**Comment by uptimizt** [comment]
@seredniy лучше всего это сделать отдельным плагином. Просто используя эти хуки.

**Comment by seredniy** [comment]
спасибо, попробуем обязательно и отпишусь с примером кода своего

чт, 21 февр. 2019 г., 22:26 Anatoly Yumashev <notifications@github.com>:

**Comment by uptimizt** [comment]
@seredniy как успехи? удалось найти какое либо решение?
