### ISSUE TITLE
Call to undefined function curl_init()

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#165]
CRITICAL Uncaught Error: Call to undefined function curl_init() in /var/www/arealshop.fi/data/www/arealshop.fi/wp-content/plugins/wooms/inc/class-import-product-images.php:210

надо добавить проверку на существование функции.

если функции нет - сообщать в лог ошибок.
плюс сообщать в здоровье сайта что надо поставить.

**Comment by mihdan** [comment]
А почему бы не использовать `wp_remote_get` вместо `curl`?

**Comment by uptimizt** [comment]
> А почему бы не использовать wp_remote_get вместо curl?

почти везде он используется. кроме механики получения картинок.
также пробовал родной метод https://developer.wordpress.org/reference/functions/download_url/ - в этом API он тоже не работает.

не знаю пчм но именно в этом месте оно никак не работало.
методом тыка и чтения форумов подобрал рабочий curl вариант.
так заработало. и пока стараюсь сюда не лазить.

@mihdan
