### ISSUE TITLE
Загрузка товаров у которых есть фото и описание

### ISSUE THREAD

**Issue by Alexivakha** [wpcraft-ru/wooms#167]
Обмен товаров между Wordpress (Woocommerce) и Мойсклад
Нужно выгружать товары с Мойсклад на Woocommerce только те у которых есть фото и описание, подскажите как такое реализовать.
Или выгружать все товары, но без фото и описания чтобы попадали в статус на утверждения

Заранее благодарен

С ув, Александр

**Comment by mihdan** [comment]
В момент синхронизации, если у товара нет описания или фото, нужно ставить товару статус "Черновик"?

PS: связано с https://toster.ru/q/635014

**Comment by Alexivakha** [comment]
Да, можно в черновик, или в статус на утверждении.

**Comment by uptimizt** [comment]
у плагина есть хук фильтр wooms_product_save в который передается объект продукта и данные из МойСклад.
цепляемся на хук, смотрим нужные данные и скрываем продукт из каталога.

```
add_filter( 'wooms_product_save', function($product, $data_api){
  if($data_api[...]){
    $product->set_catalog_visibility( 'hidden' );
  }
  return $product;
}, 30, 2 );
```

**Comment by Alexivakha** [comment]
Мне за честь с Вами пообщаться
Вставил данный код в functions.php 
http://cd39323-wordpress-1.tw1.ru/shop/  
Нет ли ошибки в коде ?

**Comment by uptimizt** [comment]
> Мне за честь с Вами пообщаться
давай вот без этого ))

> Нет ли ошибки в коде ?
мне за честь полагать что ты думаешь что я могу так быстро взламывать сайты и смотреть коды не имея доступов ))
но лучше все таки показать тот код который ты туда вставил.
сам код не рабочий, его надо еще допиливать, тк я не помню какие данные надо смотреть чтобы проверить на описание и картинки.

**Comment by Alexivakha** [comment]
Я могу предоставить доступы, только не хотелось бы это делать публично. Можем как-то выйти на связь в каком-то из мессенджеров?

**Comment by uptimizt** [comment]
> Я могу предоставить доступы, только не хотелось бы это делать публично. Можем как-то выйти на связь в каком-то из мессенджеров?

не нужен доступ к сайту. нужно просто пример адаптированного кода.
если это просто копи паст то точно не будет работать )
если надо вот прям рабочий код, то я могу написать но позже

**Comment by Alexivakha** [comment]
Понял) Спасибо за быстрые ответы.
Желательно рабочий код, можете сориентировать по времени, когда можно ожидать ?)

**Comment by artikus11** [comment]
@Alexivakha  у тебя там Элементор вроде на главной, а он может и не срабатывать, так как при выводе там параметры штатных выводов перебиваются данными виджета, которым выводишь. Потому код может и не сработать. 
Ну и конечно копипаста тут не пройдет

@uptimizt а в данных что приходят есть данные о картинках? Описание то точно есть, насколько помню description обзывается, а вот картинки image?

Если все так то @Alexivakha кд будет примерно такой

```
add_filter( 'wooms_product_save', function($product, $data_api){
  if(! $data_api['description'] || ! $data_api['image']){
    $product->set_catalog_visibility( 'hidden' );
  }
  return $product;
}, 30, 2 );
```

**Comment by uptimizt** [comment]
о! огневая поддержка с воздуха подоспела :) 

тогда наверное точнее будет так:
```
add_filter( 'wooms_product_save', function($product, $data_api){
  if( empty($data_api['description']) || empty($data_api['image']['meta']['href']) ){
    $product->set_catalog_visibility( 'hidden' );
  }
  return $product;
}, 30, 2 );
```

вот это скорее всего будет работать. но надо тестить.

**Comment by Alexivakha** [comment]
Спасибо всем за поддержку
На последний код не ругается, но товары не фильтруются 
http://cd39323-wordpress-1.tw1.ru
http://cd39323-wordpress-1.tw1.ru/shop/

**Comment by uptimizt** [comment]
@artikus11 

> $product->save();

это лишнее, тк объект передается и после выполнения всех фильтров сохраняется 1 раз за итерацию. 2 раза сохранять не надо тк это лишняя нагрузка на БД.

**Comment by artikus11** [comment]
> о! огневая поддержка с воздуха подоспела :)
Я слежу за тобой))

**Comment by uptimizt** [comment]
> На последний код не ругается, но товары не фильтруются

надо повторить синк

@Alexivakha

**Comment by Alexivakha** [comment]
А, повторить на стороне Woocommerce ?

**Comment by artikus11** [comment]
> @artikus11
> 
> > $product->save();
> 
> это лишнее, тк объект передается и после выполнения всех фильтров сохраняется 1 раз за итерацию. 2 раза сохранять не надо тк это лишняя нагрузка на БД.

Ну вот не помню уже всю механику, а точно, там же сей фильтр перед сохранением стоит

**Comment by artikus11** [comment]
> А, повторить на стороне Woocommerce ?

Да, в адинке еще раз синхронизацию полную включи

**Comment by Alexivakha** [comment]
Мой склад => управление => выполнить, верно ?

**Comment by artikus11** [comment]
> Мой склад => управление => выполнить, верно ?

Ну да, как ты первый раз товары загружал, просто повтори

**Comment by Alexivakha** [comment]
Синхронизировал, товары добавились, но фильтрация не произошла )

**Comment by artikus11** [comment]
> Синхронизировал, товары добавились, но фильтрация не произошла )

Что-то быстро больно, у тебя там 50 страниц по 10 товаров, 500 товаров. Товары заходя по 20 шт в минуту, Итого минимум 20 минут надо для полного синка

**Comment by Alexivakha** [comment]
Надо прям полную синхронизацию сделать ? Или можно на пару десятков товаров и остановить ?

**Comment by uptimizt** [comment]
Полную да. И если не получится, то напиши доступы на m@wcpraft.ru - будем разбираться

**Comment by artikus11** [comment]
Есть еще момент, у тебя есть товары в которых есть описание, но нет картинки, Условие не срабатывает.

**Comment by Alexivakha** [comment]
Спасибо всем за помощь! Делаю сейчас полную синк, отпишусь что и как, если что скину доступы

**Comment by Alexivakha** [comment]
> Есть еще момент, у тебя есть товары в которых есть описание, но нет картинки, Условие не срабатывает.

Да, есть и такие товары

**Comment by artikus11** [comment]
@Alexivakha попробуй так
```
add_filter( 'wooms_product_save', function($product, $data_api){
  if( empty($data_api['image']['meta']['href']) ){
    $product->set_catalog_visibility( 'hidden' );
  }
  if( empty($data_api['description']) ){
    $product->set_catalog_visibility( 'hidden' );
  }
  return $product;
}, 30, 2 );
```

Ну и полный синк

**Comment by Alexivakha** [comment]
Понял, выполняю !)

**Comment by Alexivakha** [comment]
Всем доброе утро. 
Получилось убрать товары без фото и описания на странице http://cd39323-wordpress-1.tw1.ru/shop/
На категориях не сработало  (http://cd39323-wordpress-1.tw1.ru/rusalka/, http://cd39323-wordpress-1.tw1.ru/onedayart/, ), возможно как-то и там товары скрыть ? На сайте используется шаблон Monstroid2

**Comment by mihdan** [comment]
Активируйте тему Storefront официальную для чистоты эксперимента.

**Comment by Alexivakha** [comment]
> Активируйте тему Storefront официальную для чистоты эксперимента.

Делал, такая же ситуация

**Comment by mihdan** [comment]
Вы хотите сказать, что set_catalog_visibility=hidden нигде не работает?

Замените тогда на set_status=draft это 100% сработает

**Comment by Alexivakha** [comment]
Ребят, всем спасибо за помощь! 
Вот этот код работает на всех страницах 
На странице /shop (http://cd39323-wordpress-1.tw1.ru/shop/) иногда вылазят товары из черновиков, так как у них выставлена видимость в каталоге, можно как-то автоматом убирать эту видимость если товар в черновике ?

add_filter( 'wooms_product_save', function($product, $data_api){
  if( empty($data_api['image']['meta']['href']) ){
    $product->set_status('draft');
  }
  if( empty($data_api['description']) ){
    $product->set_status('draft');
  }
  return $product;
}, 30, 2 );

**Comment by mihdan** [comment]
Комбинируйте видимость и черновик и черновики видно только админу или всем юзерам? В инкогнито смотрели?

```
add_filter( 'wooms_product_save', function( $product, $data_api ) {
    if ( empty( $data_api['image']['meta']['href'] ) ) {
        $product->set_status( 'draft' );
        $product->set_catalog_visibility( 'hidden' );
    }
    if ( empty( $data_api['description'] ) ) {
        $product->set_status( 'draft' );
        $product->set_catalog_visibility( 'hidden' );
    }
    return $product;
}, 30, 2 );
```

**Comment by Alexivakha** [comment]
> Комбинируйте видимость и черновик. И черновики видно только админу или всем юзерам? В инкогнито смотрели?
> 
> ```
> add_filter( 'wooms_product_save', function( $product, $data_api ) {
>     if ( empty( $data_api['image']['meta']['href'] ) ) {
>         $product->set_status( 'draft' );
>         $product->set_catalog_visibility( 'hidden' );
>     }
>     if ( empty( $data_api['description'] ) ) {
>         $product->set_status( 'draft' );
>         $product->set_catalog_visibility( 'hidden' );
>     }
>     return $product;
> }, 30, 2 );
> ```

Да, Вы правы. Товары только админу видны. Тогда всё отлично!)

**Comment by mihdan** [comment]
@uptimizt можно закрывать

**Comment by Alexivakha** [comment]
Доброго времени суток! 
Ещё возник один вопрос, теперь после каждой синхронизации товаров без фото и описания, которые попадают в статус "черновик", эти товары дублируются. 
Можно ли избежать этот неприятный момент (чтобы они не дублировались) ? 

С ув, Александр

**Comment by uptimizt** [comment]
@Alexivakha интересный кейс )
поправил https://github.com/wpcraft-ru/wooms/commit/7e4a2553763ce376e71de4dc129040d93d048adc

залей последнюю версию с гитхаба. отпиши помогло или нет.

**Comment by Alexivakha** [comment]
После добавления кода сделать полную синхронизацию ?

**Comment by uptimizt** [comment]
@Alexivakha да
