### ISSUE TITLE
Потенциальная проблема с остатками у основного товара при наличии вариаций

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#171]
## Введение
Есть подозрение что иногда МойСклад позволяет принимать товары и делать остатки без учета модификаций. А потом при синке в вариациях этого остатка нет.

## Например:
1. Есть "Футболка Красная" и у нее 3 модификации: S, X, L
2. Приняли на склад футболку без учета модификации в количестве 1 шт.
3. В этом случае получается что футболка есть, но без учета модификаций
4. По каждой модификации получаем 0 остаток
5. Сайт не умеет вести остатки по вариативному продукту в целом и получается что у каждой вариации 0 остаток.

Если это так то надо добавить в логгер учет таких операций как ошибки чтобы легче было понять что к чему.

## Обходное решение
Принимать товары правильно. Разность остатки по модификациям. Так чтобы у основного товара остаток был 0.

**Comment by luk911** [comment]
походу это мой случай
У меня обувь в магазине и все товары с вариациями по размеру.
И вот смотрю что у всех товаров у каждого размера стоит нет на складе. 

Что делать ? только сегодня купил вашь модуль, не хочется расстраиваться.

**Comment by uptimizt** [comment]
> походу это мой случай
> У меня обувь в магазине и все товары с вариациями по размеру.
> И вот смотрю что у всех товаров у каждого размера стоит нет на складе.
> 
> Что делать ? только сегодня купил вашь модуль, не хочется расстраиваться.

@luk911 можете написать в поддержку примеры такой ошибки? Ссылки на товар и доступ к сайту.
На примере проблемы решение будет быстрее.

**Comment by uptimizt** [comment]
пока из решений только обходное - правильный учет остатков
