### ISSUE TITLE
Синхронизация по группам и отключение старых продуктов по сессиям

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#18]
- [x] синк вариаций
- [x] выбор группы
- [x] скрытие старых продуктов по сессии
- [x] При постоянном синке в вариативных товарах дублируются вариации или выпадает 502-я ошибка
- [x] Выполнение крона по очереди
- [x] тесты и правки

**Comment by artikus11** [comment]
Запушил
https://gitlab.com/wpcraft/wooms-extra/merge_requests/27
https://github.com/uptimizt/wooms/pull/22

Проверяй...

**Comment by uptimizt** [comment]
@artikus11 вроде все ок. давай закрывать и пробовать )
