### ISSUE TITLE
Как настроить исключение категорий для синхронизации?

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#181]
По умолчанию есть 2 механизма:
1. Ограничение по группе 
2. Ограничение по складу

Механизмы отличаются.

Лучше всего ограничить по 1 группе. В этом случае выбирается 1 группа для сайта и все товары из этой группы попадают на сайт. Если товара в группе нет - он не попадает.

Ограничение по складу работает иначе. В этом случае все товары все равно попадают на сайт. Но если товара нет на складе то он помечается как без остатков. И далее уже на стороне сайт можно скрыть товары с 0 остатком.

**Comment by dekterev** [comment]
А как синхронизировать категории в мс и на сайте?

**Comment by uptimizt** [comment]
решение тут https://github.com/wpcraft-ru/wooms/issues/297
