### ISSUE TITLE
В МС есть строковые доп. поля у товаров - как их синхронизировать в Woocommerce? 

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#184]
Суть в том, что в МС есть поля "текст", "целое число", "дробное число". Они пропускаются в плагине, хотя по сути, могут обрабатываться индентично простым строковым поля. Строковые поля обработались нормально. Под другие типы просто прописали свой хук. Но думаю, что внести эти поля было бы  хорошо.

**Comment by sdelfi** [comment]
\plugins\wooms-extra\inc\class-products-attributes.php

Сюда можно прописать новые типы, а еще лучше - добавить еще и хук, чтобы можно было под себя этот список менять:
```
//Если это не число и не строка - пропуск, тк другие типы надо обрабатывать иначе
if( ! in_array($attribute['type'], array('string', 'number', 'customentity')) ){
        continue;
}
```

**Comment by uptimizt** [comment]
@sdelfi добавил хук.
не смог найти названия типов в документации.
если будут примеры уже рабочих типов - то получится добавить их сразу в рабочий список
