### ISSUE TITLE
Как можно товары которые не в наличии помещать в статус ЧЕРНОВИК при синхронизации Woo с Мойсклад ?

### ISSUE THREAD

**Issue by Alexivakha** [wpcraft-ru/wooms#187]
Если помните, мы делали, товары которые без фото и описания в статус ЧЕРНОВИК)

add_filter( 'wooms_product_save', function($product, $data_api){
  if( empty($data_api['image']['meta']['href']) ){
    $product->set_status('draft');
    $product->set_catalog_visibility( 'hidden' );
  }
  if( empty($data_api['description']) ){
    $product->set_status('draft');
    $product->set_catalog_visibility( 'hidden' );
  }
  return $product;
}, 30, 2 );

**Вот я пробовал свой "код" но он не работает для меня**

add_filter( 'wooms_product_save', function($product, $data_api){
  if( empty($data_api['image']['meta']['href']) ){
    $product->set_status('draft');
    $product->set_catalog_visibility( 'hidden' );
  }
  if( empty($data_api['description']) ){
    $product->set_status('draft');
    $product->set_catalog_visibility( 'hidden' );
  }
  if( $product->get_stock_quantity() < 0 ) {
    $product->set_status('draft');
	$product->set_catalog_visibility( 'hidden' );
   }
   if ( !$product->is_in_stock() ) {
    $product->set_status('draft');
    $product->set_catalog_visibility( 'hidden' );
   }
  return $product;
}, 30, 2 );

_**С ув, Александр**_

**Comment by uptimizt** [comment]
@Alexivakha смотрю. надеюсь в течении 2 дней протестировать и отписаться что да как

**Comment by Alexivakha** [comment]
Благодарю за ответ!

Я могу скинуть Вам доступ к сайту, на котором нет много товаров и можно
потестировать разные варианты?)
Товаров 120+-

С ув, Александр

**Comment by uptimizt** [comment]
@Alexivakha попробовал у себя - все ок. работает.
пробовал через синк отдельного продукта. в карточке продукта.

попробуй. если не получится, то надо напомнить доступы к сайту (консоль, фтп) на m@wpcraft.ru - посмотрим

**Comment by Alexivakha** [comment]
Я вот этим кодом что выше пробовал, запускал синк, то не работает вообще, а бывает просто все товары кидает в статус черновик, очень странно себя ведет или то плагин или с кодом что-то непонятное. Я искал причину, так и не выяснил почему кидало все товары в черновик.

**И еще товары есть в наличии в Мойсклад, а Woocommerce показывает что продукт не в наличии и его не возможно заказать.** Эта проблема на основном сайте, думаю сначала лучше решить вопрос с черновиком, а потом с наличием товара в Мойсклад.

Я сейчас вышлю доступы к сайту там где не очень много товаров и на нем нет особого трафика сейчас, а вот потом тоже самое нужно будет поставить на основной чтобы также работало, без фото и описание + товары не в наличии => в статус черновик. 

_Высылаю доступы к ФТП и к Админ панели
С ув, Александр_

**Comment by Alexivakha** [comment]
Добрый вечер, есть новости ?

**Comment by uptimizt** [comment]
```
add_filter( 'wooms_product_save', function($product, $data_api){

    if($product->is_type('variable')){
        return $product;
    }
    
    if( $product->get_stock_quantity() < 1 ) {
        $product->set_status('draft');
        $product->set_catalog_visibility( 'hidden' );
    }
    if ( !$product->is_in_stock() ) {
        $product->set_status('draft');
        $product->set_catalog_visibility( 'hidden' );
    }
    return $product;
}, 50, 2 );
```

чуть поправил код

**Comment by uptimizt** [comment]
@Alexivakha тут проблема решена?

**Comment by Alexivakha** [comment]
Нет, не решена.
Там на симптом работает отлично.
А на 12ahopmoscow не корректно работает.
Еще не выяснил причину, но мне кажется из-за не правильных остатков у
товаров при синхронизации, пишет нет в наличии когда товар в наличии.
Вообщем путаница.

**Comment by uptimizt** [comment]
в новой версии сильно поменялась логика работы по синку остатков.
тут https://github.com/wpcraft-ru/wooms/issues/287

потому теперь решение такое:
```
add_filter('wooms_stock_product_save', function($product){

    if($product->get_stock_quantity() <= 0){
        $product->set_status('draft');
    }
});
```
