### ISSUE TITLE
Проблема интеграции Заказов между Сайтом и МойСклад - ошибка обновления статуса

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#193]
Ошибка:
`
Что то пошло не так. Хук на стороне МойСклад отключен в нарушении настройки. Попробуйте отключить и включить снова. Если не поможет - обратитесь в техподдержку.
`

**Comment by uptimizt** [comment]
Такая проблема обычно бывает в 2х случаях:

1. есть 2 копии сайта и одна заняла хук. Надо перестать использовать 2й сайт и выключить/включить опцию на 1м сайте.

2. у одного клиента эта проблема оказалась не решаемой. тк у него есть CRM Bitrix которая заняла этот хук. и он решил оставить это в CRM.

проблема в том что хук может быть только 1 на 1 систему. если системы 2 то приходится выбирать в какую попадут данные.

теоретически и технически это можно решить. если писать еще 1 систему, которая будет маршрутизировать данные между всеми другими системами. но это достаточно дорогое решение. и нужно иметь бюджет на реализацию и поддержку такой системы.

**Comment by Iamsoncha** [comment]
> Такая проблема обычно бывает в 2х случаях:
> 
> 1. есть 2 копии сайта и одна заняла хук. Надо перестать использовать 2й сайт и выключить/включить опцию на 1м сайте.
> 2.

у меня подобная проблема, две копии сайта, одна из которых перенастроена.
то тесть я имею два разных по идее сайта, которые тянут товары и заказы из разных баз Мой склад под разными логинами.
На одном хук работает, на другом - нет.
Поможет ли переустановка модуля WOOMS?

**Comment by uptimizt** [comment]
делать 2 сайта на 1 склад - это сложная история. 

если что консультации тут https://wpcraft.ru/ask/
