### ISSUE TITLE
Сохранение данных по нескольким складам

### ISSUE THREAD

**Issue by VsevolodKobzar** [wpcraft-ru/wooms#198]
**Доброго времени суток, прошу помощи!**

**1) Приобрел платную версию, как синхронизировать остатки по складам?**

Параметры из Woocommerce (названия складов знаю).

![WoomsXT](https://user-images.githubusercontent.com/56938779/67432549-e0e3c580-f5ff-11e9-9fe8-5beb8ee37ed3.JPG)

**Вторая проблема** - по какому полю (Код или Артикул или другое) идёт синхронизация ?
При синхронизации позиции из Склада вида 14123 или 14 123 - переходят в Woo как 14 123, соответственно идет не обновление кол-ва и цен старых, а создание новых товаров.

**БУДУ БЛАГОДАРЕН ИНСТРУКЦИИ ПО НАСТРОЙКЕ ИЛИ ПОМОЩИ!** 
Писал в почту, но ответа нет....

**Comment by uptimizt** [comment]
Остатки можно синхронизировать по складу. По складам нельзя. Такой опции в вукомерсе нет. А значит нет в нашем плагине. Можно сделать доп плагином, за отдельную цену.

Синхронизация идёт по полю uuid. Оно образуется при создании товара с нуля или при наличии совпадений артикулов. Если артикулы не совпали - будет создан новый товар. Запишется uuid.

14 123 не понимаю. Нужен снимок карточки товара с сайта. Пробелы ранее в артикулах не встречались.

**Comment by VsevolodKobzar** [comment]
артикулы я поправлю в складе - именно артикулы или коды надо поправить ?

**Comment by uptimizt** [comment]
Коды никак не используются при обмене.
Артикулы - идеальное решение по умолчанию.
Но если их нет то у плагина есть опция работы только на базе uuid.

**Comment by VsevolodKobzar** [comment]
Значит артикулы в складе поправлю, это не проблема - останется вопрос с товарами по складам. В МойСклад выглядит так:

![Stores](https://user-images.githubusercontent.com/56938779/67438495-1a6efd80-f60d-11e9-9182-560e0a45266c.JPG)

**Comment by VsevolodKobzar** [comment]
в переписке я задавал этот вопрос, так как этот момент был крайне важен

**Comment by uptimizt** [comment]
Да, в МойСклад они выглядят так. Проблема не в этом. Проблема в том что в вукомерсе они никак не выглядят. Каждый магазин решает проблему по своему.
Птм и интеграция решается индивидуально. Нужно понимать как хранятся данные по остаткам в вукомерсе. И тогда можно придумать как их передавать. Универсальных решений для всех пока не придумали.

Если опишите метаполя и код хранения данных то мы можем подсказать снипеет для интеграции.

**Comment by VsevolodKobzar** [comment]
если делать выгрузку товаров, магазины обозначены так:

Мета: _number_field_mel

Мета: _number_field_okt

Мета: _number_field_zel

Мета: _number_field_sklad

Мета: _number_field_gn

Как посмотреть код хранения?

**Comment by uptimizt** [comment]
Код надо смотреть где то в теме или плагинах. Зависит от того кем и как он был написан. 

Также можно попробовать описать процесс как вы руками эти данные меняете, желательно сделать снимок.
Мб получится догадаться

**Comment by VsevolodKobzar** [comment]
Небольшое приложение, ранее из базы 1С формировало xml с кодом:

<item id="15067" categoryId="14956" categoryname="Штампы и скраперы" name="Kaleidoscope Штамп ksst05 розовый двухсторонний круглый + скрапер (не липкий)" price="330.00" disc="0" in_st2="3" in_st5="1" in_st1="3" in_st3="4" in_st4="0" in_stock="11" b_in_st="instock"/>

Далее его через AllImport грузим

**Comment by VsevolodKobzar** [comment]
item id="15067" categoryId="14956" categoryname="Штампы и скраперы" name="Kaleidoscope Штамп ksst05 розовый двухсторонний круглый + скрапер (не липкий)" price="330.00" disc="0" in_st2="3" in_st5="1" in_st1="3" in_st3="4" in_st4="0" in_stock="11" b_in_st="instock"

**Comment by VsevolodKobzar** [comment]
удалил скобки в начале строки и вконце ( <  />) - с ними сюда не вставляются

**Comment by uptimizt** [comment]
Видимо есть метаполя и в каждое метаполя пишется количество по какому то складу?
Если я верно понимаю то нужен список складов и к какому складу какое метаполе соответствует? В метаполе пишем только число?

**Comment by uptimizt** [comment]
Это позволит написать примерный сниппет, который вы вероятно сможете уже применить на своем сайте

**Comment by VsevolodKobzar** [comment]
Всё верно, как на первом скриншоте - общее колво, и снизу по складам.

метаполя: 

Мета: _number_field_mel соответсвует _in_st2

Мета: _number_field_okt соответсвует _in_st5

Мета: _number_field_zel соответсвует _in_st1

Мета: _number_field_gn соответствует _in_st3 

Мета: _number_field_sklad соответсвует _in_st4

если я правильно Вас понял

![WC](https://user-images.githubusercontent.com/56938779/67440166-e1855780-f611-11e9-8467-461e40ea1cd8.png)

**Comment by VsevolodKobzar** [comment]
да, только число

**Comment by VsevolodKobzar** [comment]
код склада в МойСклад могу поставить любой (если его можно использовать)

**Comment by VsevolodKobzar** [comment]
вот как выглядит внутри

![wooC](https://user-images.githubusercontent.com/56938779/67440901-375aff00-f614-11e9-98e9-a6f690664992.JPG)

**Comment by VsevolodKobzar** [comment]
Помогите пожалуйста с настройкой

**Comment by uptimizt** [comment]
Мы готовим скрипт, который должен помочь сохранить данные правильно.
Уточните, каким образом сделали вывод этих полей в карточке товара?

**Comment by VsevolodKobzar** [comment]
Большое спасибо! Изначально через xml было сделано (когда 1С было), как я описал - сейчас же товары в МойСклад находятся, поля в woocommerce существуют - если выгружать товары то колонки Мета: _number_field_mel и тд, а когда загружали в Woo - in_st1="3" и тд (как в xml который скинул)

**Comment by VsevolodKobzar** [comment]
если как то поможет - код склада в МойСклад могу задать как надо

**Comment by VsevolodKobzar** [comment]
@uptimizt Доброго времени суток! Подскажите пожалуйста по интеграции, когда сможем попробовать скрипт?

**Comment by uptimizt** [comment]
вот такой сниппет получился @VsevolodKobzar 
он сохраняет данные об остатках по складам в метаполе `wooms_stock_by_store`

далее в идеале переписать ваш шаблон вывода. чтобы он брал данные из этого метаполя.

либо адаптировать сохранение данных под вашу структуру полей. это будет сложнее.

```
<?php 
/**
 * Plugin Name: WooMS i198
 * Description: snippet for issue https://github.com/wpcraft-ru/wooms/issues/198
 * Author: WPCraft
 * Author URI: https://wpcraft.ru/
 * License: GPLv2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: wooms
 * Domain Path: /languages
 * Version: 1.0
 */

namespace WooMS\i198;

defined( 'ABSPATH' ) || exit;

final class General {

    public static function init(){
        add_filter( 'wooms_product_save', [__CLASS__, 'product_add_hook' ], 10, 2 );
        add_action( 'wooms_product_stock_by_store_data', [__CLASS__, 'product_stock_update'], 10, 3);
    }

    /**
     * product stock update
     */
    public static function product_stock_update($wooms_id, $product_id, $data_api = []){

        $url = 'https://online.moysklad.ru/api/remap/1.1/report/stock/bystore';
        $url = add_query_arg('product.id', $wooms_id, $url);
        $data = wooms_request($url);

        do_action('wooms_logger', __CLASS__,
            'Отправлен запрос на остатки', $url
        );

        if(empty($data['rows'][0]['stockByStore'])){
            return;
        }

        $stockByStore = $data['rows'][0]['stockByStore'];
        $stock = [];
        $stock['items'] = [];
        $stock['source'] = $data;
        foreach ($stockByStore as $store_data){
            $key = $store_data['meta']['href'];
            $stock['items'][$key] = [
                'name' =>   $store_data['name'],
                'stock' =>   $store_data['stock'],
                'reserve' =>   $store_data['reserve'],
                'inTransit' =>   $store_data['inTransit'],
            ];
        }

        update_post_meta($product_id, 'wooms_stock_by_store', $stock);

    }

    /**
     * Product - add hook for update stock data
     */
    public static function product_add_hook($product, $data_api){
        if($wooms_id = $product->get_meta('wooms_id', true)){
            $product_id = $product->get_id();
            do_action('wooms_product_stock_by_store_data', $wooms_id, $product_id, $data_api);
        }
        return $product;
    }


}

General::init();

```

**Comment by VsevolodKobzar** [comment]
Спасибо! 

Подскажите, как его загрузить в плагин?

**Comment by uptimizt** [comment]
это скрипт.
можно создать папку плагина например в wp-content/plugins/wooms-mh или как то так.
там создать файл php и туда закинуть этот код.
далее активировать этот плагин в консоли сайта.

@VsevolodKobzar

**Comment by VsevolodKobzar** [comment]
@uptimizt Загрузил, ничего не поменялось...остатки так же не грузятся

**Comment by VsevolodKobzar** [comment]
@uptimizt написал в почту, посмотрите пожалуйста

**Comment by VsevolodKobzar** [comment]
@uptimizt прошу Вас выйти на связь

**Comment by uptimizt** [comment]
> Загрузил, ничего не поменялось...остатки так же не грузятся

Как вы это поняли?
Нужно посмотреть товар по которому есть данные об остатках и посмотреть что лежит в метаполе?

Какое решение приняли? Изменение кода сохранения данных или изменение кода отображения данных?
Лучше приложить оба сниппета.

**Comment by VsevolodKobzar** [comment]
Данные по метаполю выгружу, касательно решения - мы сейчас перешли на мойсклад, соответственно решили адаптировать код на сайте под данные, которые получает ваш плагин

**Comment by VsevolodKobzar** [comment]
Дописал метаполя в скрипт, посмотрите пожалуйста правильно или нет ? 

Вместо wooms_stock_by_store вбил метаполя складов, но теперь не грузится вообще...

namespace WooMS\i198;

defined( 'ABSPATH' ) || exit;

final class General {

    public static function init(){
        add_filter( 'wooms_product_save', [__CLASS__, 'product_add_hook' ], 10, 2 );
        add_action( 'wooms_product_stock_by_store_data', [__CLASS__, 'product_stock_update'], 10, 3);
    }

    /**
     * product stock update
     */
    public static function product_stock_update($wooms_id, $product_id, $data_api = []){

        $url = 'https://online.moysklad.ru/api/remap/1.1/report/stock/bystore';
        $url = add_query_arg('product.id', $wooms_id, $url);
        $data = wooms_request($url);

        do_action('wooms_logger', __CLASS__,
            'Отправлен запрос на остатки', $url
        );

        if(empty($data['rows'][0]['stockByStore'])){
            return;
        }

        $stockByStore = $data['rows'][0]['stockByStore'];
        $stock = [];
        $stock['items'] = [];
        $stock['source'] = $data;
        foreach ($stockByStore as $store_data){
            $key = $store_data['meta']['href'];
            $stock['items'][$key] = [
                'name' =>   $store_data['name'],
                'stock' =>   $store_data['stock'],
                'reserve' =>   $store_data['reserve'],
                'inTransit' =>   $store_data['inTransit'],
            ];
        }

        update_post_meta($product_id, '_number_field_okt', $stock);
	update_post_meta($product_id, '_number_field_zel', $stock);
	update_post_meta($product_id, '_number_field_okt', $stock);
	update_post_meta($product_id, '_number_field_mel', $stock);
	update_post_meta($product_id, '_number_field_sklad', $stock);

    }

    /**
     * Product - add hook for update stock data
     */
    public static function product_add_hook($product, $data_api){
        if($wooms_id = $product->get_meta('wooms_id', true)){
            $product_id = $product->get_id();
            do_action('wooms_product_stock_by_store_data', $wooms_id, $product_id, $data_api);
        }
        return $product;
    }


}

General::init();

**Comment by uptimizt** [comment]
@VsevolodKobzar без навыков программирования эту задачу сложно решить )
в идеале - найти программиста которому эту задачу решить не проблема.

в данном случае вы пытаетесь обеспечить сохранение в старую схему не понимая структуру данных и как ее разбить на нужные поля.

а я не знаю какая у вас структура данных и id. плюс без доступа к коду и без возможности отладки кода - сложно такой код написать в слепую тут.

птм выше я предложил что лучше не пытаться менять логику сохранения данных и адаптировать ее под старую структуру. 

гораздо легче поправить ту часть которая выводит данные. но для этого нужен сниппет кода который отвечает за вывод данных.

**Comment by VsevolodKobzar** [comment]
@uptimizt Подскажите, а как данные извлекаются и как записываются в wordpress? В коде нашел то что ниже, если я правильно понимаю вы об этом спрашивали:

//Добавляем поля в товар
add_action( 'woocommerce_product_options_inventory_product_data', 'art_woo_add_custom_fields' );
function art_woo_add_custom_fields() {
	global $product, $post;
	echo '<div class="options_group">';// Группировка полей

	woocommerce_wp_checkbox( array(
   'id'            => '_checkbox',
   'wrapper_class' => 'show_if_simple',
   'label'         => 'Под заказ',
   'description'   => '',
		) );

	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_mel',
		 'label'             => __( 'ул. Мельникайте, 98', 'woocommerce' ),
		 'placeholder'       => 'Остаток Мельникайте',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_okt',
		 'label'             => __( 'ул. 50 лет октября, 21', 'woocommerce' ),
		 'placeholder'       => '50 лет октября',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_zel',
		 'label'             => __( 'ул. Николая Зелинского, 16', 'woocommerce' ),
		 'placeholder'       => 'Николая Зелинского',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
    ) );
    woocommerce_wp_text_input( array(
		 'id'                => '_number_field_gn',
		 'label'             => __( 'ул. В. Гнаровской, 12 кор. 9', 'woocommerce' ),
		 'placeholder'       => 'В. Гнаровской',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_sklad',
		 'label'             => __( 'Склад', 'woocommerce' ),
		 'placeholder'       => 'Склад',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	echo '</div>';
}

add_action( 'woocommerce_process_product_meta', 'art_woo_custom_fields_save', 10 );
function art_woo_custom_fields_save( $post_id ) {
   // Сохранение цифрового поля
	 $woocommerce_number_field = $_POST['_checkbox'];
   if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_checkbox', esc_attr( $woocommerce_number_field ) );
   }
   $woocommerce_number_field = $_POST['_number_field_mel'];
   if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_mel', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_okt'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_okt', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_zel'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_zel', esc_attr( $woocommerce_number_field ) );
   }
   $woocommerce_number_field = $_POST['_number_field_gn'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_gn', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_sklad'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_sklad', esc_attr( $woocommerce_number_field ) );
   }
 			else {
      // Иначе удаляем созданное поле из бд
      delete_post_meta( $post_id, '_product_field_type_ids');
   }
}

add_action( 'woocommerce_after_add_to_cart_form', 'art_get_text_field_before_add_card' );
function art_get_text_field_before_add_card() {
	global $post;
	echo '<div class="sklad">';
	echo '<div class="nalichie-title">Наличие в магазинах:</div><div class="nalichie-subtitle">Фактическое наличие уточняйте по телефону</div>';
	echo '<div class="item-sklad"><label>ул. Мельникайте, 98: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_mel', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 589-294</span></div>';
	echo '<div class="item-sklad"><label>ул. 50 лет октября, 21: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_okt', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 601-704</span></div>';
    echo '<div class="item-sklad"><label>ул. Николая Зелинского, 16: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_zel', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 605-451</span></div>';
    echo '<div class="item-sklad"><label>ул. В. Гнаровской, 12 кор. 9: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_gn', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 606-400</span></div>';
	echo '<div class="item-sklad"><label>Склад: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_sklad', true ).'</span></div>';
	echo '</div>';
	echo '<div class="zakaz-field">'.get_post_meta( $post->ID, '_checkbox', true ).'</div>';
}
////


p.s. я могу предоставить доступ к сайту, если вы возьметесь

**Comment by VsevolodKobzar** [comment]
@uptimizt нашел в структуре такой кусок, если я правильно понимаю - он отвечает за вывод...

```
//Добавляем поля в товар
add_action( 'woocommerce_product_options_inventory_product_data', 'art_woo_add_custom_fields' );
function art_woo_add_custom_fields() {
	global $product, $post;
	echo '<div class="options_group">';// Группировка полей

	woocommerce_wp_checkbox( array(
   'id'            => '_checkbox',
   'wrapper_class' => 'show_if_simple',
   'label'         => 'Под заказ',
   'description'   => '',
		) );

	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_mel',
		 'label'             => __( 'ул. Мельникайте, 98', 'woocommerce' ),
		 'placeholder'       => 'Остаток Мельникайте',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_okt',
		 'label'             => __( 'ул. 50 лет октября, 21', 'woocommerce' ),
		 'placeholder'       => '50 лет октября',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_zel',
		 'label'             => __( 'ул. Николая Зелинского, 16', 'woocommerce' ),
		 'placeholder'       => 'Николая Зелинского',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
    ) );
    woocommerce_wp_text_input( array(
		 'id'                => '_number_field_gn',
		 'label'             => __( 'ул. В. Гнаровской, 12 кор. 9', 'woocommerce' ),
		 'placeholder'       => 'В. Гнаровской',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	woocommerce_wp_text_input( array(
		 'id'                => '_number_field_sklad',
		 'label'             => __( 'Склад', 'woocommerce' ),
		 'placeholder'       => 'Склад',
		 'description'       => __( 'Вводятся только числа', 'woocommerce' ),
		 'type'              => 'number',
		 'custom_attributes' => array(
				'step' => 'any',
				'min'  => '0',
		 ),
	) );
	echo '</div>';
}

add_action( 'woocommerce_process_product_meta', 'art_woo_custom_fields_save', 10 );
function art_woo_custom_fields_save( $post_id ) {
   // Сохранение цифрового поля
	 $woocommerce_number_field = $_POST['_checkbox'];
   if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_checkbox', esc_attr( $woocommerce_number_field ) );
   }
   $woocommerce_number_field = $_POST['_number_field_mel'];
   if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_mel', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_okt'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_okt', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_zel'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_zel', esc_attr( $woocommerce_number_field ) );
   }
   $woocommerce_number_field = $_POST['_number_field_gn'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_gn', esc_attr( $woocommerce_number_field ) );
   }
	 $woocommerce_number_field = $_POST['_number_field_sklad'];
	 if ( !empty($woocommerce_number_field)) {
      update_post_meta( $post_id, '_number_field_sklad', esc_attr( $woocommerce_number_field ) );
   }
 			else {
      // Иначе удаляем созданное поле из бд
      delete_post_meta( $post_id, '_product_field_type_ids');
   }
}

add_action( 'woocommerce_after_add_to_cart_form', 'art_get_text_field_before_add_card' );
function art_get_text_field_before_add_card() {
	global $post;
	echo '<div class="sklad">';
	echo '<div class="nalichie-title">Наличие в магазинах:</div><div class="nalichie-subtitle">Фактическое наличие уточняйте по телефону</div>';
	echo '<div class="item-sklad"><label>ул. Мельникайте, 98: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_mel', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 589-294</span></div>';
	echo '<div class="item-sklad"><label>ул. 50 лет октября, 21: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_okt', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 601-704</span></div>';
    echo '<div class="item-sklad"><label>ул. Николая Зелинского, 16: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_zel', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 605-451</span></div>';
    echo '<div class="item-sklad"><label>ул. В. Гнаровской, 12 кор. 9: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_gn', true ).'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 606-400</span></div>';
	echo '<div class="item-sklad"><label>Склад: </label><span class="count">'.get_post_meta( $post->ID, '_number_field_sklad', true ).'</span></div>';
	echo '</div>';
	echo '<div class="zakaz-field">'.get_post_meta( $post->ID, '_checkbox', true ).'</div>';
}
////
``

p.s. готов предоставить доступ к сайту если возьметесь или подскажите пожалуйста что поменять (если тут)

**Comment by VsevolodKobzar** [comment]
@uptimizt проблема решена! Спасибо за наводку!

Оказалось, что было необходимо посмотреть что скприпт грузит в метаполе, и потом оттуда значения прописать! Всё оказалось очень просто! Оставляю код, может будет полезно комунибудь!

```
add_action( 'woocommerce_after_add_to_cart_form', 'art_get_text_field_before_add_card' );
function art_get_text_field_before_add_card() {
	global $post;
	$sklads = get_post_meta( $post->ID, 'wooms_stock_by_store', true );
	echo '<div class="sklad">';
	echo '<div class="nalichie-title">Наличие в магазинах:</div><div class="nalichie-subtitle">Фактическое наличие уточняйте по телефону</div>';
	echo '<div class="item-sklad"><label>ул. Мельникайте, 98: </label><span class="count">'.$sklads['items']['https://online.moysklad.ru/api/remap/1.1/entity/store/f68686ff-d487-11e9-0a80-04600012a1c3']['stock'].'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 589-294</span></div>';
	echo '<div class="item-sklad"><label>ул. 50 лет октября, 21: </label><span class="count">'.$sklads['items']['https://online.moysklad.ru/api/remap/1.1/entity/store/debedf2e-d487-11e9-0a80-0269001224cb']['stock'].'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 601-704</span></div>';
    echo '<div class="item-sklad"><label>ул. Николая Зелинского, 16: </label><span class="count">'.$sklads['items']['https://online.moysklad.ru/api/remap/1.1/entity/store/c89e532a-d487-11e9-0a80-03e80011ae5e']['stock'].'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 605-451</span></div>';
    echo '<div class="item-sklad"><label>ул. В. Гнаровской, 12 кор. 9: </label><span class="count">'.$sklads['items']['https://online.moysklad.ru/api/remap/1.1/entity/store/36b6893b-ca2e-11e9-9107-5048000241b4']['stock'].'</span><br/><span style="font-size:13px;">Телефон: +7 (3452) 606-400</span></div>';
	echo '<div class="item-sklad"><label>Склад: </label><span class="count">'.$sklads['items']['https://online.moysklad.ru/api/remap/1.1/entity/store/c2afdb1c-f41e-11e9-0a80-047700209f44']['stock'].'</span></div>';
	echo '</div>';
	echo '<div class="zakaz-field">'.get_post_meta( $post->ID, '_checkbox', true ).'</div>';
}
