### ISSUE TITLE
Сделать настройку для выключения резерва товаров

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#20]
Требуется сделать настройку для возможности отключения резервирования товаров пи синхронизации заказов. Не всем данный функционал нужен

**Comment by uptimizt** [comment]
зачем? в чем смысл опции? при каких сценариях она имеет ценность?

**Comment by artikus11** [comment]
Не всем нужно резервировать товары. Почему не знаю, но раз не всем это нужно, имеет смысл сделать настройку, чтобы можно было отключить данный функционал при необходимости

**Comment by uptimizt** [comment]
Я не понимаю как делается резерв или не делается?
Мы просто вроде бы предаем данные о количестве продуктов в заказе.
Там можно как то помечать резерв? Есть ссылка на доки по API?

**Comment by ni032mas** [comment]
У позиции заказа покупателя есть атрибут **reserve** - Резерв данной позиции, думаю это оно.

**Comment by artikus11** [comment]
@uptimizt Можно. https://online.moysklad.ru/api/remap/1.1/doc/index.html#%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7-%D0%BF%D0%BE%D0%BA%D1%83%D0%BF%D0%B0%D1%82%D0%B5%D0%BB%D1%8F
Выше верно сказали. атрибут **reserve** 
А мы при передаче заказа передаем количество каждого товара в заказе в зависимости от настройки https://gitlab.com/wpcraft/wooms-extra/blob/master/inc/class-orders-sending.php#L319

**Comment by artikus11** [comment]
@uptimizt Такая настройка уже есть. В 1.7.9 отрелизилась

**Comment by uptimizt** [comment]
настройка или код? надо галочку нажимать или сразу так работает? @artikus11

**Comment by uptimizt** [comment]
тест ок
