### ISSUE TITLE
Как скрыть группу товаров с сайта?

### ISSUE THREAD

**Issue by VsevolodKobzar** [wpcraft-ru/wooms#200]
@uptimizt  Доброго времени суток!

В группе товаров есть одна группа (с подгруппами), которую надо скрыть - не можем разобраться как этл настроить, возможно вопрос задавался - дайте пожалуйста ссылку на описание как это лучше реализовать? 

Предполагаю, что надо сделать 2 глобальных группы - одна для сайта, другая не для сайта, и в плагине указать в пункте *Ограничить группой товаров* - группу, которая предназначена для сайта. Прошу дать комментарий если прав, описание у модуля не очевидное...

**Comment by uptimizt** [comment]
решение тут https://github.com/wpcraft-ru/wooms/issues/297
