### ISSUE TITLE
Как включить работу с модификациями и вариациями товаров (продуктов)?

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#206]
перейти в раздел МойСклад / Настройки
опция называется: Включить синхронизацию вариаций

![image](https://user-images.githubusercontent.com/1852897/71321702-8c10de00-24ce-11ea-96cb-39a13a2abfcd.png)

**Comment by a1exnet** [comment]
Добрый день! Функция синхронизирует только модификации/вариации или остатки модификаций тоже передает в остатки на уровне вариаций товара?

**Comment by uptimizt** [comment]
> Добрый день! Функция синхронизирует только модификации/вариации или остатки модификаций тоже передает в остатки на уровне вариаций товара?

вопрос не понятен.

должно синкать остатки по всем модификациям и вариациям

если это не так - создайте новый ишью и опишите проблему и как ее повторить
