### ISSUE TITLE
Синхронизация вариаций на Сайте с учетом обычных товаров на Складе

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#207]
Встречается такой кейс, когда Клиент хранит товары на Складе как обычные, а на Сайте хочет работать с ними как с вариациями.

Например: Вариации и модификации с артикулами #91

Нужно изучить техническую возможность сделать опцию, которая позволит работать с такими условиями.

# dod
-  добавить класс в wooms-xt типа SimpleAsVariationHack
- сделать опцию типа "Включить работу с простыми продуктами как с вариативными"
- добавить описание что это такое + ссылка на этот тикет с детализацией решения
- релизовать подмену данных о типе продукта через хук (см комменты ниже)
- закрыть тикет тут https://github.com/wpcraft-ru/wooms/issues/91

# ХД
3256 3031

**Comment by uptimizt** [comment]
Есть информация о том что в старых версиях синк как то работал при таких условиях.

Подозреваю что перестало работать когда мы добавили код, который при каждом синке стал жестко задавать тип продукта на Сайте.

**Comment by uptimizt** [comment]
Возможно решением будет добавить опцию, которая будет отключать этот выбор типа продукта.

Тогда плагину будет не важно какой тип продукта?

Он будет просто брать продукт по артикулу и обновлять ему данные. Даже если этот продукт на Сайте хранится как вариация, а на Складе как обычный. В остальном данные совпадают.

Но без экспериментов сложно сказать на сколько это рабочее решение.

**Comment by uptimizt** [comment]
Есть информация о том что даже в текущей версии если указать у обычных товаров в МойСклад артикул и такой же артикул у вариаций, то синк самих товаров происходит ок.

**Comment by uptimizt** [comment]
Заказы при этом не отправляются.
Метод:
```

    /**
     * Get data of positions the order
     *
     * @param $order_id
     *
     * @return array|bool
     */
    public static function get_data_positions($order_id)
    {
        $order = wc_get_order($order_id);
        $items = $order->get_items();
        if (empty($items)) {
            return false;
        }
        $data = array();
        foreach ($items as $key => $item) {
            if ($item['variation_id'] != 0) {
                $product_id   = $item['variation_id'];
                $product_type = 'variant';
            } else {
                $product_id   = $item["product_id"];
                $product_type = 'product';
            }

            // правка
            $product_type = 'product';

            $uuid = get_post_meta($product_id, 'wooms_id', true);

            if (empty($uuid)) {
                continue;
            }

            if (apply_filters('wooms_order_item_skip', false, $product_id, $item)) {
                continue;
            }

            $price    = $item->get_total();
            $quantity = $item->get_quantity();
            if (empty(get_option('wooms_orders_send_reserved'))) {
                $reserve_qty = $quantity;
            } else {
                $reserve_qty = 0;
            }

            $data[] = array(
                'quantity'   => $quantity,
                'price'      => ($price / $quantity) * 100,
                'discount'   => 0,
                'vat'        => 0,
                'assortment' => array(
                    'meta' => array(
                        "href"      => "https://online.moysklad.ru/api/remap/1.1/entity/{$product_type}/" . $uuid,
                        "type"      => "{$product_type}",
                        "mediaType" => "application/json",
                    ),
                ),
                'reserve'    => $reserve_qty,
            );
        }

        return $data;
    }
```

**Comment by uptimizt** [comment]
см коммент правка в сниппете выше.
если жестко указать что продукт обычный при подготовке данных по позициям для Заказа - тогда все работает.

надо придумать опцию, которая на хуке wooms_order_update_data будет делать такую подмену

**Comment by VictorSharov** [comment]
Здравствуйте, вами вручную на сайте добавлялась поддержка таких товаров. После обновления плагина до версии 4.0 снова все перестало работать в такой ситуации.

**Comment by uptimizt** [comment]
@Aharonyan зачем эта задача ушла в работу? при том что есть куча не доделанных задач в работе?

**Comment by VictorSharov** [comment]
Здравствуйте, есть ли у вас новости по исправлению ошибки? Мы заплатили за ваш плагин 6 авгутса 8000р. Прошло 9 месяцев, вы игнорируете все мои письма. Мы не можем пользоваться плагином. Что это за мошенничество?

**Comment by uptimizt** [comment]
> Здравствуйте, есть ли у вас новости по исправлению ошибки? Мы заплатили за ваш плагин 6 авгутса 8000р. Прошло 9 месяцев, вы игнорируете все мои письма. Мы не можем пользоваться плагином. Что это за мошенничество?

@VictorSharov 

тут сложный вопрос. это не ошибка плагина. это стандартная логика работы, которую в рамках этой задачи мы попытаемся нарушить и обойти. 
нарушение стандартной логики - сложная разработка. которая требует времени.

пока все силы уходят на те задачи которые точно ошибки и которые точно нужно исправлять.
на данное хакерство пока ресурсов не хватает.

и это точно не мошенничество. мы можем вернуть оплату за заказ если вы так считаете.

**Comment by VictorSharov** [comment]
Да, прошу вернуть оплату. Плагином пользоваться мы не можем.

Kind regards,
Victor Sharov

On 17 March 2020 at 20:17:53, Anatoly Yumashev (notifications@github.com) wrote:

Здравствуйте, есть ли у вас новости по исправлению ошибки? Мы заплатили за ваш плагин 6 авгутса 8000р. Прошло 9 месяцев, вы игнорируете все мои письма. Мы не можем пользоваться плагином. Что это за мошенничество?

@VictorSharov

тут сложный вопрос. это не ошибка плагина. это стандартная логика работы, которую в рамках этой задачи мы попытаемся нарушить и обойти.
нарушение стандартной логики - сложная разработка. которая требует времени.

пока все силы уходят на те задачи которые точно ошибки и которые точно нужно исправлять.
на данное хакерство пока ресурсов не хватает.

и это точно не мошенничество. мы можем вернуть оплату за заказ если вы так считаете.

**Comment by diSWAG** [comment]
"Подозреваю что перестало работать когда мы добавили код, который при каждом синке стал жестко задавать тип продукта на Сайте."

Подскажите, а как убрать эту проверку, чтобы синк в таком виде заработал?

**Comment by uptimizt** [comment]
думаю это решается только через доп плагин - в базе такое не решить
