### ISSUE TITLE
Исправить конфликты разных операционных систем при скачивания фотографий

### ISSUE THREAD

**Issue by Aharonyan** [wpcraft-ru/wooms#211]

**Comment by uptimizt** [comment]
@Aharonyan что тут?

**Comment by ljutaev** [comment]
> @Aharonyan что тут?

на локалке виндовс, на сервере линукс и у меня на работает загузка выдает ошибку

**Comment by uptimizt** [comment]
> на локалке виндовс, на сервере линукс и у меня на работает загузка выдает ошибку

@ljutaev попробуйте Local https://localwp.com/

вроде бы порешали все
