### ISSUE TITLE
Некорректная синхронизация и остановка при загрузке 20 записей

### ISSUE THREAD

**Issue by San4o-dev** [wpcraft-ru/wooms#213]
Прошу прощения за то, что засоряю Гитхаб своими вопросами, но в чате вы не отвечаете, так что пишу здесь.

Вопрос по синхронизации "Мой склад" и WP.

Возможно уже сталкивались с подобным. Проблема следующая:
Настроена синхронизация по расписанию с "Мой склад", товарных позиций ~2 тыс. (на всех складах), из них в наличии, допустим для основного склада, ~350 шт.

Есть как простые, так и вариативные товары.
После выгрузки не все товары показываются "В наличии" (из 350 товаров в наличии, отображается лишь 250).
Конкретно эта проблема зафиксирована у вариативных товаров. У них не подгружаются атрибуты, соответственно не отображаются вариации и "теряется" наличие.

Однако если запустить отдельную синхронизацию для товара-"потеряшки", то атрибуты прогрузятся нормально и отобразится "В наличии".

Из особенностей:
1. Сайт работает на поддоменах через "Мультисайт" WP: 1 склад = 1 поддомен (всего 8 шт.)
2. Сайт работал на обычном хостинге, была повышенная нагрузка — перенесли на VDS, пока нагрузка стабильная.
3. У каждого сайта-поддомена в настройках указан один и тот же администратор "Мой склад".

С чем может быть связана данная проблема? Может мы что-то некорретно указали в настройках или какая-то беда с "Мой склад"?

Очень прошу Вашей помощи. Буду Вам благодарен.

ВАЖНО!
Теперь возникла новая проблема. Синхронизация останавливается на 20 записях. Загружается 20 позиций и всё... Что можно с этим сделать?

**Comment by uptimizt** [comment]
@San4o-dev Александр - большое спасибо что смогли сделать тикет тут. Если бы все клиенты так делали - головной боли и потерь времени у нас было бы меньше :) А значит больше ресурсов могли бы тратить на разработку :)

Что касается проблемы. Мы с таким сценарием еще не встречались. Вероятно придется подумать :)

Основная проблема кроется в механизме синка по Складу.
Система не умеет понимать какой товар создавать и обходить, а какой нет? Потому плагин вынужден оббегать все 2тыс товаров и смотреть какие есть на складе?

От сюда вероятно большие нагрузки на интерфейс. МойСклад может за такое блокировать запросы.

Идеальное решение с моей точки зрения:
1. отказ от мультисайта
2. переход на мультисклады в 1 сайте

у п. 2 есть еще два варианта решения:
1. делать просто виджет остатков по складам - проще
2. делать поддомены по городам - сильно сложнее и дороже

Либо искать пути оптимизации синка по складам. 
Изучим новую версию протокола, мб там добавили какие то методы или опции под данный сценарий.

**Comment by San4o-dev** [comment]
Благодарю за ответ!
Как я писал ранее на почте — проблему с остановкой загрузки товаров на 20 шт. решили (были проблемы со стороны хостинг-провайдера).

А вот оптимизации синка по складам были бы очень рады.
Если нужные какие-то дополнительные ресурсы для ускорения работ — сообщите, готовы оплатить.

Успехов Вам!

**Comment by milkaa66** [comment]
Подскажите, как решили проблему с остановкой загрузки товаров на 20 шт.?

**Comment by uptimizt** [comment]
> Подскажите, как решили проблему с остановкой загрузки товаров на 20 шт.?

@milkaa66 
раньше была только 1 причина - сломанный крон.
теперь мы переходим на новый механизм синка ActionSheduler. тут причина таже, но плюс добавляется еще одна - слишком старая версия WooCommerce ниже 3.6 версии.

**Comment by milkaa66** [comment]
У нас проблема решилась путём отключения плагина для кэширования Redis

**Comment by uptimizt** [comment]
@milkaa66 да добавили задачу https://github.com/wpcraft-ru/wooms/issues/320

постараемся поправить механику, чтобы не зависеть от кривых настроек внешнего объектного кеша.

**Comment by uptimizt** [comment]
@San4o-dev у вас также беда может быть связана с объектным кешем.

ну а история со складами - лучше делать так как у Спортмастера и др крупных игроков.

иметь 1 сайт, 1 базу товаров, но склады делать на подпапках или поддоменах, но без мультисайта и дубликации данных.

**Comment by uptimizt** [comment]
в 9х версии должно быть исправлено - надо проверить
