### ISSUE TITLE
Задвоение продуктов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#23]
при этом один продукт помечен как Нет в наличии, а второй в наличии.
wooms_id у обоих одинаковый. например 27998481-9193-11e7-6b01-4b1d003bf072

это значит что в волкере, там где есть метод получения по wooms_id что то пошло не так.

![image](https://user-images.githubusercontent.com/1852897/44164947-1756b400-a0d0-11e8-9275-fbd690917d0b.png)

**Comment by uptimizt** [comment]
@artikus11 есть идеи?

**Comment by uptimizt** [comment]
ошибка плавающая. пока не удалось повторить

**Comment by artikus11** [comment]
@uptimizt А как ты тестировал? На чистовую? Или так как есть?

**Comment by uptimizt** [comment]
> А как ты тестировал? На чистовую? Или так как есть?

последовательность не запомнил. просто синкал как то )

**Comment by artikus11** [comment]
@uptimizt Не надо закрывать. Пока не могу понять почему это происходит. Иногда, очень редко появляется, надо поймать это состояние и полечить. Как раз сейчас синком из рубрик 2-го уровня занимаюсь, заодно займусь
