### ISSUE TITLE
Параллельные процессы надо как то порешать

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#233]
возможно это проблема

если 2 раза запустить процесс в 1 время, если 2й процесс стартует, пока 1й не выполнился, то они по сути начнут загружть одну и туже пачку продуктов

![image](https://user-images.githubusercontent.com/1852897/75162553-cac14f80-572e-11ea-9fa4-ec8562c24d0d.png)

**Comment by uptimizt** [comment]
@Aharonyan 

решение от сюда: https://actionscheduler.org/perf/

```
add_filter( 'action_scheduler_queue_runner_concurrent_batches', function($concurrent_batches){
	return 1;
});
```

рабочее. но оно делает ограничение на все задачи.

в идеале найти решение на конкретную задачу. мб поиграть с аргументами.

но если ничего не найдется, то можно пробовать это

**Comment by Aharonyan** [comment]
Решил проблему в рамках задачи #215
