### ISSUE TITLE
не могу заставить синхронизировать атрибуты

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#239]
не могу заставить синхронизировать атрибуты. Галочка стоит, но кроме картинки и описания - не хочет.

доп поля есть, но не синкаются как атрибуты в продукты Woo

## HD
830-903484
3580

## SH
![image_2020-02-28_12-07-25](https://user-images.githubusercontent.com/1852897/75714054-071b1f80-5cdc-11ea-8541-80aab17efed2.png)

**Comment by uptimizt** [comment]
@Aharonyan протестишь?

**Comment by Aharonyan** [comment]
![photo_2020-03-04_17-06-29](https://user-images.githubusercontent.com/48214689/75892150-dfde6280-5e41-11ea-885c-e021e879c79f.jpg)

Проверили у нас все нормально @uptimizt

**Comment by uptimizt** [comment]
@Aharonyan надо попробовать добавить доп атрибуты разных типов. см снимок.

**Comment by uptimizt** [comment]
пока проблема не проявлялась
