### ISSUE TITLE
Передачи стоимости доставки в Заказы

### ISSUE THREAD

**Issue by Taimerlan** [wpcraft-ru/wooms#241]
Не работает передача стоимости и самой позиции доставки .
https://github.com/wpcraft-ru/wooms/issues/174
Все настройки вроде бы выставлены верно. Код позиции для передачи стоимости доставки выполняется. 
Проблема происходит в момент передачи, но я не могу понять где. 
Версия плагина XT 6.1.

**Comment by uptimizt** [comment]
> Не работает передача стоимости и самой позиции доставки .
> #174
> Все настройки вроде бы выставлены верно. Код позиции для передачи стоимости доставки выполняется.
> Проблема происходит в момент передачи, но я не могу понять где.
> Версия плагина XT 6.1.

@Taimerlan возможно старая версия плагина. В 7 версии тесты прошли положительно.
