### ISSUE TITLE
Стоимость доставки перестала передаваться

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#244]
решение было тут https://github.com/wpcraft-ru/wooms/issues/174
потом было изменение https://github.com/wpcraft-ru/wooms/issues/186

возможно что то сломалось.

пример: https://wooms.wpcraft.ru/wp-admin/post.php?post=6716&action=edit

- [x] надо исправить
- [ ] релиз
- [x] сообщить о результат в ХД

**Comment by uptimizt** [comment]
@Aharonyan что за ошибка?
![image](https://user-images.githubusercontent.com/1852897/76549541-b22c9580-64a1-11ea-8f48-a40645b0dcec.png)

**Comment by Aharonyan** [comment]
@uptimizt исправил
