### ISSUE TITLE
Изменить API на 1.2 для отправки статуса Заказов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#246]
в 1.1 версии которая сейчас есть беда. можно только 1 хук делать на изменение статуса заказов.

если есть 2 магазина или магаз + CRM которая этот хук занимает, то статус перестает передаваться в магаз.

в версии 1.2 можно делать 2 и более хука в разные сайты.

надо обновиться.

так чтобы можно было добавлять хук без учета конкуренции.

Кейсы:
1. добавить хук на локальном контуре
2. добавить хук на тест контуре

проверить что в тест контуре обновление статуса прилетает.

**Comment by Aharonyan** [comment]
@uptimizt пока ждем что нам дадут доступ к этой функции для работы 
![image](https://user-images.githubusercontent.com/48214689/76799897-83852680-67e3-11ea-823c-66920ac39f92.png)

**Comment by uptimizt** [comment]
сменил API на версию 1.2 - пока полет норм. но тестить не получится тк МойСклад пока не отвечает.
