### ISSUE TITLE
Как исправить генерацию номера заказа в WooMS?

### ISSUE THREAD

**Issue by Ba11istique** [wpcraft-ru/wooms#258]
Здравствуйте, вордпресс при подключении плагина, и тестовом оформлении заказа, номер этого самого заказа генерируется рандомно. А не так как нужно. От 100 до 500. Где и как это можно поправить? Чтобы номер заказа соответствовал тому что генерируется в моем складе?

**Comment by uptimizt** [comment]
> Здравствуйте, вордпресс при подключении плагина, и тестовом оформлении заказа, номер этого самого заказа генерируется рандомно. А не так как нужно. От 100 до 500. Где и как это можно поправить? Чтобы номер заказа соответствовал тому что генерируется в моем складе?

1. пока нет идей. номер генерируется силами WooCommerce. мы на это не влияем.
2. это может приводить к проблеме дубликации номеров. для защиты от этой проблемы есть опция подстановки символа к номеру заказа. проблема решаема.

возможно что то придумать еще. но нужно понимать какую проблему решаем?
