### ISSUE TITLE
Надо, чтобы на каждом заказе была зафиксирована настройка "резерв"

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#26]
Заказ загружается в Мой Склад, но опция "доступно" не уменьшается. В техподдержке Моего Склада мне сказали, что для того, чтобы опция "доступно" уменьшалась надо, чтобы на каждом заказе была зафиксирована настройка "резерв". Сейчас этого нет.

ХД 933

**Comment by artikus11** [comment]
@uptimizt Это давно сделано. Можно закрывать
