### ISSUE TITLE
Комплекты МойСклад и товары WooCommerce - один из кейсов настройки

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#269]
# вопрос 

- возможно ли сделать синхронизацию комплектов с МС аналогично как это сделано с доставкой? я делаю товар на сайте вручную, задаю артикул комплекта, и при покупке товара, в заказе МС отображался комплект с аналогичным артикулом?  (попробовал сделать это, но у меня пропадает эта позиция в заказе, возможно сделал что-то не так)

# решение

отключил в настройках управление групповыми продуктами и комплекты из МС начали импортироваться как простой товар. При покупке такого товара в МС заходит заказ с комплектом от того же артикула. 

З.Ы. единственное, что надо вручную включить в управлении запасами статус «в наличии»

ХД 3686

**Comment by Fun-mask** [comment]
Делаю всё то же самое, но не работает так как у вас. Товар в МС - комплекс, на сайте - Простой товар. При синхронизации с МС автоматически происходит изменение настроек такого товара на Видимость в каталоге: Скрыто

**Comment by Fun-mask** [comment]
Проблему скрытия решил установкой галочки в настройках МС в админке сайте на "Отключить скрытие продуктов". Но при заказе комплекта на сайте в Мой склад передаётся пустой заказ
