### ISSUE TITLE
МойСклад добавил возможность загрузки нескольких фотографий. 

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#27]
# Проблема

В МойСклад появилась возможность указать множество картинок у товара. Но плагин загружает только одну.

# Решение

В текущей версии протокола обмена этой возможности нет. В новой версии появится. Ждем выхода новой версии.

# Как быть?

Пока можно добавлять картинки на сайте. Многие вообще не используют хранение картинок в МойСклад. А хранят их на сайте. Так выше качество и больше возможностей делать более красивое оформление.

ХД 838, 823

**Comment by artikus11** [comment]
@uptimizt Етить... Галерею надо создавать? Надо посмотреть как это в МС реализовано

**Comment by artikus11** [comment]
Пока нет возможности подгружать несколько картинок. Еще АПИ МС не обновилось. Обещают в конце августа https://support.moysklad.ru/hc/ru/community/posts/360002871768-%D0%9D%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BA-%D0%B2-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B5?input_string=%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BA%20%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B0
![image](https://user-images.githubusercontent.com/16116688/44484019-a5e1ad00-a65d-11e8-9f7f-a8f0be7bff1e.png)

**Comment by GodoLoki** [comment]
Этот вопрос еще не решен? Загружает только одну картинку

**Comment by artikus11** [comment]
@GodoLoki Обновления АПИ еще не было, как в МойСклад АПИ обновят, так сделаем загрузку галерей

**Comment by uptimizt** [comment]
Есть рекомендация от МойСклад на то что можно брать из новой версии https://support.moysklad.ru/hc/ru/community/posts/360034783253-%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B0-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%A1MS-Bitrix

**Comment by uptimizt** [comment]
Документация https://moysklad.github.io/api-remap-1.2-doc/api/remap/1.2/ru/#izobrazhenie

**Comment by VsevolodKobzar** [comment]
@uptimizt подскажите, эта функция ещё не реализоавна?
