### ISSUE TITLE
Отправка заказов с сайта в Мой Склад

### ISSUE THREAD

**Issue by Daryaarti** [wpcraft-ru/wooms#270]
Активировала функцию "Включить автоматическую синхронизацию заказов в МойСклад". Один заказ прошел. Последующие заказы не синхронизируются.
Вручную они не выгружаются. На странице заказа в админке сайта в блоке "МойСклад" стоит галочка "Синхронизировать", но это ничего не даёт - заказы не синхронизируются.
![joxi_screenshot_1586510561125](https://user-images.githubusercontent.com/63449100/78980661-52d1ac00-7b59-11ea-8a5e-b145c11267a9.png)

# HD
933-744936

**Comment by uptimizt** [comment]
> Активировала функцию "Включить автоматическую синхронизацию заказов в МойСклад". Один заказ прошел. Последующие заказы не синхронизируются.
> Вручную они не выгружаются. На странице заказа в админке сайта в блоке "МойСклад" стоит галочка "Синхронизировать", но это ничего не даёт - заказы не синхронизируются.
> ![joxi_screenshot_1586510561125](https://user-images.githubusercontent.com/63449100/78980661-52d1ac00-7b59-11ea-8a5e-b145c11267a9.png)

Здравствуйте.

Могут быть какие то ошибки в конфигурации или синхронизации.
Давайте соберем больше информации.
Тут есть инструкция как это сделать лучше: https://github.com/wpcraft-ru/wooms/issues/272

**Comment by Daryaarti** [comment]
Здравствуйте! Обновила плагин до новой версии, проверила настройки. Всё
равно не выходит.
Заметила следующего рода ошибку " Ошибка сохранения webhook: webhook с
данным набором параметров уже существует " - как это исправить я не знаю.
Очень надеюсь на Вашу помощь!

Отправляю информацию о здоровье сайта.
`
### wp-core ###

version: 5.4
site_language: ru_RU
user_language: ru_RU
timezone: +03:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/host1772803/kamchatka-terra-incognita.com/htdocs/www
wordpress_size: 55,03 MB (57705712 bytes)
uploads_path: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/uploads
uploads_size: 1,65 GB (1770841308 bytes)
themes_path: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/themes
themes_size: 23,26 MB (24386833 bytes)
plugins_path: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/plugins
plugins_size: 106,63 MB (111807135 bytes)
database_size: 50,55 MB (53002240 bytes)
total_size: 1,88 GB (2017743228 bytes)

### wp-active-theme ###

name: Oxygen - Child Theme | Shared by VestaThemes.com (dark_studio)
version: 1.0
author: Laborator
author_website: https://laborator.co/
parent_theme: Oxygen | Shared by VestaThemes.com (oxygen)
theme_features: post-thumbnails, menus, widgets, automatic-feed-links,
featured-image, title-tag, woocommerce, wc-product-gallery-slider,
wc-product-gallery-zoom, wc-product-gallery-lightbox
theme_path: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/themes/dark_studio

### wp-parent-theme ###

name: Oxygen | Shared by VestaThemes.com (oxygen)
version: 5.2.4
author: Laborator
author_website: https://laborator.co/
theme_path: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/themes/oxygen

### wp-plugins-active (20) ###

Advanced Custom Fields PRO: version: 5.7.13, author: Elliot Condon (latest
version: 5.8.9)
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd:
version: 5.1.0, author: SeedProd
Contact Form 7: version: 5.1.6, author: Takayuki Miyoshi (latest version:
5.1.7)
Cyr-To-Lat: version: 4.3.2, author: Sergey Biryukov, Mikhail Kobzarev, Igor
Gergel (latest version: 4.3.5)
Envato Market: version: 2.0.3, author: Envato
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Loco Translate: version: 2.3.1, author: Tim Whitlock (latest version: 2.3.3)
Russian Post and EMS for WooCommerce: version: 1.3.1, author: Artem Komarov
(latest version: 1.3.2)
Slider Revolution: version: 5.4.8.3, author: ThemePunch
TranslatePress - Multilingual: version: 1.6.5, author: Cozmoslabs, Razvan
Mocanu, Madalin Ungureanu, Cristophor Hurduban (latest version: 1.7.0)
WooCommerce: version: 4.0.0, author: Automattic (latest version: 4.0.1)
WooCommerce CDEK: version: 0.8.5, author: WPCraft
WOOCS - WooCommerce Currency Switcher: version: 1.3.0, author: realmag777
(latest version: 1.3.1)
WooMS: version: 7.0, author: WPCraft
WooMS XT (Extra): version: 7.0, author: WPCraft
Wordfence Security: version: 7.4.4, author: Wordfence (latest version:
7.4.6)
WPBakery Page Builder: version: 5.7, author: Michael M - WPBakery.com
(latest version: 6.1)
YITH WooCommerce Product Bundles: version: 1.1.22, author: YITH
YITH WooCommerce Wishlist: version: 3.0.5, author: YITH (latest version:
3.0.9)
Робокасса WooCommerce: version: 1.2.35, author: Робокасса (latest version:
1.3.3)

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic (latest version:
4.1.4)
GTranslate: version: 2.8.50, author: Translate AI Multilingual Solutions
(latest version: 2.8.54)

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1656
imagemagick_version: ImageMagick 6.7.8-9 2019-02-01 Q16
http://www.imagemagick.org
imagick_limits:
imagick::RESOURCETYPE_AREA: 125 GB
imagick::RESOURCETYPE_DISK: -1
imagick::RESOURCETYPE_FILE: 75000
imagick::RESOURCETYPE_MAP: 125 GB
imagick::RESOURCETYPE_MEMORY: 63 GB
imagick::RESOURCETYPE_THREAD: not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 3.10.0-1062.12.1.el7.x86_64 x86_64
httpd_software: Apache/2.2.35-dev (Unix) mod_ssl/2.2.35-dev
OpenSSL/1.0.2k-fips Phusion_Passenger/5.1.12 PHP/7.1.33 mod_wsgi/4.6.2
Python/3.6
php_version: 7.1.33 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 60
memory_limit: 384M
max_input_time: 60
upload_max_size: 256M
php_post_max_size: 256M
curl_version: 7.29.0 NSS/3.44
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.29-32-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id:
38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content
WP_PLUGIN_DIR: /home/host1772803/
kamchatka-terra-incognita.com/htdocs/www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 384M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wooms-plugin-debug ###

Wooms Version: 7.0 ✔️
WoomsXT Version: 7.0 ✔️
wooms-tariff-for-orders: Ошибка сохранения webhook: webhook с данным
набором параметров уже существует ❌
Woocommerce: 4.0.0 ✔️
wooms-plugins-versions: WooMS(7.0) = WooMS XT(7.0) ✔️

`

вс, 12 апр. 2020 г. в 04:17, Anatoly Yumashev <notifications@github.com>:

**Comment by uptimizt** [comment]
@Daryaarti 

лучше посмотреть логи по части передачи заказов.

обычно такие ошибки бывают в следующих ситуациях:
1. товар в заказе не синхронизирован и валятся ошибки о том что товар не удалось связать
2. на стороне мойсклад добавлены какие то доп поля обязательные и плагин их не может заполнить
3. указано не верное юр лицо в настройках плагина
