### ISSUE TITLE
Если товар находится в самой нижней ветке дерева категории МС, проставлять автоматично все категории выше по дереву при синхронизации, как решить?

### ISSUE THREAD

**Issue by ljutaev** [wpcraft-ru/wooms#282]
Проблема в том, что в МС можно прикреплять товар только к одной категории, за частую все виглядит так: Акссесуары / Телефоны / Айфоны.  Товар прикреплен к самой нижней категории  Айфоны. При импорте, товар находиться только в категории айфоны, можно ли зделать так, ч то-
бы проставлялись и все родительский категории?
После импорта сейчас:
![Screenshot_1](https://user-images.githubusercontent.com/6756977/80802152-343e5e00-8bb7-11ea-8439-a548c2d115a5.png)
После импорта нужно:
![Screenshot_2](https://user-images.githubusercontent.com/6756977/80802198-5cc65800-8bb7-11ea-834f-ae6e3693986a.png)

**Comment by ljutaev** [comment]
`add_filter('wooms_product_save', 'gc_product_save', 30, 3);


function gc_product_save( $product, $value, $data ) {

	$result = null;
	$ancestors = [];

	$product_id = $product->get_id();

	$terms = get_the_terms( $product_id, 'product_cat' );

	// by default wooms set 1 cat
    if( count( $terms ) == 1 ) {
    	if( $terms[0]->parent != 0 ) {
    		$cat_id = $terms[0]->term_id;
    		$ancestors = get_ancestors( $cat_id, 'product_cat' );
            $ancestors[] = $cat_id;

            $result = $product->set_category_ids( $ancestors );

            if( ! is_null( $result ) || ! is_wp_error( $result ) ) {
				do_action('wooms_logger',
			        'gc',
			        sprintf(
			            'Проставлены категории: (%s), для продукта %s (%s).',
						implode(",", $ancestors),
						$product->get_name(),
						$product->get_id()
			        )
			    );
		    }
    	}    	
    }
   
    return $product;
}`

**Comment by ljutaev** [comment]
`
 

    add_filter('wooms_product_save', 'gc_product_save', 30, 3);

    function gc_product_save( $product, $value, $data ) {

	$result = null;
	$ancestors = [];

	$product_id = $product->get_id();
	$terms = get_the_terms( $product_id, 'product_cat' );

	// by default wooms set 1 cat
    if( count( $terms ) == 1 ) {
    	if( $terms[0]->parent != 0 ) {
    		$cat_id = $terms[0]->term_id;
    		$ancestors = get_ancestors( $cat_id, 'product_cat' );
            $ancestors[] = $cat_id;

            $result = $product->set_category_ids( $ancestors );

            if( ! is_null( $result ) || ! is_wp_error( $result ) ) {
				do_action('wooms_logger',
			        'gc',
			        sprintf(
			            'Проставлены категории: (%s), для продукта %s (%s).',
						implode(",", $ancestors),
						$product->get_name(),
						$product->get_id()
			        )
			    );
		    }
    	}    	
    }   
    return $product;
    }
`
Работает только при второй синхронизации, ине для всех товаров ((

**Comment by uptimizt** [comment]
добавил в план работ. посмотрим. скорее всего не очень сложно сделать это как опцию.

**Comment by Juicew** [comment]
> добавил в план работ. посмотрим. скорее всего не очень сложно сделать это как опцию.

подскажите, а когда я получу плагин. я его оплатил 28 числа на вашу карту ВТБ. а от вас ни ответа ни привета.

**Comment by ljutaev** [comment]
> добавил в план работ. посмотрим. скорее всего не очень сложно сделать это как опцию.

Cпасибо )

**Comment by evgrezanov** [comment]
@uptimizt Если у товара выбрано 2 категории без потомков 
![image](https://user-images.githubusercontent.com/5329288/128154790-1f17aaca-3623-4d4e-ba14-2086a8980435.png)
тогда 2 дерева выберется? какое поведение будет?
