### ISSUE TITLE
Оплатили заказ на WOOMS XT, но плагин так и не предоставили.

### ISSUE THREAD

**Issue by Juicew** [wpcraft-ru/wooms#283]
Уважаемый разработчик данного плагина. С 27 апреля вы активно отвечали на мои вопросы с почты hd@wpcraft.ru на почту с neon0344@gmail.com.
![03-05-2020 12-58-24](https://user-images.githubusercontent.com/64439588/80911280-02a3cf00-8d3e-11ea-9d19-99a440108550.jpg)
![03-05-2020 12-58-41](https://user-images.githubusercontent.com/64439588/80911287-0afc0a00-8d3e-11ea-9dc5-3e706fc6c0bf.jpg)
![unnamed](https://user-images.githubusercontent.com/64439588/80911291-151e0880-8d3e-11ea-918f-7fa20321f123.jpg)
На протяжении недели мы ждём от вас плагин. У нас горит проект. ВЫ игнорируете сообщения, написанные Вам на почту как личную так и рабочую. Мы так же написали Вам на данный сервис GITHUB, но вы игнорируете наши сообщения, отвечая на сообщения других пользователей по техническим ошибкам плагина. Просим ответить нам !
Мы с радостью удалим сообщения на гитхабе, если мы урегулируем данный вопрос.

Просим с пониманием отнестись к данному обращению, ведь плагин стоит не 10$

**Comment by Juicew** [comment]
Спасибо. Вопрос урегулирован. Плагин предоставили.

**Comment by uptimizt** [comment]
@Juicew извините. я бывает выпадаю. не получается заниматься этим делом на фултайме.
