### ISSUE TITLE
Опция "Отправлять выбранный склад в Заказе" - улучшить инструкцию

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#284]
Опция нужна была Клиентам, у которых 3 склада, и на сайт поступали товары только по 1 складу. В момент передачи Заказа из Сайта в МойСклад по умолчанию должен был подставляться именно тот склад, остатки по которому поступали на Сайт.

Чтобы было меньше ручной работы и путаницы со складами в МойСклад.

мб улучшить инструкцию в плагине?

**Comment by Juicew** [comment]
Пользуемся данной опцией. Удобно когда в моем складе несколько складов. При поступающем заказе с сайта, автоматически в заказе в моем складе прописывается нужны склад
