### ISSUE TITLE
Разницы во времени создания заказа при синхронизации магазина и моего склада

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#285]
HD::998-952075
HD::146-862406

- [x] решение

- [x] добавить в чейнджлог

**Comment by uptimizt** [comment]
сделал проверку на локалке. 
время ок.
отправил дозапрос клиенту. ждем инфу.

**Comment by Juicew** [comment]
Только сегодня пофиксили такую же проблему. Просто в админке водпресса в настройках изменили часовой пояс. По стандарту там стоит +0

**Comment by uptimizt** [comment]
беда была в том что плагин отправлял время в лоб. то что в заказе то и в Склад.
а МойСклад хочет в часовом поясе Москвы.

для Москвы и маленьких магазинов это не критично.

а тут клиент из другого часового пояса плюс много оборотов.
в итоге началась беда с остатками.
