### ISSUE TITLE
Скрытие товаров в черновики

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#287]
бывает проблема когда нужно скрывать товары в черновики.

**Comment by uptimizt** [comment]
хук wooms_hide_old_product
можно использовать для скрытия товаров в черновики

**Comment by uptimizt** [comment]
```
add_action('wooms_hide_old_product', function($products){
    foreach($products as $product){
        $product->set_status('draft'); 
        $product->save(); 
    }
});
```

**Comment by Alexivakha** [comment]
Как можно скрыть товары (простые и вариативные) если их нет в наличии ? 
Можно ли как-то по статусу отправлять в черновик ?

С ув. Александр

**Comment by uptimizt** [comment]
@Alexivakha 
добавил хук 
`$product = apply_filters('wooms_stock_product_save', $product, $row);`

теперь можно делать так:
```
add_filter('wooms_stock_product_save', function($product){

    if($product->get_stock_quantity() <= 0){
        $product->set_status('draft');
    }
});
```

**Comment by Alexivakha** [comment]
Отлично, попробую

Можно сделать идентификацию клиента в МС не по почте, а по номеру телефона?


сб, 13 июня 2020 г. в 2:52 PM, Anatoly Yumashev <notifications@github.com>:
