### ISSUE TITLE
Нужно для указаных атрибутов проставлять не использовоть для вариаций при интеграции

### ISSUE THREAD

**Issue by ljutaev** [wpcraft-ru/wooms#288]
Нужно для указаных атрибутов проставлять не использовaть для вариаций при интеграции. Тоесть у меня в МС есть модификация например bind-model, мне нужно при интеграции перехватить создание атрибута и установить для него не испольвать для вариаций. Спасибо

![image](https://user-images.githubusercontent.com/6756977/81700367-3b942000-9471-11ea-9929-25eac7dee716.png)

так понимаю это тут происходит в методе save_other_attributes() класса ProductAttributes: 
![image](https://user-images.githubusercontent.com/6756977/81700487-5ebecf80-9471-11ea-97e0-f88ed5d6653c.png)

**Comment by uptimizt** [comment]
@ljutaev в МойСклад есть доп поля.

Если товару добавить доп поля, то они передадуться как атрибуты без вариации
