### ISSUE TITLE
Когда ожыдать 7.2 с сихронизацией изображений вариаций ?

### ISSUE THREAD

**Issue by ljutaev** [wpcraft-ru/wooms#293]
Когда ожыдать 7.2 с сихронизацией изображений вариаций ? 
Горит, нужно дать ответ клиенту. Ответься быстрее

**Comment by uptimizt** [comment]
Должен был быть позавчера. Но что то пошло не так. Пока что валятся ошибки. Решаем. 
@ljutaev
