### ISSUE TITLE
Добавить опцию для ускорения синхронизации

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#295]
Иногда бывает нужно ускорять обмен данными. На крупных магазинах. Добавил опцию.

Но нужно быть осторожней. Слишком большой размер пачки может приводить к перегрузкам сервера и ошибкам.

# Решение

![image](https://user-images.githubusercontent.com/1852897/84777866-d0e38080-afea-11ea-8fe3-e3c3a2e1153d.png)

**Comment by FiruzHamidov** [comment]
Слишком большой это сколько, Чтобы мы могли ориентироваться
