### ISSUE TITLE
Метабоксы с данными о интеграции Продукта, Категории и Заказа

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#31]
для всех 3-х сущностей мы вроде бы сохраняем ссылку на МойСклад и wooms_id.
надо добавить метабокс, назвать его МойСлад и вывести туда id + ссылку на сущность в МойСклад.

это важно для тех поддержки и решения проблем. и для пользователя. чтобы он мог из Заказа, Продукта или Категории попасть на аналогичную сущность сразу в МойСклад.

**Comment by artikus11** [comment]
Принято. Это для всех сущностей делать? Заказа, Продукт? А с вариациями как быть?

**Comment by uptimizt** [comment]
> А с вариациями как быть?

не припомню чтобы у вариации была ссылка. думаю надо только там где есть возможность открыть сущность по ссылке. а их всего 3.

**Comment by artikus11** [comment]
Ссылка там есть, но она не сохраняется в мету, только woom_id туда пишем. Ок, нет так нет

**Comment by uptimizt** [comment]
![image](https://user-images.githubusercontent.com/1852897/45600001-60b35f80-b9fe-11e8-9800-05e8eee4aed4.png)

**Comment by uptimizt** [comment]
@artikus11 обрати внимание что uuid и ид у ссылки - это разные ид. надо как то вытаскивать ссылку. иначе не работает.

**Comment by artikus11** [comment]
@uptimizt хм, ок, проверю

**Comment by uptimizt** [comment]
@artikus11 как минимум это по товарам. по другим сущностям не проверял. проверь плиз.

**Comment by artikus11** [comment]
@uptimizt Без проблем, проверю

**Comment by uptimizt** [comment]
тест ок
