### ISSUE TITLE
Документация и инструкции по плагину

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#325]
сделать инструкцию.

разместить ссылку в консоли плагина. чтобы Клиенты могли быстро перейти и почитать.

- [x] прописать инструкцию https://github.com/wpcraft-ru/wooms/wiki/GettingStarted

- [x] добавить ссылку на инструкцию в плагин, так чтобы она была видна тем кто только начинает работу

- [x] также добавить ссылку в readme.txt чтобы на оф странице плагина в каталоге вп орг можно было быстро найти и почитать

**Comment by uptimizt** [comment]
![image](https://user-images.githubusercontent.com/1852897/90985151-b7c6f500-e582-11ea-8d8f-5aa7dcc6f2bb.png)

**Comment by evgrezanov** [comment]
![image](https://user-images.githubusercontent.com/5329288/91039300-87d92980-e636-11ea-9397-b05a99de3b2c.png)
![image](https://user-images.githubusercontent.com/5329288/91039383-ac350600-e636-11ea-9720-98b078fe9420.png)
