### ISSUE TITLE
Поднять перформанс плагина на нагруженных сайтах

### ISSUE THREAD

**Issue by mihdan** [wpcraft-ru/wooms#328]
Привет, у тебя судя по всему для некоторых `set_transients` не указано время жизни, из за этого при отключенном кеше в таблицу `wp_options` кладутся записи с `autoload=yes`, что не есть хорошо.

Например,

![](https://i.imgur.com/hfUeUR5.png)

**Comment by uptimizt** [comment]
@mihdan как это влияет на скорость?

тут от силы 2-3 кб данных. оно на скорость влияет ровно также как плевок в океан на его температуру.

плюс эти транзиты при каждом чихе чистятся.

**Comment by uptimizt** [comment]
плюс если сайт нагруженный и там внешний объектный кеш - то совсем никак не влияет.

**Comment by mihdan** [comment]
Речь про шареды, где олее 30мб на сайт не дадут и нет объектного кеша, а каждый килобайт в памяти - сам понимаешь, скалыдвается в мегабайты.

**Comment by uptimizt** [comment]
> Речь про шареды, где олее 30мб на сайт не дадут и нет объектного кеша, а каждый килобайт в памяти - сам понимаешь, скалыдвается в мегабайты.

@mihdan я понимаю о чем ты.

когда таблица опций растет до 10 мб потому что там хранят что попало. типа историю отправленных email. или какие то большие списки.

тут нет и не будет 10 мб. и даже 1 мб не будет. это просто служебные данные. которые по хорошему надо хранить в транзитах. 

но так как бывают проблемы с транзитами из за кривого редиса, то скоро перепишу на опции. а там и автолоад убрать можно будет. 

в любом случае задача будет решена, но по другим причинам )

**Comment by uptimizt** [comment]
задача тут https://github.com/wpcraft-ru/wooms/issues/320
