### ISSUE TITLE
Фикс проблемы поиска по номерам заказа

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#331]
https://github.com/pablo-sg-pacheco/wc-booster-search-order-by-custom-number-fix/blob/master/Order.php

- [ ] протестить

- [ ] дописать чейнджлог

**Comment by evgrezanov** [comment]
@uptimizt здесь вроде все понятно - допилить чтобы работал поиск по номеру заказа (по ссылке пример)
единственное что странно - стандартно работает все
![image](https://user-images.githubusercontent.com/5329288/89622232-f0957780-d8bc-11ea-97cf-6941297f95a4.png)
разберемся

**Comment by evgrezanov** [comment]
@uptimizt сделал PR в master
