### ISSUE TITLE
Ошибка обновления кастомных статусов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#332]
Кастомные статусы не учитываются в коде

**Comment by uptimizt** [comment]
Ошибка:
если обновить статус на Доставлен в МойСклад, то на сайте образуется какая то очередь не верных обновлений

**Comment by evgrezanov** [comment]
![image](https://user-images.githubusercontent.com/5329288/89492863-db491c00-d7dc-11ea-8609-84d7d75148ef.png)
импортировал несколько заказов после смены статуса в МС - проблема пока не повторилась,  или я не туда смотрю?
