### ISSUE TITLE
Сбрасывается заказ в "Мой склад"

### ISSUE THREAD

**Issue by Juicew** [wpcraft-ru/wooms#333]
Доброго времени суток. Два дня назад столкнулись с проблемкой.
Приходит заказ с сайта в "мой склад" во вкладку "заказы покупателей".
Далее покупатель просит добавить товар к его заказу, мы открываем заказ в "заказы покупателей" и докидываем товар. Сохраняем и меняем статус. Ранее всё было четко.
Сейчас после добавления товара в заказ покупателя, спустя пару секунд. карточка товара обновляется, согласно точному заказу на сайте. 
Подскажите, ввиду чего может автоматически сбрасываться отредактированный заказ в моем складе, раньше не сбрасывался.

update: первый раз редактируешь заказ на складе - сбрасывается до заказа, который пришёл с сайта
              второй раз редактируешь тот же заказ - всё сохраняется и не обнуляется

**Comment by uptimizt** [comment]
@Juicew взял в работу.

Как обходное решение - править состав продуктов на сайте. И оно автоматом обновит заказ в МойСклад.

Попробую эту логику откатить к старому сценарию как быстрое решение.

В будущем надо будет делать 2х сторонний синк заказа. Это более сложное и потому более долгое решение.

**Comment by uptimizt** [comment]
сначала надо сделать вот это https://github.com/wpcraft-ru/wooms/issues/335
