### ISSUE TITLE
Исключение единичных товаров из синхронизации

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#334]
# checklist

- [x] получить про версию МС с полями
- [x] добавитье поле исключения типа флаг в МС - указать название поля например "Исключить" https://github.com/wpcraft-ru/wooms/issues/334#issuecomment-1072694289
- [ ] добавить такое поле к товарам в МС - типа чекбокс - с тем же названием
- [ ] указать у 1-2 товаров это поле - чтобы исключить
- [ ] удалить все товары и перезапустить синк
- [ ] проверить что этот товар не загрузился

```
есть беда с этой опцией - бывает глючит - надо хорошо перепроверить
```

# notes
Цитата от Клиента
> У меня есть группа товаров. Мне нужно синхронить все кроме 1 продукта. Это возможно вообще? Или обязательно этот продукт нужно вынести в другую группу?

ХД 568-527824

https://github.com/uptimizt/wooms-extra/pull/20

**Comment by uptimizt** [comment]
тип поля тут 
![2022-03-18-21-34-15-6bd1d](https://user-images.githubusercontent.com/1852897/159063207-c73bd579-bcf9-4c1a-a78b-2eda37c9e955.png)

**Comment by Aliya072** [comment]
1. https://online.moysklad.ru/app/#good/edit?id=6ac21533-9192-11e7-6b01-4b1d003be44e
2. https://online.moysklad.ru/app/#good/edit?id=27997e52-9193-11e7-6b01-4b1d003bf070
