### ISSUE TITLE
Некорректно передается заказ с сайта в мой склад

### ISSUE THREAD

**Issue by Juicew** [wpcraft-ru/wooms#343]
На сайте всё корректно отображается. При передачи заказа в мой склад. Передается только карточка клиента, а суммы заказа, наименование товара, зарезервировано - не отображается. Поля по нулям

**Comment by Juicew** [comment]
`
![12-08-2020 11-29-18](https://user-images.githubusercontent.com/64439588/89993549-8bac9980-dc8f-11ea-9ac6-54756b86f5fb.jpg)
![12-08-2020 11-29-38](https://user-images.githubusercontent.com/64439588/89993554-8cddc680-dc8f-11ea-9595-f24f59390093.jpg)

`

**Comment by uptimizt** [comment]
@evgrezanov сможешь повторить проблему на демо стенде?

**Comment by evgrezanov** [comment]
> @evgrezanov сможешь повторить проблему на демо стенде?
> 
> 

Это по тому же магазу который Xiaomi? Или это другая таска? Повторить на нашем демо стенде нужно?

**Comment by uptimizt** [comment]
> Это по тому же магазу который Xiaomi? Или это другая таска? Повторить на нашем демо стенде нужно?

да, на нашем демо. это не про xiaomi. @evgrezanov  

@Juicew есть возможность проверить на 7.11? сегодня релиз сделал. там эта механика улучшена.

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by Juicew** [comment]
Да. Сегрдня в течени часа опробую и отпишу

**Comment by evgrezanov** [comment]
@uptimizt @Juicew проверил на демо-стенде, на версии 7.12
![image](https://user-images.githubusercontent.com/5329288/91032773-a63a2780-e62c-11ea-98e0-9c86540da57b.png)
![image](https://user-images.githubusercontent.com/5329288/91032876-c4a02300-e62c-11ea-8f79-a6db71b09b91.png)

**Comment by Juicew** [comment]
Да. Вчера пришел заказ и снова в мой склад передалась некорректно информация о заказе

**Comment by evgrezanov** [comment]
@Juicew уточните заказ создается стандартным способом ?

**Comment by Juicew** [comment]
Да. Делается заказ стандартным способом. Добавляем товар в корзину, переходим в корзину, добавляем нужное количество, далее переходи в оформление, заполняем поля. Указываем самомвывоз или доставка и оформляем заказ.

**Comment by uptimizt** [comment]
@Juicew можете отправить доступы в поддержку? hd@wpcraft.ru

или уточнить номер тикета или email если ранее отправляли.

**Comment by Juicew** [comment]
отправил

**Comment by Juicew** [comment]
Беда осталась. В общем передаётся заказ в Мой склад - всё четко. Далее клиент просит добавить в его заказ еще одну позицию + проставляем в его заказе скидки. Сохраняем заказ и закрываем. Проходит пару минут и заказ в Моём Складе сбрасывается на дефолтный, который пришёл с сайта, без скидки и добавленной позиции.

Помогите решить проблему.
![28-09-2020 23-00-01](https://user-images.githubusercontent.com/64439588/94480077-6db6dc00-01de-11eb-8257-1d00619d7040.jpg)

**Comment by uptimizt** [comment]
@Juicew в версии от декабря-ноября вроде бы это порешали.

подтвердите?

**Comment by missha2022** [comment]
Точно такая же ситуация. На сайте всё корректно отображается. При передачи заказа в мой склад. Передается только карточка клиента, а суммы заказа, наименование товара, зарезервировано - не отображается. Поля по нулям

**Comment by uptimizt** [comment]
в 9.1 вроде бы починил https://github.com/wpcraft-ru/wooms/releases/tag/9.1

проверьте
