### ISSUE TITLE
Полное и краткое описание товара

### ISSUE THREAD

**Issue by SliceofHuman** [wpcraft-ru/wooms#347]
На сайте использую полное и краткое описание товара. По умолчанию поле "Описание" из МС выводится в полном описании товара. Пытаюсь понять, каким образом можно выводить excerpt в товарах из МС. Пробовал через доп. поля, но там начинаются танцы с бубном вокруг удаления атрибутов.

Есть простой способ решения данной проблемы?

**Comment by SliceofHuman** [comment]
> > Создал доп поле "Краткое описание".
> 
> @SliceofHuman
> 
> я верно понял что сценарий должен быть таков:
> 
> 1. описание товара - загружать как полное описание
> 2. из доп поля "Краткое описание" - загружать текст в поле excerpt на стороне сайта?

Именно так.
Подскажите, как это можно реализовать?

**Comment by SliceofHuman** [comment]
> > Создал доп поле "Краткое описание".
> 
> @SliceofHuman
> 
> я верно понял что сценарий должен быть таков:
> 
> 1. описание товара - загружать как полное описание
> 2. из доп поля "Краткое описание" - загружать текст в поле excerpt на стороне сайта?

Когда можно ожидать функцию в релизе плагина?
Или есть костыль на время хотя бы?

**Comment by uptimizt** [comment]
> Или есть костыль на время хотя бы?

@SliceofHuman 

да, обходное решение это основной контент пилить на сайте.

так многие делают. кто то даже отключает синк описания и категорий и все это вручную пилят на сайте.

потому что сложно обеспечить качественное управление контентом на складе, так как это можно делать на сайте.

но задача в приоритете, мы ищем решение. собираем комменты от клиентов чтобы придумать что то работающее.

**Comment by uptimizt** [comment]
HD 553-456843

**Comment by uptimizt** [comment]
Сейчас в плагине реализованы 2 опции:
- по умолчанию - плагин берет описание МС и сохраняет его в полное описание продукта
- есть опция которая позволяет переключить эту логику так, чтобы описание из МС сохраняет в краткое описание продукта на сайте

Последняя опция нужна для тех магазинов, которые краткое описание ведут в МС, а полное на Сайте.

Если мы говорим о сценарии когда полное описание берем из описания МС, а краткое из доп поля, то думаю это надо попробовать описать как микро плагин

**Comment by uptimizt** [comment]
описал отдельно https://github.com/wpcraft-ru/wooms/issues/400
