### ISSUE TITLE
При включении опции синка по коду, ломаются категории продуктов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#349]
Нужно протестировать и если проблема повторится, то порешать.

# Проблематика
При синхронизации установили галочку "Использовать код как артикул" 
и у нас слетели все привязки к категориям товаров на сайте , т.е. товары стали вне категорий после синхронизации и пришлось их разносить заново.

**Comment by OlaIola** [comment]
Не удалось получить такого эффекта. 

- Категории, которые заведены исключительно на сайте удаляются у товара и остаются пустыми. После того, как категория синхронизировалась, изменение ее названия с одной или с другой стороны уже не синхронизируется. 
- При установленной галочке "Отключить синхронизацию категорий" добавленные товару (и услуге) на сайте дополнительные категории все-равно удаляются у товара.

**Comment by OlaIola** [comment]
![2021-05-05_20-04-30](https://user-images.githubusercontent.com/16874687/117182214-5d9b5680-add6-11eb-90ba-091f7b790691.png)
При отмеченной второй опции "Выбор всех категорий в дереве" несмотря на то, что Синхронизация категорий выключена, категории синхронизируются и пытается встать все дерево категорий и категории, установленные товару на сайте слетают. Может быть это тот случай.

**Comment by uptimizt** [comment]
В версии 9.0 принцип связи продуктов изменился и теперь скорее всего синк по коду не нужен.
Если окажется что это не так - открыть новый ишью.
