### ISSUE TITLE
Передача пункта самовывоза из Заказа в МойСклад

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#353]
![image](https://user-images.githubusercontent.com/1852897/92263274-078faf80-eee5-11ea-9639-256093d634e2.png)

**Comment by m-pravdin** [comment]
Кастомные поля в теме, плагин не использовался.

**Comment by uptimizt** [comment]
@m-pravdin нужен ключ метаполя.

по нему напишем сниппет и если ключ правильный, то все будет работать

**Comment by m-pravdin** [comment]
Вот видимо это поле - https://prnt.sc/ueh0qh

**Comment by uptimizt** [comment]
Код, который должен работать, но надо тестировать.

```
<?php
/**
 * Plugin Name: WooMS OrderPickupPoint
 * Plugin URI: https://github.com/wpcraft-ru/wooms/issues/353
 * Description: Передача пункта самовывоза из Заказа в МойСклад #353
 */

namespace WooMS;

class OrderPickupPoint
{
    public static function init()
    {
        add_filter('wooms_order_sender_notes', [__CLASS__, 'add_order_notes'], 10, 2);
    }

    /**
     * add_order_notes
     * 
     * @param \WC_Order $order
     */
    public static function add_order_notes($notes, $order)
    {
        if (!get_option('wooms_order_additional_notes_enable')) {
            return $notes;
        }

        $address = $order->get_address();
        if (empty($address['pickup_point'])) {
            return $notes;
        }

        $notes['pickup_point'] = $address['pickup_point'];

        return $notes;
    }
}

OrderPickupPoint::init();

```

Закинуть можно в плагины, в mu-plugins или в functions.php темы.

@m-pravdin

**Comment by m-pravdin** [comment]
Тот код выдавал ошибку.
Добавили этот


<?php
/**
 * Plugin Name: WooMS OrderPickupPoint
 * Plugin URI: https://github.com/wpcraft-ru/wooms/issues/353
 * Description: Передача пункта самовывоза из Заказа в МойСклад #353
 */

namespace WooMS;

class OrderPickupPoint
{
    public static function init()
    {
        add_filter('wooms_order_sender_notes', [__CLASS__, 'add_order_notes'], 10, 2);
    }

    /**
     * add_order_notes
     * 
     * @param \WC_Order $order
     */
    public static function add_order_notes($notes, $order)
    {
        if (!get_option('wooms_order_additional_notes_enable')) {
            return $notes;
        }

        if(is_int($order)){
            $order = wc_get_order($order);
        }

        $address = $order->get_address();
        if (empty($address['pickup_point'])) {
            return $notes;
        }

        $notes['pickup_point'] = $address['pickup_point'];

        return $notes;
    }
}

OrderPickupPoint::init();
