### ISSUE TITLE
Пропал метод доставки в комментах к заказу

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#357]
после обновления плагина перестал передаваться метод доставки в заказах

**Comment by l0stmagic** [comment]
+Приветствую. 
Не передает метод доставки в мой склад.
Смотрю версию 7.9 все передаётся
Как было в 7.9:
Посмотреть заказ на сайте: https://сайт.ru/wp-admin/post.php?post=2215&action=edit
---
Примечание Клиента к Заказу:
тест
---
Метод доставки: Служба СДЭК
---
Указаны дополнительные данные для доставки: 
Тесст Тестов, г Санкт-Петербург, пр-кт адрес, д1 к 1, Санкт-Петербург, Санкт-Петербург, 190000
---
Телефон: +79111001010

И как стало 7.12:
Посмотреть заказ на сайте: https://сайт.ru/wp-admin/post.php?post=6302&action=edit
---
Примечание Клиента к Заказу:
пр ТЕСт
---
Указаны дополнительные данные для доставки: 
Тесст Тестов, г Санкт-Петербург, пр-кт адрес, д1 к 1, Санкт-Петербург, Санкт-Петербург, 190000
---
Телефон: +79111001010
---
