### ISSUE TITLE
rest_route вызвана неправильно

### ISSUE THREAD

**Issue by luk911** [wpcraft-ru/wooms#358]
rest_route вызвана неправильно. В определении маршрута REST API для wooms/v1/order-update отсутствует обязательный аргумент permission_callback. Для общедоступных маршрутов REST API используйте __return_true для разрешения обратного вызова. Дополнительную информацию можно найти на странице «Отладка в WordPress». (Это сообщение было добавлено в версии 5.5.0.)

**Comment by uptimizt** [comment]
вижу проблему https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#permissions-callback

поправим в след версии
