### ISSUE TITLE
Загрузка изображения у модификаций Товара повторное

### ISSUE THREAD

**Issue by SneakyBaddger** [wpcraft-ru/wooms#359]
# checklist

- [ ] добавить вариацию с картинкой
- [ ] перезапустить синк
- [ ] проверить что картинка дошла до вариации

# desc

Я пользователь Wooms XT, крайне не хватает функционала
Загрузка изображения у модификаций Товара #116
(https://github.com/wpcraft-ru/wooms/issues/116)

Из ToDo было выброшено полтора года назад. В Api МС поддержка выгрузки массива изображений модификаций (до 10шт у модификации) появилась, насколько я могу судить

**Comment by uptimizt** [comment]
HD 519-332663

**Comment by uptimizt** [comment]
HD 220-799147

**Comment by evgrezanov** [comment]
@uptimizt здесь есть какие-то пояснения берем ее следующую?

**Comment by evgrezanov** [comment]
@uptimizt 
1. добавил модификацию товара с изображением здесь https://online.moysklad.ru/app/#good/edit?id=fe478018-70ce-11e8-9ff4-31500018ac08 при синхронизации миниатюра не передается
2. в woo для вариации можно установить только 1 миниатюру, так что можно реализовывать 1, 10 думаю лишнее, что скажешь?
3. МС API посмотрел возможность получения изображения вроде есть https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-izobrazhenie
![image](https://user-images.githubusercontent.com/5329288/112085243-bd3df980-8bbc-11eb-817f-ba591278437c.png)

**Comment by uptimizt** [comment]
@evgrezanov это ок.

мы тут ограничены со стороны Woo и потому плагин может работать только с учетом этих ограничений.

если этот функционал добавить на стороне Woo то с учетом этого и надо будет пилить доп плагин. Но это отдельный плагин, история и бюджет.

потому если все ок то двигай в тест

**Comment by evgrezanov** [comment]
@uptimizt что значит "все ок" ? Тут либо  дорабатывать выгрузку миниатюры в вариации (но это будет 1 картинка) либо просто идём дальше)

**Comment by uptimizt** [comment]
@evgrezanov все ок - значит код написан и картинка грузится.

**Comment by evgrezanov** [comment]
@uptimizt у вариации изображение передается, перепроверил сейчас
https://www.loom.com/share/0f990a733eb343b09fcb69b1517ff3e3
