### ISSUE TITLE
возникла потребность исключить из синхронизации некоторые из категорий и подкатегорий

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#36]
У моего клиента, использующего платную версию плагина WooMS XT, возникла потребность исключить из синхронизации некоторые из категорий и подкатегорий в МойСклад.

# Решение

Добавлен хук фильтр в цикл загрузки данных по ассортименту:
```
$i = 0;
foreach ( $data['rows'] as $key => $value ) {
  if( apply_filters('wooms_skip_product_import', false, $value) ){
    continue;
  }
  do_action( 'wooms_product_import_row', $value, $key, $data );
  $i ++;
}
```

Можно использовать так:
```
    add_filter('wooms_skip_product_import', function($skip, $value){
      $list_paths = array(
        'Колясочные запчасти/Колесные элементы/Покрышки для колясок',
      );

      $pathName = $value['pathName'];

      foreach ($list_paths as $path) {
        if(strpos($pathName, $path) !== false ){
          $skip = true;
        }
      }

      do_action( 'cl', array( 'что в $value?', $skip, $value ) );
      return $skip;
    }, 10, 2);
```

Делаем список путей, и если у товара есть совпадение по такому пути, то пропускается импорт.

**Comment by uptimizt** [comment]
@artikus11 есть идеи?

**Comment by artikus11** [comment]
Ход мыслей верный. Но могут возникнуть проблемы:

- при повторном синке, когда уже есть товары
- если много товаров, то может все обвалиться
- могут быть проблемы с вариативными товарами

Но попробовать можно.

Можно попробовать использовать функционал того как мы сделали синк по отдельной рубрике. То есть, использовать фильтры `wooms_product_ms_api_url` и `wooms_variant_ms_api_url`. Передавать в них нужные параметры и по ним сверять...
Хм, правда фильтра для параметром нет, мы его в релизе убрали. Думали, что не потребуется

Постараемся оперетивно что-то придумать. Спасибо за обратную связь

@uptimizt Это как раз тот случай про который я тебе говорил, и надо делать функционал исключения категорий

**Comment by ikalm** [comment]
Артем, спасибо за обратную связь!

Про фильтры wooms_product_ms_api_url и wooms_variant_ms_api_url еще почитаю дополнительно...

Понимаю, что правильнее всего было бы использовать возможность фильтрации получаемого набора товаров в запросах через API к МойСклад атрибут productFolder, но это потребовало бы написать несколько более серьезное расширение, а решение требовалось очень быстро, поэтому пока дописал и опробовал в эту пятницу плагин, принцип работы которого был описан выше в цитате из моего письма. 

Он добавил на страницу настроек еще один пункт «Не импортировать из» со списком категорий из МойСклад в виде чекбоксов. Помечаются ненужные каталоги и товары из них соответственно не импортируются в базу данных сайта.

При этом пришлось все же внести в базовый модуль WooMS уже упомянутую выше правку:

`$product_id = $this->add_product( $value );
if ($product_id)
  $this->update_product( $product_id, $value );
else
  return;`

Очень бы хотелось, чтобы разработчики базового плагина учли этот код в следующем релизе.

**Comment by artikus11** [comment]
@ikalm 
Хорошее решение, если все работает как надо.

Правка должна быть в методе load_data? Можете предложить пулреквест по изменению этого метода?

**Comment by ikalm** [comment]
Никогда не работал с ГитХабом, к сожалению, поэтому, чтобы не напортачить, опишу предложение здесь:

Предлагаю добавить проверку на наличие валидного возвращаемого значения _$product_id_ в файле **class-import-products.php**, функции **load_data(...)** (строка 49), которая бы предотвращала последующий безусловный пока вызов функции update_product(...), приводящий к ошибке в случае некорректного значения _$product_id_:

> Fatal error: Uncaught Error: Call to a member function get_title() on boolean in ...\wooms\inc\class-import-products.php on line 95

Подобное происходит, если функция add_product(...) того же класса возвращает FALSE. Такая возможность уже заложена в коде, а также возникает при использовании хука '**wooms_add_product**' для отфильтровывания товаров по какому-либо признаку, извлекаемому из _$data_source_.

В частности, я уже использовал этот хук для создания дополнительного плагина, позволяющего не импортировать товары из выбранных категорий в базе данных МойСклад.

Вышеупомянутый код из функции load_data(...)

`
$product_id = $this->add_product( $value );
$this->update_product( $product_id, $value );
`
заменил на

`
$product_id = $this->add_product( $value );
if ($product_id)
    $this->update_product( $product_id, $value );
else
    return;
`

**Comment by uptimizt** [comment]
@artikus11 @ikalm а вы заметили что вы оба с Саратова? ))

**Comment by ikalm** [comment]
Конечно, заметил - заглянул уже и в профиль Артема на GitHub, и на wpruse.ru, и даже в профиль в VK :)  Там, правда, написано Балаково - не совсем Саратов, но тоже Саратовская область :) Можно сказать, земляки, что безусловно приятно!

**Comment by artikus11** [comment]
@ikalm Дак для того и написано Саратов))) Балаково редко кто знает, а Саратов точно у всех на слуху)

Ок, изменения приняты. В следующем релизе добавим

**Comment by uptimizt** [comment]
@artikus11 добавил в работу. Думаю это не долго. В идеале сниппет тут же написать по использованию хука для пропуска группы

**Comment by artikus11** [comment]
@uptimizt Там даже сниппет не нужен, просто код изменить надо, чтобы хук работал. Ща исправлю

**Comment by artikus11** [comment]
@ikalm Подскажите, как при повторной синхронизации, когда уже есть товары, себя товары ведут?

**Comment by ikalm** [comment]
@artikus11 При повторной синхронизации ничего необычного пока не заметил: если у ранее импортированного товара из разрешенной категории поменять цену, привязку к каталогу на сайте и наличие, эти данные восстанавливаются при запуске повторного импорта.

**Comment by uptimizt** [comment]
@artikus11 

> Там даже сниппет не нужен, просто код изменить надо, чтобы хук работал. Ща исправлю

сниппет нужен не там, а тут :)

- как ты поймешь что решил задачу? если не проверишь?
- как потом без примера людям описать как можно использовать этот хук чтобы исключать категории?
- как я пойму что решение оптимально и его нельзя улучшить?

все эти вопросы без сниппета повиснут.

**Comment by artikus11** [comment]
@uptimizt Понял

**Comment by artikus11** [comment]
@uptimizt На этой неделе, я чей-то туплю, не могу пока его придумать, точнее логику разработать

**Comment by uptimizt** [comment]
@artikus11 инструмент сделал, а как им пользоваться не знаешь? ))

**Comment by artikus11** [comment]
@uptimizt говорю же, туплю) Ща пройдет тупизм и напишу.

**Comment by artikus11** [comment]
@uptimizt Посмотри сниппет https://gist.github.com/artikus11/034502c6f876bb7d1fd78ecb37615b2a

Тестировал, вроде работает как надо, но это работает только при первой синхронизации, если еще нет товаров. Если товары уже есть, то работать не будет

**Comment by uptimizt** [comment]
@artikus11 я думаю надо учитывать оба кейса.

вот добавились какие то товары.

потом добавили группу в исключения.

это значит что старые товары не должны обновиться, и потом по номеру старой сессии должны скрыться.

**Comment by uptimizt** [comment]
@artikus11 как тут дела?

**Comment by artikus11** [comment]
@uptimizt Не занимался, то что есть так и осталось. Второй вариант чтобы на существующих товарах работало не делал

**Comment by uptimizt** [comment]
добавил в шапку темы решение

**Comment by WEBzaytsev** [comment]
> @artikus11 я думаю надо учитывать оба кейса.
> 
> вот добавились какие то товары.
> 
> потом добавили группу в исключения.
> 
> это значит что старые товары не должны обновиться, и потом по номеру старой сессии должны скрыться.

Работает ли это при повторной синхронизации, если нет
На какую функцию это повесить?
