### ISSUE TITLE
Учитывать остатки по части складов

### ISSUE THREAD

**Issue by VladPodrechnev** [wpcraft-ru/wooms#362]
В настройках есть опция - учитывать остатки по складам. В ней есть возможность выбрать все склады или строго 1 из списка.

Опция не подходит, тк содержит лишние склады:
![image](https://user-images.githubusercontent.com/48187095/94362928-1b36cc00-00c7-11eb-9f4d-569340f16742.png)

Этот (и еще несколько) нужно учитывать:
![image](https://user-images.githubusercontent.com/48187095/94362971-84b6da80-00c7-11eb-8dca-7dca6f24ab51.png)

Этот (и еще несколько) нужно исключить из учета:
![image](https://user-images.githubusercontent.com/48187095/94362986-9bf5c800-00c7-11eb-8851-6907523cee84.png)

Как можно синхронизировать остатки по нескольким складам из списка (но не по всем)?

Было бы здорово изменить выбор 1го значения на возможность выбора нескольких складов.

Задача срочная, блокирует нас от запуска проекта.

Заранее спасибо!

**Comment by ProstoSvet** [comment]
Добрый день!

Подскажите, в какие сроки удастся реализовать доработку?

**Comment by uptimizt** [comment]
153-769369

**Comment by uptimizt** [comment]
@ProstoSvet вроде бы не сложно.

добавили в приоритет.

постараемся в течении 1-2 недель добавить.

**Comment by uptimizt** [comment]
Простейший вариант установки:
1. создаем файлик типа wp-content/mu-plugins/StockFilterByStores.php
2. кидаем туда код и меняем список складов в 1 переменной класса
3. оно будет сразу работать

либо можно создать файлик в папке wp-content/plugins/StockFilterByStores.php - в этом случае плагин можно включать и отключать

Код

```
<?php
/*
Plugin Name: WooMS Stock Multi Store
Plugin URI: https://github.com/wpcraft-ru/wooms/issues/362
Description: Обеспечивает синк по множеству складов. Список складов правится в коде. 
Version: 1
Author: wpcraft.ru
Author URI: https://wpcraft.ru
*/

/**
 * Filter by some stores
 */
class StockFilterByStores
{

    /**
     * 1. тут пишем список складов через запятую
     * 2. опцию в настройках сайта - отключаем
     */
    public static $include_stores = "Основной склад, Розничный склад";

    public static function init()
    {

        // tests
        // add_action('init', function () {
        //     if (!isset($_GET['dd'])) {
        //         return;
        //     }

        //     echo '<pre>';

        //     $check = self::filters_by_store([]);

        //     var_dump($check);

        //     die(0);
        // });


        add_filter('wooms_assortment_sync_filters', [__CLASS__, 'filters_by_store']);
    }

    /**
     * use $filters = apply_filters('wooms_assortment_sync_filters', $filters);
     */
    public static function filters_by_store($filters)
    {
        if($additional_store_hrefs = self::get_additional_stores()){
            foreach($additional_store_hrefs as $store_href){
                $filters[] = 'stockStore=' . $store_href;
            }
        }

        return $filters;
    }

    public static function get_additional_stores()
    {

        if(!$stores_api = get_transient('wooms_stores')){
            $stores_api = wooms_request('https://online.moysklad.ru/api/remap/1.2/entity/store/');

            set_transient('wooms_stores', $stores_api, MINUTE_IN_SECONDS * 5);
        }

        $include_stores = array_map('trim', explode(",", self::$include_stores));

        if(empty($stores_api['rows'])){
            return false;
        }

        $stores_href_list = [];
        foreach($stores_api['rows'] as $row){
            if(in_array($row['name'], $include_stores)){
                $stores_href_list[] = $row['meta']['href'];
            }
        }

        if(empty($stores_href_list)){
            return false;
        }

        return $stores_href_list;

    }
}

StockFilterByStores::init();

```

**Comment by uptimizt** [comment]
@VladPodrechnev @ProstoSvet попробуете?

**Comment by uptimizt** [comment]
Переписать опцию выбора складов с поддержкой множества складов

- поменять опцию
- сделать миграцию старой опции на новую
- переписать инструкцию https://github.com/wpcraft-ru/wooms/wiki/StockMultiStore
