### ISSUE TITLE
часть глобальных атрибутов, которые создавали в самом Woocommerce — исчезло

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#364]
Здравствуйте! Обнаружили, что часть глобальных атрибутов, которые создавали в самом Woocommerce — исчезло. Это могло быть связано с тем, что в Мой склад их не было и при обновлении затерло?

Если да, как получить возможность создавать новые атрибуты, без создания в Мой склад?

422-616323

**Comment by OlaIola** [comment]
Не удалось получить аналогичный результат, ни с глобальными, ни с индивидуальными атрибутами созданными на сайте и отсутствующими в МойСклад, ни у товаров, ни у услуг. 

Есть какая-то дополнительная информация?

**Comment by uptimizt** [comment]
видимо устарело - закрываем
