### ISSUE TITLE
Ошибка загрузки вариативных товаров

### ISSUE THREAD

**Issue by yurovigorr** [wpcraft-ru/wooms#379]
При загрузке вариативных товаров из МойСклад на сайт, они попадают в папку «Уникальное», хотя каждый из товаров имеет свою четкую категорию. Почему это происходит?
Приходится вручную перетаскивать товары в другие категории. 

HD 507-878066

**Comment by uptimizt** [comment]
@yurovigorr опция пропуска синка категории включена или отключена?

если отключена, то нечто идет не так. 

лучше отправить доступ к консоли сайта и фтп на m@wpcraft.ru - надо разбираться в конфигурации сайта.

на тест сайте с этим все ок

**Comment by yurovigorr** [comment]
Опция «Отключить синхронизацию категорий» стоит без галочки, т е выключена. 
Предоставить доступ к админке сайта?

Regrads,
Yurov I.I.

Saturday, 2 January 2021, 20:21 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by uptimizt** [comment]
@yurovigorr 

вопрос в том пчм вы думаете что вариативные товары должны грузиться в какую то категорию?

в базовой логике - у вариативных товаров нет категорий. они привязаны к категориям основного товара - а он вроде бы простой.

типа есть Футболка АБВ. и она в категории Футболки. но есть вариации - размер, цвет и т д. 

Вот все вариации в базе живут без категорий, так как привязка идет к основному продукту - и у него есть категория.

Как так получается что у вас вариация должна иметь категории? Это не базовая логика. И надо понимать как она нарушилась.

**Comment by yurovigorr** [comment]
Я абсолютно вас понимаю, сами вариации не должны выгружаться так же, как сами товары. Происходит другое. Товары, которые заведены как вариативные, выгружаются в категорию «остальное» (или типо того, как я писал выше), а обычные товары выгружаются в ту категорию, в которую необходимо. 

Regrads,
Yurov I.I.

Friday, 5 March 2021, 21:36 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by yurovigorr** [comment]
По какой-то неизвестной причине товар «Свеча катанная «Путь Старухи»» не выгружается из МойСклад на сайт. Не известно сколько ещё товаров так не выгружается. 

Regrads,
Yurov I.I.

Friday, 5 March 2021, 21:50 +0300 from Igor Yurov  <yurov.igorr@mail.ru>:

**Comment by uptimizt** [comment]
@yurovigorr можете отправить сюда список активных плагинов? это можно взять в разделе Здоровье сайта

**Comment by yurovigorr** [comment]
Я ведь вам давал доступ к админке.

Regrads,
Yurov I.I.

Sunday, 14 March 2021, 18:34 +0300 from ***@***.***  ***@***.***>:
***@***.*** можете отправить сюда список активных плагинов? это можно взять в разделе Здоровье сайта

**Comment by uptimizt** [comment]
в последних версиях этот сценарий тестировали - пока все ок
