### ISSUE TITLE
Не передаются Заказы без email

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#39]
Время от времени попадаются проблемы когда заказы не создаются.

Оказывается что некоторые магазины отключают поле email.

Надо придумать опцию, которая будет генерить email из телефона.

Например телефон 8 111 111 22 33, генерится email no-reply+71111112233@sitename.com
Либо отключить у таких Заказов проверку на дубль клиента. Опять же как опция.

**Comment by artikus11** [comment]
@uptimizt Это про этот тикет речь во флипе было?

**Comment by artikus11** [comment]
@uptimizt Посмотрел и проверил. У нас там стоит защита, если емайла нет, то берется адрес их общих настроек сайта почта админа.
![image](https://user-images.githubusercontent.com/16116688/44815359-5d436a00-abf0-11e8-8b9e-29f318b819f7.png)

Заказы отправляются без проблем
Проблема точно в емайлах?

**Comment by artikus11** [comment]
@uptimizt Как сделать дубликат, если почты вообще нет? Если только по твоему примеру - формировать какую-то почту из телефона. А если телефона нет? Ну оставили только поле имени

Кстати, в новой Вуке есть одна особенность, поле страны невозможно просто так убрать, будет ошибку выбивать. Может на него завязать формирование почты?

**Comment by uptimizt** [comment]
> Если пустые и телефон, и емайл, то используется поле страны, так как это поле будет в любом случае

не будет. поле Страны удаляется чаще всего. Плюс у 99 ищ 100 клиентов оно будет одинаковым. Это будет создавать дубли.
Мы же можем вообще не передавать поле?
Давай вообще не будем передавать это поле. Попробуй сделать поиск дубля по User ID & Phone. 
А передавать только те поля что реально есть и нужны.

Думаю что эти поля нам нужны по факту только для проверки дубля. А передавать их - не обязательно.

@artikus11

**Comment by artikus11** [comment]
@uptimizt А его нельзя не передавать, надо проверить, но пустое поле ошибку вроде выдает при передаче заказа. Проверю

**Comment by uptimizt** [comment]
> А что делать если не будет телефона?
создавать нового клиента. мб дубль, но защиты тут быть не может уже.

**Comment by artikus11** [comment]
@uptimizt Вот как придумал
1. Если нет телефона, то передаем пустую строку
2. Если нет почты, то формируем виртуальный почтовый ящик из телефона.
3. Если пустые и почта и телефон, тогда создается виртуальный ящик вида `no-reply-unknown@site.ru`, но тогда все равно будет перезапись заказов на этот ящик

ПО другому уже не знаю что придумать

**Comment by uptimizt** [comment]
тест ок
