### ISSUE TITLE
Загружает на сайт архивные товары

### ISSUE THREAD

**Issue by SliceofHuman** [wpcraft-ru/wooms#390]
# checklist

- [x] сделать синк в базе
- [x] перевести 1 продукт в архив в МС
- [x] сделать синк
- [x] проверчить что продукт пропал с сайта

# nptes
Прошу добавить чекбокс в настройки "Загружать архивные товары" Да\Нет

**Comment by uptimizt** [comment]
@SliceofHuman 

что такое архивные товары? как это работает в МойСклад?

зачем их загружать на сайт?

**Comment by SliceofHuman** [comment]
> @SliceofHuman
> 
> что такое архивные товары? как это работает в МойСклад?
> 
> зачем их загружать на сайт?

В МС есть возможность закинуть старые товары в Архив.
Плагин на сайте настроен таким образом, что выводит весь каталог, наличие доступно сразу, то чего нет через предзаказ.
Но я отловил в каталоге сайта архивные товары, которые доступны по предзаказу.
Плагин их грузит на сайт, и не убирает после.

**Comment by uptimizt** [comment]
@evgrezanov перевел на тебя.

тут все просто - добавить пару строк кода в базовый плагин где идет загрузка и если есть признак архивного товара то пропускать его обработку.

**Comment by evgrezanov** [comment]
![image](https://user-images.githubusercontent.com/5329288/113476694-2ec45480-94a7-11eb-9290-6ea45295cc67.png)
![image](https://user-images.githubusercontent.com/5329288/113476703-43a0e800-94a7-11eb-9544-b19c425b9afb.png)
![image](https://user-images.githubusercontent.com/5329288/113476719-60d5b680-94a7-11eb-8b56-01c0e74432b4.png)
@uptimizt @SliceofHuman Перепроверил, удалил все товары, затем в МС сделал несколько товаров архивными, сделал заново выгрузку - архивные товары не выгрузились, похоже они и так не выгружаются, я думаю проблема в другом, похоже что в следующий раз если я заархивирую товар в МС, то его статус не изменится в магазине, правильно понимаю проблему?

**Comment by SliceofHuman** [comment]
Именно так. 
Убивать каталог ради удаления архивных товаров каждый раз не хочется.
Хотелось бы автоматизировать этот процесс на стороне вашего плагина)

**Comment by SliceofHuman** [comment]
@uptimizt  Сценарий верный!

**Comment by evgrezanov** [comment]
> правильно



> Жень, ты сможешь проверить такой сценарий?
> 
> 1. выгрузить каталог как есть
> 2. затем сделать 1 товар архивным - проверить что он скрылся
> 3. затем товар сделать не архивным - проверить что он появился

Проверю

**Comment by evgrezanov** [comment]
@uptimizt @SliceofHuman прогнал проверку, 
![image](https://user-images.githubusercontent.com/5329288/113925371-26f11100-9815-11eb-8303-28ef4e2cdad6.png) - отправил в архим в МС
![image](https://user-images.githubusercontent.com/5329288/113925426-35d7c380-9815-11eb-8e58-255638f9e452.png) - товар скрылся в каталоге
![image](https://user-images.githubusercontent.com/5329288/113925545-57d14600-9815-11eb-9b96-ff91fa12b7cc.png) - вернул из архива в МС
товар появился
@SliceofHuman у вас эта опция галочка снята?
![image](https://user-images.githubusercontent.com/5329288/113927846-32920700-9818-11eb-97bf-78f10333f3b8.png)

![image](https://user-images.githubusercontent.com/5329288/113927702-04142c00-9818-11eb-958d-212e99fc045f.png)

**Comment by evgrezanov** [comment]
@SliceofHuman здесь ждем от вас ответа

**Comment by uptimizt** [comment]
@evgrezanov я верно понимаю что для решения задачи надо сделать доп поле в МС - типа архив? и только тогда мы можем что то делать со стороны сайта?

**Comment by evgrezanov** [comment]
@uptimizt См выше скрины, вроде там все работает

**Comment by uptimizt** [comment]
если я перевожу продукт в архив то на сайте он скроется? верно? @evgrezanov

**Comment by evgrezanov** [comment]
> @uptimizt @SliceofHuman прогнал проверку, 
> ![image](https://user-images.githubusercontent.com/5329288/113925371-26f11100-9815-11eb-8303-28ef4e2cdad6.png) - отправил в архим в МС
> ![image](https://user-images.githubusercontent.com/5329288/113925426-35d7c380-9815-11eb-8e58-255638f9e452.png) - товар скрылся в каталоге
> ![image](https://user-images.githubusercontent.com/5329288/113925545-57d14600-9815-11eb-9b96-ff91fa12b7cc.png) - вернул из архива в МС
> товар появился
> @SliceofHuman у вас эта опция галочка снята?
> ![image](https://user-images.githubusercontent.com/5329288/113927846-32920700-9818-11eb-97bf-78f10333f3b8.png)
> 
> ![image](https://user-images.githubusercontent.com/5329288/113927702-04142c00-9818-11eb-958d-212e99fc045f.png)
> 

@uptimizt пруфы

**Comment by Aliya072** [comment]
1. Сделала синк
2. Добавила в архив Диван Альфа
3. Сделала синк
4. Товар на сайте отсутствует
5. Извлекла товар из архива
6. Сделала синк
7. Товар появился на сайте

**Comment by Aliya072** [comment]
![121](https://user-images.githubusercontent.com/57318429/159060095-0d671271-4b64-4a87-b1f3-bf5b5808d82b.jpg)

**Comment by Aliya072** [comment]
![Uploading 122.jpg…]()

**Comment by Aliya072** [comment]
![122](https://user-images.githubusercontent.com/57318429/159060198-51e16678-a5d6-46c8-b9e0-5c531df77432.jpg)
