### ISSUE TITLE
Проверка совместимости с WooCommerce 5.0

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#396]
прогнать тесты

если все ок то поставить отметку о совместимости

- [x] ## Сброс
- [x] Деактивировать оба плагина
- [x] Удалить все данные через DevTools https://wooms.wpcraft.ru/wp-admin/admin.php?page=premmerce-dev-toolsclean_database
- [x] Тест базовой версии
- [x] Активируем базовую версию
- [x] Добиваемся синхронизации всего каталога продуктов
- [x] Проверяем наличие картинок
- [x] Тест расширенной версии
- [x] Активируем расширенную версию
- [x] Проверяем наличие вариаций
- [x] Проверяем работу заказов

**Comment by evgrezanov** [comment]
@uptimizt Обновил все, если есть какие-то пояснения как тестирование прогонять, могу прогнать и запушить

**Comment by uptimizt** [comment]
@evgrezanov https://github.com/wpcraft-ru/wooms/wiki/TestChecklist

**Comment by evgrezanov** [comment]
@uptimizt все проверил по инструкции - работает, единственное что смутило в woo нумерация заказов началась с 00001, но похоже так и должно быть

![image](https://user-images.githubusercontent.com/5329288/111098704-a113da00-8576-11eb-8a8d-8f1a12d005e4.png)

**Comment by uptimizt** [comment]
@evgrezanov так быть не должно.

Но что то могло поменяться. Может быть МС сменил нумерация на 5 знаком по умолчанию. Тогда да.

Обращений на эту тему не было. 


Но лучше перепроверить - сделать еще заказы и посмотреть как нумерация пойдет.

**Comment by evgrezanov** [comment]
![image](https://user-images.githubusercontent.com/5329288/111913858-4c0a2380-8aa2-11eb-9a0e-ac6839c9dc4a.png)
номера заказов теперь идут по порядку.. могла повлиять то что я в этом пункте почистил все Удалить все данные через DevTools https://wooms.wpcraft.ru/wp-admin/admin.php?page=premmerce-dev-toolsclean_database ? @uptimizt

**Comment by uptimizt** [comment]
@evgrezanov думаю это изменения на стороне МС.

потому все ок. двигаем эту задачу дальше
