### ISSUE TITLE
Заказы под последнего контрагента загоняет, если делать заказы из админки или юзер гость

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#40]
Похоже проблема всплыла когда email пуст, то идет подстановка админского email и в заказе он подставляет одного и тогоже пользователя админа.

# ХД 
931

**Comment by artikus11** [comment]
@uptimizt Переделал как ты говорил в тикете #39 

Но это логично, если нет поля емайла, то да, сейчас будут поставлять админа, а потом перезаписывать на него заказы. 

Сейчас сделаю пуш

**Comment by artikus11** [comment]
Изменена провека пустого поля емайла при отправке закзов в МС. 

Тикеты
* https://github.com/uptimizt/wooms/issues/39
* https://github.com/uptimizt/wooms/issues/40

Если поле емайла пустое, то формируется демо адрес через номер телефона

Если пустые и телефон, и емайл, то используется поле страны, так как это поле будет в любом случае

@uptimizt проверь пулреквест на гитлабе

**Comment by uptimizt** [comment]
тест ок
