### ISSUE TITLE
Глючит датапикер у выбора даты отправки Заказов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#41]
<img width="346" alt="veio3-2018-09-05-09-48-05" src="https://user-images.githubusercontent.com/1852897/45075768-e1b25300-b0f0-11e8-97db-5db53691dc61.png">

надо поменять вот на этот https://github.com/t1m0n/air-datepicker

**Comment by artikus11** [comment]
@uptimizt  Хм. А надо ли? Это придется дополнительно подключать стили и скрипты. Надо разобраться почему стили не принимаются на датапикере.

Поправил, теперь работает. Там зачем-то http стояло
![image](https://user-images.githubusercontent.com/16116688/45085033-c0615f00-b110-11e8-9edd-7a99e0fab236.png)
