### ISSUE TITLE
При рекурсивном создании категорий, проверять основную папку без учета протокола

### ISSUE THREAD

**Issue by OlaIola** [wpcraft-ru/wooms#411]
Так как раньше был протокол 1.1, а сейчас 1.2, а в woomss_include_categories_sync сохраняется полный путь, то условие 
$url == get_option('woomss_include_categories_sync')
см: https://github.com/wpcraft-ru/wooms/blob/master/inc/ProductsCategories.php#L157 не будет выполнено. 
Жалоб на возможную проблему на данный момент нет.

**Comment by uptimizt** [comment]
решено в 9х ветке
