### ISSUE TITLE
Синхронизация вариаций с учетом уже имеющихся на сайте

### ISSUE THREAD

**Issue by OlaIola** [wpcraft-ru/wooms#412]
Результаты тестирования:
- если глобальный атрибут уже есть, то атрибут (характеристика) встает как глобальный, в противном случае как индивидуальный, соответственно, даже Дополнительные поля не добавляются как глобальные атрибуты.
- Если атрибут установлен как глобальный, то вариация с ним не встает, получается "Любой атрибут" вне зависимости было ли заведено такое значение или нет
Соответственно сейчас глобальные атрибуты и характеристики модификаций в МойСклад не могут совпадать.
- Если slug атрибута совпадает, то созданные в админке атрибуты товара будут перезаписаны. 
- Удаленная в МойСклад вариация не удаляется с сайта
- Если добавить вручную модификацию с индивидуальным атрибутом на сайт и точно такой же атрибут добавить модификации на складе, то со склада выгружается новая модификация, и связь с уже имеющейся не происходит.

Плюс:
+ проверить синхронизируются ли вообще вариации отдельно.

**Comment by uptimizt** [comment]
теоретически это возможно было бы если бы были артикулы у модификаций со стороны МойСклад.
при совпадении артикула - легко связать сущности.
однако в МойСклад этого нет.
можно писать какую то опцию типа связывать вариации по коду - но это редкий кейс.
в базовую версию не пойдет.
можно дописать микро плагин который это будет делать под заказ.
