### ISSUE TITLE
Если заказ удален в МойСклад, то на сайте идут запросы на обновление

### ISSUE THREAD

**Issue by eduardgermoniy** [wpcraft-ru/wooms#415]
Здравствуйте!
Заметил такую проблему.

Если удалить заказ из МойСклад, то сайт продолжает попытки обновить его статус
![image](https://user-images.githubusercontent.com/31701982/117142045-f078c880-adb7-11eb-8623-1ff01e9d3231.png)

**Comment by eduardgermoniy** [comment]
Спасибо за быстрый ответ!

**Comment by uptimizt** [comment]
в версии 9.0 сделали 1 попытку на отправку - должно сработать
