### ISSUE TITLE
Опция выбора атрибутов, которые должны сохраняться как общие

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#44]
Сейчас все модификации из Склада сохраняются как вариации на Сайте с индивидуальными атрибутами (метаполя). 

В некоторых случаях нужно сохранение как общие атрибуты (таксономии), чтобы иметь возможность делать фильтры.

Нужно придумать какую-то опцию, которая позволит указать какие атрибуты сохранять как общие.

ХД 688 

# Решение
- нужно создать общие атрибуты в консоли сайта с тем же названием что на Складе
- далее плагин при обмене данными будет провероять наличие атрибута по Имени
- если общий атрибут есть - будет использоваться он
- если общего атрибута нет - будет как раньше использоваться Индивидуальный на уровне Продукта

**Comment by artikus11** [comment]
@uptimizt Одной опцией не обойтись. Тут придется целую систему делать - создавать таксономии, потом их использовать как вариации. Надо посмотреть как это в Woo реализовано. Пока как-то сложно представить мне такое

**Comment by artikus11** [comment]
@uptimizt Чтобы сделать такую опцию, но внедрять новые настройки, там подключены select2 из Вукомерса им очень удобно множественный выбор делать и места немного занимает

**Comment by uptimizt** [comment]
> Одной опцией не обойтись. Тут придется целую систему делать - создавать таксономии, потом их использовать как вариации. Надо посмотреть как это в Woo реализовано. Пока как-то сложно представить мне такое

в момент создания атрибута достаточно там один флаг добавить, и таксономии и т д в теории должны сами создаться. но эт не точно

**Comment by uptimizt** [comment]
> Чтобы сделать такую опцию, но внедрять новые настройки, там подключены select2 из Вукомерса им очень удобно множественный выбор делать и места немного занимает

в идеале так:
1. на Складе прописывается руками название атрибутов - это так уже работает
2. на Сайте сделать опцию, где через запятую указать атрибуты, которые должны сохраняться как общие
3. Клиент на Сайте прописывает через запятую те атрибуты, которые должны сохраняться как общие

Далее плагин в момент сохранения атрибута, смотрит в опцию. Если название такое нашел, то сохраняет как Общий, если нет, то как Индивидуальный.

@artikus11

**Comment by artikus11** [comment]
> в момент создания атрибута достаточно там один флаг добавить, и таксономии и т д в теории должны сами создаться. но эт не точно

Надо проверить этот момент, чет в коде не наблюдаю. Тестить надо


> на Складе прописывается руками название атрибутов - это так уже работает
> на Сайте сделать опцию, где через запятую указать атрибуты, которые должны сохраняться как общие
> Клиент на Сайте прописывает через запятую те атрибуты, которые должны сохраняться как общие

Вариант, типа получаем массив названий и нужное создаем. Вариант. Попробую

@uptimizt

**Comment by uptimizt** [comment]
нашел решение:
1. если хотим получать общие атрибуты, то создаем общие атрибуты в консоли Сайта с тем же названием, которое в МойСклад
2. система при синхронизации по имени атрибута проверяет есть ли общие? и если есть то создает на их основе, иначе также как раньше создает индивидуальные

**Comment by uptimizt** [comment]
уже почти написал, скоро залью в мастер ветку

**Comment by artikus11** [comment]
Жду пуша)
