### ISSUE TITLE
test 9.0

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#445]
test cases https://github.com/wpcraft-ru/wooms/wiki/TestChecklist

- [x] - отключить вариации, услуги и картинки
- [x] - удалить все продукты
- [x] - сделать базовый синк
- [x] - включить картинки
- [x] - включить вариации
- [x] - проверить что все синхронизировалось

**Comment by Aliya072** [comment]
https://wooms.wpcraft.ru/product-category/mebel/divany/ У дивана ЛИКСЕЛЕ МУРБО нет картинки

**Comment by uptimizt** [comment]
@Aliya072 посмотрел - все есть

может быть надо было просто подождать когда закончится синк?

**Comment by Aliya072** [comment]
я не поняла нужно в целом отключить вариации, услуги и картинки или просто отключить их синхронизацию. Если первое, то у меня не получается найти где это сделать. 

и я не поняла, что такое базовый синк, гуглила, там тоже не понятно)

**Comment by Aliya072** [comment]
Не знаю важно это или нет) но у пиццы пипперони стоит картинка R2D2)))) https://wooms.wpcraft.ru/product/piczcza-pepperoni-barbekyu/

**Comment by uptimizt** [comment]
> Не знаю важно это или нет) но у пиццы пипперони стоит картинка R2D2, когда выбираешь толстое тесто и размер пиццы большой)))) https://wooms.wpcraft.ru/product/piczcza-pepperoni-barbekyu/

можно зайти в МС и сделать другую картинку - по вкусу - лучше конечно пиццу
