### ISSUE TITLE
Не работает синхронизация категорий

### ISSUE THREAD

**Issue by Mekhet** [wpcraft-ru/wooms#450]
Здравствуйте! Подскажите пожалуйста почему может не работать синхронизация категорий продуктов из МойСклад в Woocommerce .. галочка "Отключить синхронизацию категорий" отключена, но товары все равно не падают в категории

**Comment by Belecky** [comment]
Присоеденяюсь к вопросу, но кажется автор забил болт) Кто знает где можно купить подобные решения с рабочим функционалом?

**Comment by uptimizt** [comment]
опишите проблему подробнее, с учетом настроек

нужен порядок шагов как повторить проблему
