### ISSUE TITLE
Синхронизация удаленных товаров

### ISSUE THREAD

**Issue by b851TYiytNCk** [wpcraft-ru/wooms#456]
Сихнронизация товаров не поддерживает удаление товара на одной из сторон - итог: если вручную не удалить товар на сайте, а удалить в МС - можно создавать заказы с удаленными товарами в МС, которые не попадут в МС.

Шаги:

- Создать товар в МС
- Запустить синхронизацию на сайте
- Удалить товар в МС после синхронизации
- Запустить синхронизацию на сайте (не происходит удаление)
- Создать заказ на сайте (не попадет в МС, будет только на сайте)

**Comment by uptimizt** [comment]
тест в 9.6 - ок

**Comment by b851TYiytNCk** [comment]
@uptimizt спасибо, я дам отчет после тестирования
