### ISSUE TITLE
Затираются картинки у атрибутов которые создаются плагином WooCommerce Variation Swatches

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#46]
Доп инфу выясняем. 

Но надо проверить на предмет перезаписи атрибутов.

upd 20180910:
- прилепил файл с плагином
- надо проверить это ошибка нашего плагина или особенность работы доп плагина
- если наша ошибка - поправить
- если особенность плагина - предложить стоимость доработки

ХД 856

**Comment by uptimizt** [comment]
плагин
![image](https://user-images.githubusercontent.com/1852897/45114166-ec9ecf00-b154-11e8-8b6c-ca388fed8327.png)

**Comment by uptimizt** [comment]
страница плагина https://docs.woocommerce.com/document/woocommerce-color-and-image-swatches/

**Comment by artikus11** [comment]
@uptimizt При синке? Они и будут затираться. Плагин создает кастомные атрибуты, которые создаются и хранятся неизвестным нам способом https://docs.woocommerce.com/wp-content/uploads/2012/06/variation-color-and-image-swatches-05-e1484578075779.png

Плагин платный.  Код плагина посмотреть нет возможности.

**Comment by uptimizt** [comment]
Да, там еще и 1 версия ) Хотя по чейнджлогу уже давно 3+
Потому сейчас пробуем обновиться. А далее попробую больше инфы собрать.

**Comment by artikus11** [comment]
Ой-ой, как бы не сломалось все нафиг. Удачи!

**Comment by artikus11** [comment]
@uptimizt Хорошо

**Comment by uptimizt** [comment]
[woocommerce-variation-swatches-and-photos.zip](https://github.com/wpcraft-ru/wooms/files/2372518/woocommerce-variation-swatches-and-photos.zip)

файл с плагином для тестов

**Comment by artikus11** [comment]
Ок, принял

**Comment by uptimizt** [comment]
похоже нашел решение. у нас в некоторых местах атрибуты создавались с нуля при синхронизации.
сделал так чтобы плагин сначала брал существующие и обновлял их

**Comment by artikus11** [comment]
> похоже нашел решение. у нас в некоторых местах атрибуты создавались с нуля при синхронизации.
> сделал так чтобы плагин сначала брал существующие и обновлял их

Хорошая новость, надо подобным образом и все товары делать, а так у нас иначе все по новой создается. Я еще подумал, может как-то через Рест обновлять товары для тех у кого платный акк в МС

Напиши как пуш сделаешь

@uptimizt

**Comment by uptimizt** [comment]
Заказчик вернул заказ. Иных путей проверить механику пока не вижу. Потому закрываем до появления новых заявок с похожей ошибкой.

**Comment by artikus11** [comment]
@uptimizt А как интересно они решили эту проблему? Другой плагин использовали?

Можно попробовать на бесплатном проверить
