### ISSUE TITLE
Описание категории

### ISSUE THREAD

**Issue by KPABOOKING** [wpcraft-ru/wooms#463]
Доброго времени суток.
Имеем Woo и описание категории в нем, через какой хук возможно зацепить описание категории из Моего склада.

**Comment by uptimizt** [comment]
хороший вопрос, похоже логика там путанная и вот так сразу с одного хука я решение не нашел.

попробуем переписать тут https://github.com/wpcraft-ru/wooms/pull/474

**Comment by uptimizt** [comment]
добавил хук wooms_update_category_args
`$args_update = apply_filters('wooms_update_category_args', $args_update, $term_id, $data);`

**Comment by uptimizt** [comment]
добавил хук `wooms_product_categories_update` #517 

по аналогии можно зацепиться и добавить описания
