### ISSUE TITLE
Не загружаются фото товара в каталоги Woocomerce 

### ISSUE THREAD

**Issue by Iamsoncha** [wpcraft-ru/wooms#466]
Я конечно понимаю, тема наверное избитая, но все же.

при синхронизации не грузятся фото, сайт лежит на HANDYHOST.

в поддержку хостинга писала, что надо внести изменения, они написали:

От: Дмитрий (Специалист службы поддержки) - 2022-12-22 21:34:40
Уточните у них, пожалуйста, какие порты должны быть открыты и для какого IP-адреса, также уточните какой протокол нужен TCP или UDP?

Просто если они пишут, что после открытия портов картинки начали загружаться, то уточните, у них почему файлы не отображаются в WP?

ЧТО ДЕЛАТЬ? Попрыгать или менять хостинг? Помогите пожалуйста

**Comment by uptimizt** [comment]
Скорее всего менять хостинг, но проверим на своем бегете https://wpcraft.ru/hosting-wordpress-woocommerce/

**Comment by Iamsoncha** [comment]
Благодарю за ответ! Проблема решена техподдержкой хостинга. Включили расширение IMAGIC, открыли исходящее соединение к storage.files.mow1.cloud.servers.ru по порту 8080 и увеличили объём сайта с 10 до 25 гб. Ах да, и php обновили заодно. Все работает!
