### ISSUE TITLE
Ошибка синхронизации по расписанию после смены данных от моего склада

### ISSUE THREAD

**Issue by KPABOOKING** [wpcraft-ru/wooms#471]
Доброго времени суток, после смены данные от моего склада, затем ввода новых данных в настройки WooMS - не работает синхронизация по расписанию.
Последний лог с синхронизацией.
2022-12-12T00:01:45+00:00 ERROR https://online.moysklad.ru/api/remap/1.2/entity/organization:
{ "errors": [ { "error": "Ошибка аутентификации: Неправильный пароль или имя пользователя", "code": 1056, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1056" } ] }

**Comment by uptimizt** [comment]
исправление тут https://github.com/wpcraft-ru/wooms/pull/474
