### ISSUE TITLE
Остатки по складам

### ISSUE THREAD

**Issue by qwave** [wpcraft-ru/wooms#472]
Добрый день.
Нужно учитывать остатки по складам, когда выбрана опция "По всем складам", чтобы потом на сайте показывать наличии по каждому из складов.

На сколько понял надо делать дополнительный запрос `/report/stock/bystore` - как лучше это сделать чтобы не сломать ничего?

**Comment by uptimizt** [comment]
Это сложно, что такое склады? зачем они нужны? Для чего?

Вопросов много и все они ведут к очень разным решениям.

Надо четко понимать что зачем и для чего.

**Comment by uptimizt** [comment]
всопмнил что пара решений было тут 
раз https://github.com/wpcraft-ru/wooms/wiki/MultiWarehouse
два https://github.com/wpcraft-ru/wooms/wiki/StockMultiStore

**Comment by qwave** [comment]
Супер, первого решения достаточно, спасибо.
