### ISSUE TITLE
Не синхронизирует товар по коду

### ISSUE THREAD

**Issue by Pienene** [wpcraft-ru/wooms#478]
Товар создан на сайте и ему присвоен артикул руками. На складе есть товар с таким же артикулом, но был создан позже, чем на сайте.  При синке со складом не присвается ссылка на товар и ничего не обновляется. Товар простой, без вариаций.  Подскажите ,как их связать?

**Comment by uptimizt** [comment]
самый простой путь - удалить сайт на сайте - дать ему появиться исходя из данных со склада.

по правилам автоматизации источник правды должен быть 1.

если пытаться делать 2 источника правды - это дорого, сложно и долго.

товары как данные имеют 1 источник правды - это МойСклад.

попытка обмануть систему и правила ведет к тому что вы поседеете и потратие кучу денег на обман. Так будет дорого и долго.

соблюдайте правила и все будет ок.
