### ISSUE TITLE
Нет синхронизации

### ISSUE THREAD

**Issue by SaintDrag** [wpcraft-ru/wooms#497]
Третий день практически совсем нет синхронизации. В лучшем случаем 100-200 товаров обработает, потом застревает наглухо. Плагин последней версии. WordPress и Woocommerce тоже.
В «здоровье сайта» пишет: 
«REST API: (http_request_failed) cURL error 28: Connection timed out after 10001 milliseconds» и «Ваш сайт не смог выполнить петлевой запрос».
По журналу плагина просто не выполняются запросы.

Есть предположения можно что-то сделать? Или это какая-то общая беда?

**Comment by uptimizt** [comment]
доработали в https://github.com/wpcraft-ru/wooms/pull/519

проверьте
