### ISSUE TITLE
Проскакивают продукты с 0 ценой

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#50]
Когда в Склад заводят продукт, то цена не всегда еще определена. Такие продукты не должны попадать на Сайт.

![image](https://user-images.githubusercontent.com/1852897/45586959-87429f00-b907-11e8-97f9-56fa3dd1757f.png)

**Comment by artikus11** [comment]
@uptimizt В какой момент это происходит? В общем синке или при синке со складов?

**Comment by artikus11** [comment]
@uptimizt хм, как это работать должно? Вообще отклонять при синке или скрывать их на сайте?

**Comment by uptimizt** [comment]
в идеале отклонять. но мб лучше скрывать.
например как ты отклонишь если продукт уже был и кто то поставил 0 цену?
птм по логике наверное сокрытие будет более верным решением.
@artikus11

**Comment by artikus11** [comment]
@uptimizt Ок, сделаем скрытие

**Comment by uptimizt** [comment]
тест ок
