### ISSUE TITLE
При cинхронизации по артикулу товаров из МойСклад в Woocommerce подгружаются не все товары

### ISSUE THREAD

**Issue by ms850** [wpcraft-ru/wooms#500]
Подскажите пожалуйста, возможно кто-то сталкивался, синхронизируются не все товары из сервиса МойСклад в Woocommerce при использовании плагина WooMS. Все товары вариативные. Примерно первые 90 товаров синхронизируются, дальше система как-будто принудительно останавливается. По коду из Моего Склада то же самое, по UUID аналогично не подгружается.

WordPress - 6.0.2
Woocommerce - 6.8.1
WooMS - 9.2

Журнал выдает только сообщения:
2023-05-25T00:15:09+00:00 INFO Старт скрытия вариаций: 2023-05-25 00:15:09
2023-05-25T00:15:09+00:00 INFO Скрытие вариаций завершено: 2023-05-25 00:15:09
2023-05-25T01:17:47+00:00 INFO Старт скрытия вариаций: 2023-05-25 01:17:47
2023-05-25T01:17:47+00:00 INFO Скрытие вариаций завершено: 2023-05-25 01:17:47

Буду благодарен за любую информацию.

**Comment by igoreshka78** [comment]
Такая же проблема....
Решили проблему?

**Comment by uptimizt** [comment]
исправили ряд ошибок которые могли оказывать такое влияение в версии 9.6

проверьте @igoreshka78 @ms850

**Comment by igoreshka78** [comment]
Спасибо, уже нашли в чем была проблема лично у нас.
Если правильно помню было дублирование артикула


Sent from Gmail Mobile


Вс, 29 окт. 2023 г. в 15:01, Anatolii I ***@***.***>:
