### ISSUE TITLE
"Видимость в магазине" всегда меняется на "Каталог и результаты поиска"

### ISSUE THREAD

**Issue by infazz** [wpcraft-ru/wooms#503]
Проблема в том, что мы хотим скрывать некоторые товары, но при обновлении видимость всегда меняется на "Каталог и результаты поиска"

По коду видно, что в файле "wooms/includes/Products.php", просто прописано "$product->set_catalog_visibility('visible');"

Прошу хотя бы обернуть это в хук, например: 
`$product->set_catalog_visibility( apply_filters('wooms_product_visibility', 'visible', $product, $data_api) );`

Таким образом, отдельным кодом, мы сможем проверять текущую видимость товара и оставлять её без изменений.

Либо можете сами добавить сюда проверку видимости и оставлять её такой же, а не принидутельно открывать товары :)

Спасибо!

**Comment by infazz** [comment]
@uptimizt @evgrezanov @artikus11  жду обратной связи :)

**Comment by PineparksGit** [comment]
?

**Comment by uptimizt** [comment]
вы можете использовать стандартный хук
`add_filter( 'wooms_product_update', array( __CLASS__, 'update_product' ), 30, 2 );`

просто приоритет поставить 50 или 100

и там добавить свою логику указания видимости

@infazz @PineparksGit

**Comment by infazz** [comment]
К сожалению хук 'wooms_product_update' не сработает, так как к этому моменту плагин уже заменит статус видимости в магазине на 'visble'.

Проблема в том, что у вас прописано принудителное изменение $product->set_catalog_visibility('visible');
Как нам узнать какой был предыдущий статус у товара используя хук 'wooms_product_update'?

**Comment by uptimizt** [comment]
все сработает. хук стоит ниже по коду.

это значит что все что было до - не важно.

там же можно проверить какой статус стоит.

и добавить свою логику изменения статуса.

**Comment by infazz** [comment]
Я возможно не так обьясняю, попробую ещё раз описать проблему :) 

Смотрите:
1. Синхронизируются товары, все становятся 'visible'.
2. Менеджер магазина помечает некоторые товары как 'скрытые'.
3. Позже происходит синхронизация по расписанию и все товары опять ставятся как 'visible'.

Я не очень понимаю как хук 'wooms_product_update' может тут помочь? Ведь на момент когда мы им пользуемся и можем сделать что-то с данными товара, товар уже будет опять отмечен как 'visible'. А нам нужно оставлять в ручную скрытые товары скрытыми. Пользуясь хуком 'wooms_product_update' мы же не знаем, был ли товар 'hidden' или нет, так как мы уже видим его последнее значение 'visible'.

Но если обернуть значение "visible" в свой хук, можно будет манипулировать значением и мы будем видеть какое оно на момент обновления товара по расписанию.

Либо может я тут что-то не понимаю? как нам возможно оставлять состояние товара после синхронизации?

**Comment by uptimizt** [comment]
я не знаю.

возможно вы пытаетесь охладить воду при помощи кипятильника.

возможно это просто не возможно.

ну или это надо изучать, делать тех аналитику, собирать варианты решений - обсуждать - это сложный и долгий процесс.

для его выполнения нужно нанимать профессионалов https://github.com/wpcraft-ru/wooms/wiki/Hire-Developer

**Comment by artikus11** [comment]
@uptimizt там проблема в том, что видимость уже изменена на сайте, а при синке она меняется автоматически всегда на visible, независимо от того что сейчас на сайте есть. И ты ничего на этом хуке сделать не сможешь так как не знаешь какая видимость была до синка. Так что @infazz прав, там или фильтр надо ставить или как-то в хук wooms_product_update передавать предыдущее состояние товара, чтобы можно было проверить

**Comment by uptimizt** [comment]
> @uptimizt там проблема в том, что видимость уже изменена на сайте, а при синке она меняется автоматически всегда на visible, независимо от того что сейчас на сайте есть. И ты ничего на этом хуке сделать не сможешь так как не знаешь какая видимость была до синка. Так что @infazz прав, там или фильтр надо ставить или как-то в хук wooms_product_update передавать предыдущее состояние товара, чтобы можно было проверить. Или где то записывать состояние видимости до синка и после

не путай людей

все там есть - и пред состояние и все что надо для результата

просто это надо разбираться с тем что надо

хук позволяет дописать любую логику - хоть видимость поменять, хоть остатки, хоть категории - вообще все что угодно

**Comment by infazz** [comment]
@uptimizt  нет, я пытаюсь исправить ошибку в вашем плагине которым пользуются многие наши клиенты, и этот баг доставляет много неудобств.
ошибка именно в том, что 'visible' устанавливается всегда! 
Файл "wooms/includes/Products.php", просто указано "$product->set_catalog_visibility('visible');". Почему так? 

Эта строка убивает стандартный функционал woocommerce "Видимость в магазине". При каждой синхронизации всегда возвращается 'visible'. 

Не понимаю, откуда токе не желание исправить ситуацию лёгким добавленоем хука?


@artikus11 да, спасибо. Обернуть значение 'visible' в свой хук самое разумное и простое решение тут, и не нужно будет плодит доп. мета значения. Просто тем кому нужно будет, смогут добавит пару строк кода которые оставят текущее значение у товара.

**Comment by infazz** [comment]
@uptimizt 
"хук позволяет дописать любую логику" - да, но он перезаписывает значение "catalog_visibility" принудительно

**Comment by uptimizt** [comment]
этот хук - просто сброс

он в целом работает - только на базовых настройках

если есть доп настройки - работают другие слои конвеера

если активны опции про видимость - работают они - а этот код не работает

**Comment by uptimizt** [comment]
он там написан на случай - если сбросили настройки

в целом можно считать что его не существует

потому что другие слои заменяют эту логику по ходу работы

**Comment by uptimizt** [comment]
либо надо просто описать порядок шагов как повторить проблему

если мы говорим что ошибка в плагине

**Comment by artikus11** [comment]
@uptimizt "все там есть - и пред состояние и все что надо для результата" 

В каком таме? Дай пример, как поменять видимость товара в момент синка. 
Чет не смог придумать, как проверить предыдущее состояние товара.
Там еще передается row и data но что это за данные, хз. Может быть в них есть что-то что позволит проверить

**Comment by uptimizt** [comment]
```
	add_filter('wooms_product_save', function( \WC_Product $product, $data){
		$catalog_visibility = $product->get_catalog_visibility();
		//$catalog_visibility - current visibility

		if(something){
			// $product->set_catalog_visibility('visible')
		}

		return $product;


	}, 111, 2);


```

например так

**Comment by artikus11** [comment]
> ```
> 	add_filter('wooms_product_update', function( \WC_Product $product, $row){
> 		$catalog_visibility = $product->get_catalog_visibility();
> 		//$catalog_visibility - current visibility
> 
> 		if(something){
> 			// $product->set_catalog_visibility('visible')
> 		}
> 
> 		return $product;
> 
> 
> 	}, 111, 2);
> ```
> 
> например так

Дак тут $catalog_visibility = $product->get_catalog_visibility(); у товара видимость уже изменилась, всё. Была скрыта, стала видимой. Так как до хука сработала установка видимости. Или я чего то не понимаю

**Comment by uptimizt** [comment]
ты чего то не понимаешь )

не важно что было до этого хука

этот хук переопределяет все

и там впереди еще туча хуков которые переопределяют видимость

хочешь свою логику - пишешь хук выше по приоритету и добавляешь свою логику
