### ISSUE TITLE
"Отключить скрытие продуктов" не работает на вариациях

### ISSUE THREAD

**Issue by PineparksGit** [wpcraft-ru/wooms#504]
Привет! 
Прошу добавить выключение скрытия вариаций, сейчас это невозможно сделать.

Так же, у нас по крайней мере на одном сайте это работает не верно, проверка id сессии у товара и той, которая в options табице, не сходится (разница до 10 секунд...), и происходит скрытие товаров :(

**Comment by uptimizt** [comment]
с учетом последних версий - это актуально?
