### ISSUE TITLE
Не работает синхронизация с МС

### ISSUE THREAD

**Issue by volkovandrey17** [wpcraft-ru/wooms#505]
Добрый день!
Столкнулся со следующей проблемой, которую сам не могу решить. Несколько месяцев назад подключил функцию Интернет-магазин в Мой Склад и по CommerceML связал со своим сайтом, сделанным на WooCommerce, использую ваш плагин WooMS. Все заработало, хоть и не сразу - была синхронизация по остаткам и ценам. Когда я убедился, что все работает, начал заполнять карточки товаров, перенесенные из МС. Однако спустя какое-то время синхронизация работать перестала. Когда это произошло сказать не могу, так как товаров очень много и остатки меняются постоянно. 
Писал в поддержку МС и на форум разработчиков WooCommerce - везде сказали связаться с разработчиками плагина, поэтому пытаюсь написать сюда.
В данный момент, если попытаться нажать "Проверить соединение" в меню "Онлайн-торговля" пишет: "Не удалось установить соединение". В поддержке сказали, что это может быть из-за неправильно введенных логина и пароля - специально менял несколько раз, пробовал разные админки - безрезультатно.
Если попробовать запустить синхронизацию вручную из плагина, то обрабатывается 91 запись. Закономерности среди этих товаров не вижу, разные категории и разное время загрузки в МС. Сами записи не изменяются, даже эти 91. Товаров всего значительно больше - около 6 тысяч. 
Пожалуйста, подскажите, в чем может быть проблема. Пользовательские настройки я не менял, но мало ли... Ниже прикладываю сообщение агента службы поддержки МС - по их словам., на их стороне все нормально работает, проблема в коннекторах со стороны сайта, которые работают через плагин. Плагин переустанавливал - результата нет.

Здравствуйте. 
Причина возникшей проблемы явно прослеживается в плагине на стороне вашего сайта. Для синхронизации здесь используется модуль CommerceML. В МоемСкладе у вас настроен коннектор для синхронизации. Но и со стороны сайта этот модуль должен быть установлен и корректно работать. В CMS, вроде WooCommercе, модуль CommerceML ставится в виде плагина или приложения. По какой-то причине он у вас перестал корректно работать. Сейчас он не корректно обрабатывает запросы на соединение, получение остатков, отправку заказов. Поэтому рекомендуем на стороне сайта найти этот модуль и по возможности переустановить

Если кто-то сможет подсказать, буду очень благодарен, так как жалко потерянного времени и денег - купил функцию Интернет-магазин  на целый год

**Comment by igoreshka78** [comment]
Такая же проблема с синхронизацией товаров.
Кто как решает?

**Comment by uptimizt** [comment]
наш плагин не использует CommerceML
он работает на базе REST API.

думаю вы пытаетесь настраивать не там

**Comment by igoreshka78** [comment]
Понял спасибо.
По крайней мере все заработало.


Sent from Gmail Mobile


Вс, 29 окт. 2023 г. в 14:59, Anatolii I ***@***.***>:
