### ISSUE TITLE
Слетает форматирование для описания категорий

### ISSUE THREAD

**Issue by MichelMclaren** [wpcraft-ru/wooms#508]
Устанавливаешь форматирование для описания, ставишь теги ul,li,h2. Когда происходит синхронизация с мой склад, всё форматирование слетает под чистую и всё влетает под один тег, как исправить эту "фичу", уже какие только настройки не смотрел, не нашел ничего такого, что мне бы помогло.

**Comment by uptimizt** [comment]
надо думать

предлагайте

или обращайтесь за помощью сюда https://wpcraft.ru/wooms/
