### ISSUE TITLE
Плагин перестанет работать после 1 декабря 2023?

### ISSUE THREAD

**Issue by Stason077** [wpcraft-ru/wooms#509]
Доброго времени суток! Так понял что с 1 декабря МойСклад вносит изменения в работу своих API и плагин перестанет корректно функционировать без необходимого обновления. https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api
Верно понимаю?

**Comment by uptimizt** [comment]
возможно.

но сегодня мы выкатиили 9.3 релиз где частично проблему решили

вероятно в 9.4 релизе - дожмем

**Comment by Stason077** [comment]
> возможно.
> 
> но сегодня мы выкатиили 9.3 релиз где частично проблему решили
> 
> вероятно в 9.4 релизе - дожмем

Спасибо 🙏

**Comment by VdoxV** [comment]
> возможно.
> 
> но сегодня мы выкатиили 9.3 релиз где частично проблему решили
> 
> вероятно в 9.4 релизе - дожмем

Благодарим за Реализацию новой версии REST API MoySklad. Подскажите, пожалуйста, куда можно направить небольшой донат за такую важную доработку? Всем кто пользуется, предлагаю последовать такому примеру. Еще раз спасибо!

**Comment by uptimizt** [comment]
@VdoxV 
можно поставить оценку тут https://wordpress.org/plugins/wooms/

это будет лучше чем донат
