### ISSUE TITLE
Добавить инструкцию к выбору группы

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#51]
Если выбрана группа, то надо учесть что старые товары будут помечаться как отсутствующие.
А для этого нужна инструкция к опции которая объясняет как это сделать.

Типа так:
"После включения опции, старые товары будут помечаться как отсутствующие. Чтобы они пропали с сайта нужно убедиться что включена опция управления запасами, стоит опция сокрытия отсутствующих товаров, а в виджете категорий стоит опция скрывать пустые категории. Также для ускорения можно в разделе Статуса выполнить команду пересчета Счетчиков." В идеале снабдить инструкцию ссылками на соответствующие разделы.

**Comment by artikus11** [comment]
@uptimizt Длинный текст. Тут не только ссылки нужны, но и скриншоты. Может отдельную страницу сделать с инструкциями?

**Comment by uptimizt** [comment]
ссылок будет достаточно. длина текста думаю не проблема.
мб в будущем статью напишем и на нее тоже ссылку дадим. 
@artikus11

**Comment by artikus11** [comment]
Может сделать как в Вуке? В тултипах, примерно так
![image](https://user-images.githubusercontent.com/16116688/45599781-dae5e300-ba02-11e8-8556-547b8e945e0a.png)

**Comment by uptimizt** [comment]
@artikus11 не стоит. вот для тултипа текста слишком много и ссылки не будут работать скорее всего.

**Comment by uptimizt** [comment]
тест ок )
