### ISSUE TITLE
wooms_assortment_sync - Статус: Выполняется очередями в фоне

### ISSUE THREAD

**Issue by wsmnastya** [wpcraft-ru/wooms#510]
несколько дней бесконечно выполняется wooms_assortment_sync. **Остатки** - Статус: Выполняется очередями в фоне. При этом не может запуститься синхронизацию продуктов по расписанию, т.к. не выполнены задачи в фоне. Как то можно удалить все запланированные **wooms_assortment_sync** ? из-за чего это может происходить? в планировщике задача wooms_assortment_sync появляются по одной.

**Comment by uptimizt** [comment]
@wsmnastya исправлено в #517
