### ISSUE TITLE
похоже конвертация валюты сломалась... 

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#516]
похоже конвертация валюты сломалась... на сайте все цены в рублях по значениям в евро (в МС 100 евро -> на сайте 100 рублей)

_Originally posted by @LigeronAhill in https://github.com/wpcraft-ru/wooms/issues/475#issuecomment-1773741864_

**Comment by uptimizt** [comment]
@LigeronAhill нужно больше деталей.

что за настройки? евро рубли? где? на сайте? у товаров?

**Comment by LigeronAhill** [comment]
![Screenshot 2023-10-29 131545](https://github.com/wpcraft-ru/wooms/assets/132837792/f78c98f9-a55c-47cf-be6a-b3cc430cb89e)
![Screenshot 2023-10-29 131439](https://github.com/wpcraft-ru/wooms/assets/132837792/33f62364-1c42-4c83-8b6c-9ace5c51340b)
![Screenshot 2023-10-29 131359](https://github.com/wpcraft-ru/wooms/assets/132837792/b4fe6629-867e-4ae2-8c75-b6e78a947d65)

**Comment by uptimizt** [comment]
@LigeronAhill 
можете отправить пример JSON товара?

он должен лежать в мета поле wooms_data_api

![image](https://github.com/wpcraft-ru/wooms/assets/1852897/867a7947-cd5e-4d08-8d11-3cd2a05b6056)

**Comment by uptimizt** [comment]
и я верно понимаю что на сайт должна попадать цена в рублях?

с учетом цены в евро и текущего курса?

**Comment by uptimizt** [comment]
ну не знаю - пока выглядит сложным
опция эксперимент

приложил новую версию - попробуйте

[wooms.zip](https://github.com/wpcraft-ru/wooms/files/13198404/wooms.zip)

**Comment by uptimizt** [comment]
если не поможет - то либо ждать

любо сюда https://github.com/wpcraft-ru/wooms/wiki/Hire-Developer

**Comment by LigeronAhill** [comment]
Я пока вручную поправил, подожду. До обновления работало всё как надо, в МС цены в евро/юанях, в вуу все в рублях.

**Comment by uptimizt** [comment]
надо попробовать в версии 9.7 

сложно потому что у меня нет тест кейсов

потому протестировать это можно только на вашей стороне

**Comment by LigeronAhill** [comment]
Сейчас протестируем
