### ISSUE TITLE
После обновления не работает синхронизация.

### ISSUE THREAD

**Issue by MSvse** [wpcraft-ru/wooms#518]
После установки обновления версии 9.4 перестало отображаться количество нового загруженного товара - только "В наличии". Остатки перестали обновляться. Товары с изменившимся остатком скрылись, но не обновились.
После установки обновления версии 9.5 вообще синхронизация никакая не идет. Ни новинки, ни остатки, ничего.
Wordpress обновил до последнего. По старому совету очистил таблицы планировщика (wp_actionscheduler). Но это всё не помогло.
![mswoopng](https://github.com/wpcraft-ru/wooms/assets/149240973/392c552a-d780-40b0-96b2-1a59a2fe76fc)

**Comment by uptimizt** [comment]
@MSvse спасибо за обратную связь
можете включит логи и посмотреть что там? 
заодно отчет по инструкции https://github.com/wpcraft-ru/wooms/wiki/Diagnostics

**Comment by uptimizt** [comment]
нашел причину - в 9.6 будет исправлено
