### ISSUE TITLE
В комментарий к заказу добавлять ссылку на Заказ с Сайта

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#52]
проверить передается ли сейчас ссылка на Заказ с Сайта в поле Комментарий на стороне Склада.

как минимум точно не передается при тестировании этого кейса https://github.com/wpcraft-ru/wooms/issues/43

провеорить, поправить.

Важно чтобы я из Склада при просмотре Заказа, мог нырнуть в Сайт и там поработать.

**Comment by artikus11** [comment]
@uptimizt Не, не передается, задачи такой не было. Добавим

**Comment by artikus11** [comment]
@uptimizt Так пойдет?
![image](https://user-images.githubusercontent.com/16116688/45623358-20a0bb00-ba98-11e8-95a8-ffd805588b89.png)

**Comment by uptimizt** [comment]
да, тока проверь чтобы он добавлялся к тому комменту что пишет сам Клиент
@artikus11

**Comment by artikus11** [comment]
@uptimizt Не понял. То есть ссылка должна быть только если есть какой-то комментарий?

**Comment by uptimizt** [comment]
ссылка должна быть всегда. но если есть коммент то она должна быть снизу и не заменять коммент собой. чтобы коммент Клиента тоже сохранялся. вместе с ссылкой. 
@artikus11

**Comment by uptimizt** [comment]
агонь! :)

**Comment by uptimizt** [comment]
тест ок
