### ISSUE TITLE
Синхронизируются все категории, хотя выставлены только несколько

### ISSUE THREAD

**Issue by markov12** [wpcraft-ru/wooms#520]
При автоматической синхронизации плагин синхронизирует категории из моего  склада на сайт, причем даже те ктороые не выставлены в настройках плагина 
https://shottr.cc/s/1jd9/SCR-20231030-ibp.png 
в скриншоте выставлены категории: Женская одежда, Мужская одежда, Детская одежда, Унисекс одежда, Sale, Аксессуары

https://shottr.cc/s/1PwB/SCR-20231030-iey.png
Сихронизируются кроме них также Bestsellers, Акция, для маркета, не выгружать в каталог, под заказ.
Товары в эти категории не синхронизируются, только сами категории.

Еще 2 недели назад все работало корректно. и эти категории на пустом месте не создавались.
Плагин версии 9.5 так как далее необходимо обновлять php

**Comment by uptimizt** [comment]
тут есть обходное решение - скрывать категории без продуктов - должно сработать

это в вашем случае сработает?

если нет то почему?

**Comment by markov12** [comment]
Да скрытие категорий продуктов срабатывает и действительно скрывает категории с сайта, но в фильтрации они остаются https://shottr.cc/s/1MYj/SCR-20231102-hs8.jpeg

**Comment by markov12** [comment]
После тщательного изучения вопроса, все удалось решить установкой плагина Hide Categories and Products for Woocommerce теперь и пустые категории скрываются и по сайту и в фильтрах и где бы то ни было.

**Comment by markov12** [comment]
После тщательного изучения вопроса, все удалось решить установкой плагина Hide Categories and Products for Woocommerce теперь и пустые категории скрываются и по сайту и в фильтрах и где бы то ни было.
