### ISSUE TITLE
Не обновляются остатки

### ISSUE THREAD

**Issue by anfisabreus** [wpcraft-ru/wooms#521]
После синхронизации на сайте не устанавливается галочка Управлять запасами? 
В разделе "Мой Склад" - "Управление" Остатки всегда в Ожидании задач (на скриншоте ниже).
Версия плагина 9.6

<img width="318" alt="Снимок экрана 2023-11-01 в 14 08 14" src="https://github.com/wpcraft-ru/wooms/assets/25826782/4d4a822b-3dbd-4ccd-9e9d-7f843b422b65">

**Comment by uptimizt** [comment]
инструкции тут https://github.com/wpcraft-ru/wooms/wiki/OpenSource

**Comment by uptimizt** [comment]
нужно больше информации

проверил на тест стенде - все ок


![Image](https://github.com/wpcraft-ru/wooms/assets/1852897/3a9dbed5-ab0d-472a-9c14-e65c68b53b4d)

**Comment by anfisabreus** [comment]
Спасибо за ответ! Обновила до версии 9.7. Удалила все товары и еще раз включила синхронизацию. К сожалению остатки так и не обновились. В логах вот такая картина,

<img width="1113" alt="Снимок экрана 2023-11-06 в 01 51 11" src="https://github.com/wpcraft-ru/wooms/assets/25826782/0c084c30-1ec2-4265-9520-8a78de07b395">

Такие же логи с 23 октября. 11 октября остатки обновлялись. К сожалению между 11 октября и 23 октября логов по остаткам нет. 

Вот скрин логов остатков за 11 октября:

<img width="1111" alt="Снимок экрана 2023-11-06 в 01 51 39" src="https://github.com/wpcraft-ru/wooms/assets/25826782/87343d2d-ab30-4810-966c-c3e1840cc6dc">

Подскажите пожалуйста, какие еще данные необходимы для диагностики?

Спасибо заранее за помощь.

**Comment by anfisabreus** [comment]
Новая информация о проблеме. Версия 9.7 не синхронизирует товары со склада.

Я установила плагин новой версии (9.7) на тестовом сайте (без лишних плагинов, на дефортной теме), синхронизация не сработала. Ни один товар из моего склада не появился на сайте. Тогда я удалила плагин версии 9.7 и установила версию 9.2 - все заработало как часы. Идеальная синхронизация :)

проблема где-то между версиями 9.2 и 9.7

**Comment by uptimizt** [comment]
возможно это как то зависит от настроек.

можете скинуть свои настройки?

типа скрин всех настроек на странице.

чтобы мы могли это как то повторить на своих тестах.

пока по тестам у нас все ок. и мы не можем повторить эту проблему

@anfisabreus

**Comment by uptimizt** [comment]
можно ускорить через услугу диагностики https://wpcraft.ru/wooms/#diagnostics

**Comment by Stason077** [comment]
Подтверждаю. Обновились с 9.2 на 9.7 на тестовой среде. Синхронизация товаров работает, но без остатков по товарам (т.е. просто "В наличии"). В логах такая же картина как у [anfisabreus](https://github.com/anfisabreus)

**Comment by Taimerlan** [comment]
Ровно такая же проблема на новой версии, скажите, у вас два склада или один?

**Comment by Stason077** [comment]
> Ровно такая же проблема на новой версии, скажите, у вас два склада или один?

Один - основной

**Comment by anfisabreus** [comment]
> Ровно такая же проблема на новой версии, скажите, у вас два склада или один?

Тоже один - основной

**Comment by uptimizt** [comment]
пока не вижу решений

нужно делать что то про https://github.com/wpcraft-ru/wooms/issues/527

**Comment by uptimizt** [comment]
решние было тут https://github.com/wpcraft-ru/wooms/issues/522
