### ISSUE TITLE
Bug: Не синхронизируются товары 

### ISSUE THREAD

**Issue by liemuar** [wpcraft-ru/wooms#524]
Плагин установлен из каталога, логин-пароль введены корректно, но при запуски синхронизации товаров (вручную), в журнале нет ошибок, но если посмотреть в запланированных действиях, действие "wooms_products_walker" выполняется неудачно и пишет вот такую ошибку "действие не удалось через Async Request: Cannot use object of type WP_Error as array"
Конфигурация wordpress --->
### wp-core ###

version: 6.4.1
site_language: ru_RU
user_language: ru_RU
timezone: +03:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-active-theme ###

name: undressme (undressme)
version: undefined
author: Аноним
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, woocommerce, menus, widgets
theme_path: wp-content/themes/undressme
auto_update: Выключено

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: Команда WordPress, Автоматические обновления отключены

### wp-plugins-active (28) ###

Admin Menu Editor Pro: version: 2.20, author: Janis Elsts (latest version: 2.22), Автоматические обновления отключены
Advanced Custom Fields PRO: version: 6.1.7, author: WP Engine (latest version: 6.2.2), Автоматические обновления отключены
Code Snippets: version: 3.4.2, author: Code Snippets Pro (latest version: 3.6.1), Автоматические обновления отключены
Contact Form 7: version: 5.8, author: Takayuki Miyoshi (latest version: 5.8.2), Автоматические обновления отключены
Custom Post Type UI: version: 1.13.7, author: WebDevStudios (latest version: 1.15.1), Автоматические обновления отключены
Cyr-To-Lat: version: 6.0.3, author: Sergey Biryukov, Mikhail Kobzarev, Igor Gergel (latest version: 6.0.5), Автоматические обновления отключены
Duplicator Pro: version: 4.5.11.1, author: Duplicator, Автоматические обновления отключены
Firebase Authentication for WordPress: author: (undefined), version: 1.0, Автоматические обновления отключены
Flamingo: version: 2.4, author: Takayuki Miyoshi, Автоматические обновления отключены
Integration for UDS WooCommerce: version: 1.0, author: Alex Kacharin, Автоматические обновления отключены
Intuitive Custom Post Order: version: 3.1.4.1, author: hijiri, Автоматические обновления отключены
Loco Translate: version: 2.6.4, author: Tim Whitlock (latest version: 2.6.6), Автоматические обновления отключены
MailPoet: version: 4.30.0, author: MailPoet (latest version: 4.35.1), Автоматические обновления отключены
Media Library Organizer: version: 1.6.0, author: Optimole, Автоматические обновления отключены
reCAPTCHA (v2 & v3) for Asgaros Forum: version: 1.0.4, author: Hitesh Chandwani, Автоматические обновления отключены
Show Current Template: version: 0.5.2, author: JOTAKI Taisuke, Автоматические обновления отключены
Variation Swatches for WooCommerce: version: 2.0.26, author: Emran Ahmed (latest version: 2.0.28), Автоматические обновления отключены
Variation Swatches for WooCommerce - Pro: version: 2.0.26, author: Emran Ahmed (latest version: 2.0.27), Автоматические обновления отключены
weLaunch Framework: version: 1.0.2, author: weLaunch.io (latest version: 1.0.19), Автоматические обновления отключены
WooCommerce: version: 8.0.1, author: Automattic (latest version: 8.2.2), Автоматические обновления отключены
WooCommerce Checkout Manager: version: 7.2.5, author: QuadLayers (latest version: 7.3.0), Автоматические обновления отключены
WooCommerce Multiple Customer Addresses: version: 16.3, author: Lagudi Domenico, Автоматические обновления отключены
WooCommerce Product & Gallery Images (Slider, Zoom, Lighbox): version: 1.1.2, author: weLaunch, Автоматические обновления отключены
WooCommerce Single Variations: version: 1.3.19, author: weLaunch, Автоматические обновления отключены
WooCommerce Variation Prices: version: 1.0.9, author: Barn2 Plugins, Автоматические обновления отключены
WooMS: version: 9.7, author: WPCraft, Автоматические обновления отключены
WordPress Importer: version: 0.8.1, author: wordpressdotorg, Автоматические обновления отключены
WP Add Mime Types: version: 3.0.3, author: Kimiya Kitani, Автоматические обновления отключены

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: Spam Protection: version: 5.2, author: Automattic - Anti Spam Team (latest version: 5.3), Автоматические обновления отключены
Login with phone number: version: 1.6.3, author: Hamid Alinia - idehweb (latest version: 1.6.5), Автоматические обновления отключены
WooCommerce - 1C - Data Exchange: version: 1.124.0, author: itgalaxycompany, Автоматические обновления отключены
WooCommerce Checkout Manager PRO: version: 1.4.7, author: QuadLayers, Автоматические обновления отключены
WooCommerce Ship to Multiple Addresses: version: 3.8.6, author: WooCommerce, Автоматические обновления отключены
YITH WooCommerce Points and Rewards Premium: version: 3.7.0, author: YITH, Автоматические обновления отключены

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 МБ
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 МБ
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 МБ
	imagick::RESOURCETYPE_MEMORY: 256 МБ
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-163-generic x86_64
httpd_software: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
php_version: 8.2.10 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2023-11-09T11:00:18+00:00
utc-time: Thursday, 09-Nov-23 11:00:18 UTC
server-time: 2023-11-09T14:00:16+03:00

### wp-database ###

extension: mysqli
server_version: 10.11.5-MariaDB-1:10.11.5+maria~ubu2004-log
client_version: mysqlnd 8.2.10
max_allowed_packet: 268435456
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: .../public_html/wp-content
WP_PLUGIN_DIR: .../public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Не определено
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb3
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wooms-plugin-debug ###

Wooms Version: 9.7 ✔️
Woocommerce: 8.0.1 ✔️

**Comment by uptimizt** [comment]
нужен лог ошибки из debug.log


там где написана причина ошибки

**Comment by artikus11** [comment]
@uptimizt проблему подтверждаю. Такое происходит когда много вложенных категорий импортируется в первый раз. Проблема тут https://github.com/wpcraft-ru/wooms/blob/master/includes/ProductsCategories.php#L165 там приходит объект а не ожидаемый массив. 

Решается проверкой на WP_Error
![image](https://github.com/wpcraft-ru/wooms/assets/16116688/c8a52134-6783-4953-a995-5f7286f70ee4)

**Comment by uptimizt** [comment]
@artikus11 добавил в работу

но когда доберусь - пока не ясно

если есть возможность - можно сделать PR
