### ISSUE TITLE
Сильно растут таблицы wp_actionscheduler_actions и wp_actionscheduler_logs

### ISSUE THREAD

**Issue by miligram-ru** [wpcraft-ru/wooms#525]
День добрый!

Уже больше полугода при активном плагине WooMS мучаемся с проблемой - в SQL-базе таблицы wp_actionscheduler_actions и wp_actionscheduler_logs разрастаются до просто неприличных размеров. Как я понимаю, не удаляются выполненные запланированные задачи и их логи, но как решить эту проблему, к сожалению, знаний не хватает.

Большая просьба помочь и заранее спасибо!

P.S. Wordpress, WooCommerce и WooMS последних версий, но и на предыдущих данная проблема наблюдалась.

**Comment by artikus11** [comment]
По дефолту данные таблицы очищаются по крону раз в месяц. А при той активности что происходит в момоент синхронизации с Мой склад это надверное надо каждый день делать. 

Попробуйте изменить время очистки на один день

`add_filter( 'action_scheduler_retention_period', function ( $period ) {
	return 1 * DAY_IN_SECONDS;
} );`

Удалять еще не только выполненые задачи но и неудавшиеся

`add_filter( 'action_scheduler_default_cleaner_statuses', function ( $statuses ) {
	$statuses[] = 'failed';
	return $statuses;
} );`

Ну и количество одновременно удаляемых задач можно увеличить, по дефолту по 20 шт

`add_filter( 'action_scheduler_cleanup_batch_size', function ( $batch_size ) {
	return 100;
} );`


Код добавлять в файл functions.php темы

**Comment by miligram-ru** [comment]
Спасибо! Попробуем!
