### ISSUE TITLE
Ошибки в логах при передаче заказов на МС. Версия плагина 9.7

### ISSUE THREAD

**Issue by zerg00d** [wpcraft-ru/wooms#526]
После обновления плагина до 9.7 в логах ordersender видим вот такое:

2023-11-15T07:32:40+00:00 ERROR Ошибка передачи заказа 17195:
{ "errors": [ { "error": "Некорректный сервер в идентификаторе объекта: https:\/\/api.moysklad.ru\/api\/remap\/1.2\/entity\/product\/acd745e8-83b5-11e6-7a31-d0fd0030855e", "code": 1059, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1059", "line": 1, "column": 1753 } ] }
2023-11-15T07:32:41+00:00 ERROR При передаче Заказа 17195 - данные не переданы:
{ "errors": [ { "error": "Некорректный сервер в идентификаторе объекта: https:\/\/api.moysklad.ru\/api\/remap\/1.2\/entity\/counterparty\/281e3012-8389-11ee-0a80-0e6500180677", "code": 1059, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1059", "line": 1, "column": 2948 } ] }
2023-11-15T07:33:16+00:00 INFO Старт очереди отправки заказов - 2023-11-15 07:33:16
2023-11-15T07:33:16+00:00 INFO Старт очереди отправки заказов - 2023-11-15 07:33:16
2023-11-15T07:33:17+00:00 ERROR При передаче Заказа 17195 - данные не переданы:
{ "errors": [ { "error": "Некорректный сервер в идентификаторе объекта: https:\/\/api.moysklad.ru\/api\/remap\/1.2\/entity\/counterparty\/281e3012-8389-11ee-0a80-0e6500180677", "code": 1059, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1059", "line": 1, "column": 2948 } ] }
2023-11-15T07:33:20+00:00 ERROR При передаче Заказа 17195 - данные не переданы:
{ "errors": [ { "error": "Некорректный сервер в идентификаторе объекта: https:\/\/api.moysklad.ru\/api\/remap\/1.2\/entity\/counterparty\/281e3012-8389-11ee-0a80-0e6500180677", "code": 1059, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1059", "line": 1, "column": 2948 } ] }
2023-11-15T07:33:21+00:00 ERROR При передаче Заказа 17195 - данные не переданы:
{ "errors": [ { "error": "Некорректный сервер в идентификаторе объекта: https:\/\/api.moysklad.ru\/api\/remap\/1.2\/entity\/counterparty\/281e3012-8389-11ee-0a80-0e6500180677", "code": 1059, "moreInfo": "https:\/\/dev.moysklad.ru\/doc\/api\/remap\/1.2\/#error_1059", "line": 1, "column": 2948 } ] }
2023-11-15T07:33:22+00:00 ERROR При передаче Заказа 17195 - данные не переданы:

Возможно это нормально. Но решили поделиться.

**Comment by uptimizt** [comment]
пока ничего не ясно - у нас на тест сервере - все работает ок

если будет больше деталей - мб что то получится

**Comment by uptimizt** [comment]
детали тут https://github.com/wpcraft-ru/wooms/issues/527
