### ISSUE TITLE
Кнопка "Отправить в МойСклад" в метабоксе Заказа

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#53]
вижу как сделан метабокс. оч круто!
в голове сразу возникает желание "Отправить в МойСклад". и тут была бы оч кстати ссылка, которая просто ведет на страницу инструментов где можно запустить передачу.

![image](https://user-images.githubusercontent.com/1852897/45599628-a15baa80-b9f7-11e8-8f84-e7e972b95b39.png)

**Comment by artikus11** [comment]
@uptimizt А надо ли? Заказ через минуту уже уйдет в МС. Только дошло
1. Метабокс заказов наверное должен быть наверное в платной версии? Да и остальные тоже, наверное?
2. Если заказ не отправляется, то надо наверное ссылку на журнал с ошибками приложить и ссылку на обращение в поддержку?

**Comment by uptimizt** [comment]
> А надо ли? Заказ через минуту уже уйдет в МС. Только дошло

надо )

> Метабокс заказов наверное должен быть наверное в платной версии? Да и остальные тоже, наверное?

вообще то что ты сделал метабоксы отдельным классом - это нарушение принципа ВИСИ.
по сути код метабокса должен быть в том же классе где и его связанная сущность. тогда такого вопроса не будет. Товары в базовой. Заказы в расширенной.

> Если заказ не отправляется, то надо наверное ссылку на журнал с ошибками приложить и ссылку на обращение в поддержку?

пока не вижу в этом смысла. ошибка должна вылетать на странице управления. и вроде бы вылетает.

**Comment by artikus11** [comment]
@uptimizt Затупил немного, бывает. Тогда разнесу метабоксы и добавлю ссылку на управление отправками

**Comment by uptimizt** [comment]
тест ок
