### ISSUE TITLE
Поддержка скидок в заказе, заданных через отрицательные fees

### ISSUE THREAD

**Issue by Daniel217D** [wpcraft-ru/wooms#532]
**Что нужно?**
Поддержка WC_Order_Item_Fee при создании заказа по API

**Чтобы что?**
Чтобы можно было передавать дополнительные наценки через fee с положительной суммой и скидки через fee с отрицательной суммой

**Как?**
Передавать информацию о скидке в заказ через фильтр wooms_order_data

**Бюджет**
После оценки возможности выполнения задачи и сроков работы

**Comment by uptimizt** [comment]
это надо разбираться, делать аналитику, подбирать тех решения

детали тут https://wpcraft.ru/wooms/
