### ISSUE TITLE
Несовместим с включенной функцией WooCommerce

### ISSUE THREAD

**Issue by MariR2019** [wpcraft-ru/wooms#539]
При активации плагина выходит ошибка:
"Этот плагин несовместим с включенной функцией WooCommerce «Высокопроизводительное хранилище заказов», его не следует активировать."
![woo](https://github.com/wpcraft-ru/wooms/assets/47552301/48fee5bb-f569-4ca1-a481-70a7c9438cfa)

**Comment by darkvovich** [comment]
Да, есть такая проблемка

**Comment by Iamsoncha** [comment]
а что с этим обычно делают?

**Comment by MariR2019** [comment]
> а что с этим обычно делают?

Я просто отключила эту функцию совсем.

**Comment by Iamsoncha** [comment]
Какая у вас версия woo? Как вы её отключили? Подскажите пожалуйста, у меня кнопка переключения не активна

> > а что с этим обычно делают?
> 
> Я просто отключила эту функцию совсем.

**Comment by MariR2019** [comment]
> Какая у вас версия woo? Как вы её отключили? Подскажите пожалуйста, у меня кнопка переключения не активна
> 
Деактивируйте плагин, кнопка станет доступной. Отключите и потом снова активируйте плагин.

**Comment by Iamsoncha** [comment]
> > Какая у вас версия woo? Как вы её отключили? Подскажите пожалуйста, у меня кнопка переключения не активна
> 
> Деактивируйте плагин, кнопка станет доступной. Отключите и потом снова активируйте плагин.

Плагин какой именно? Wooms или сам woocomerce?

**Comment by Iamsoncha** [comment]
Все сработало! Спасибо большое!!!

> > Какая у вас версия woo? Как вы её отключили? Подскажите пожалуйста, у меня кнопка переключения не активна
> 
> Деактивируйте плагин, кнопка станет доступной. Отключите и потом снова активируйте плагин.

**Comment by uptimizt** [comment]
эта фича сложная и наш плагин пока не тестировался с ней. как и 90% других плагинов.

потому прежде чем ее включать - стоит 100 раз подумать
