### ISSUE TITLE
Не синхронизируются статусы заказов Мой Склад > Сайт. Запрос к старому API

### ISSUE THREAD

**Issue by varikweru** [wpcraft-ru/wooms#541]
Столкнулся с проблемой того, что статусы с МС не улетали на сайт.
Поиски привели меня к функции **get_data_order_from_moysklad($data_request)**
Через вынос в логи всей информации, я понял, что запрос в данной функции уходит не к api.moysklad.ru, а к online.moysklad.ru, из-за чего `$data_order = request($url);` кидает запрос на несуществующую страницу, и дальше всё обрывается.
Я заменил для себя это максимально прямолинейно:
`$url = str_replace('online','api',$data["events"][0]["meta"]["href"]);`
Всё заработало.
Не совсем понимаю, это баг самого WooMS, или Мой Склад по вебхуку отдает старую инфу.
В любом случае, мне кажется, что это важный функционал, который хорошо бы подправить:)

**Comment by eduardgermoniy** [comment]
![image](https://github.com/wpcraft-ru/wooms/assets/31701982/8303afae-b84d-4585-a62c-b4d3c96bea1a)
Это с документации.

**Comment by uptimizt** [comment]
в новых версиях вроде бы как это поправлено
