### ISSUE TITLE
После установки версии 9.11 сайт "висит" - проблема с checked

### ISSUE THREAD

**Issue by MariR2019** [wpcraft-ru/wooms#553]
После установки новой версии плагина сайт повис:
1. Невозможно загрузить или найти файл в медиабиблиотеке
2. Невозможно установить какой-либо плагин
3. Невозможно через админпанель найти плагин - идет бесконечная загрузка
4. При перезагрузке страниц в админпанели появляется checked='checked'

Ошибка:
Установка не удалась: checked='checked'{"success":true,"data":{"install":"plugin","slug":"classic-editor","pluginName":"Classic Editor","debug":["\u0421\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u0435 \u043f\u0430\u043a\u0435\u0442\u0430 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0438\u0437 https:\/\/downloads.wordpress.org\/plugin\/classic-editor.1.6.3.zip&#8230;","\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c \u043f\u043e\u0434\u043b\u0438\u043d\u043d\u043e\u0441\u0442\u044c classic-editor.1.6.3.zip, \u0442\u0430\u043a \u043a\u0430\u043a \u043f\u043e\u0434\u043f\u0438\u0441\u044c \u043d\u0435 \u0431\u044b\u043b\u0430 \u043d\u0430\u0439\u0434\u0435\u043d\u0430.","\u0418\u0437\u0432\u043b\u0435\u0447\u0435\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u043e\u0432&#8230;","\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u043f\u043b\u0430\u0433\u0438\u043d\u0430&#8230;","\u041f\u043b\u0430\u0433\u0438\u043d \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d.","\u041d\u0435\u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0438\u0437 \u0432\u0430\u0448\u0438\u0445 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u043e\u0432 \u043d\u0443\u0436\u0434\u0430\u044e\u0442\u0441\u044f \u0432 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0438. \u041f\u043e\u0434\u043e\u0436\u0434\u0438\u0442\u0435 \u0435\u0449\u0451 \u043d\u0435\u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0441\u0435\u043a\u0443\u043d\u0434, \u043f\u043e\u043a\u0430 \u043c\u044b \u043e\u0431\u043d\u043e\u0432\u0438\u043c \u0438\u0445 \u0442\u043e\u0436\u0435.","\u0421\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u043e\u0432 \u0438\u0437 https:\/\/downloads.wordpress.org\/translation\/plugin\/classic-editor\/1.6.3\/ru_RU.zip&#8230;","\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c \u043f\u043e\u0434\u043b\u0438\u043d\u043d\u043e\u0441\u0442\u044c ru_RU.zip, \u0442\u0430\u043a \u043a\u0430\u043a \u043f\u043e\u0434\u043f\u0438\u0441\u044c \u043d\u0435 \u0431\u044b\u043b\u0430 \u043d\u0430\u0439\u0434\u0435\u043d\u0430.","\u0418\u0437\u0432\u043b\u0435\u0447\u0435\u043d\u0438\u0435 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f&#8230;","\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u0441\u0432\u0435\u0436\u0435\u0439 \u0432\u0435\u0440\u0441\u0438\u0438&#8230;","\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0441\u0442\u0430\u0440\u043e\u0439 \u0432\u0435\u0440\u0441\u0438\u0438 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u0430&#8230;","\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u043e\u0431\u043d\u043e\u0432\u043b\u0451\u043d."],"activateUrl":"https:\/\/мой сайт\/wp-admin\/plugins.php?_wpnonce=451c94097f&action=activate&plugin=classic-editor\/classic-editor.php"}}

При откате на версию 9.10 эта проблема исчезает (но там другие проблемы...)
![22222222222](https://github.com/wpcraft-ru/wooms/assets/47552301/9a0e9aa4-e1f2-41cf-91d0-3194241584a3)

Кто решил эту проблему?

**Comment by slavik67** [comment]
У меня похожие проблемы:
Медиабиблиотека не грузится совсем.
Писк по товарам на сайте не работает.
Поиск внутри сайта по клиентам тоже не работает
Отключаю плагин (версии 9.11) всё начинает работать корректно.
Включаю, сразу проблема с "поиском" по сайту, внутри сайта, и с медиа библиотекой.
Пробовал оставлять активными только два плагина WooCommerce и WooMS эффект тот же самый.

Кто подскажет в чём проблема? Как решить?

**Comment by MrDotShop** [comment]
Ребят можт ктото уже нашел решение, а то всё что ajax использует сломалось и грустненько

**Comment by Spec-Gamer** [comment]
/wooms/includes/ProductStocks.php:490 
 замените 
` 'value' => checked( 1, get_config( 'stock_and_reserve' ) ),`
на
`'value' => checked( 1, get_config( 'stock_and_reserve' ), false ),`
![2024-05-18_162008](https://github.com/wpcraft-ru/wooms/assets/19875910/6faf4a91-1761-4912-aa56-01ace717dc52)

**Comment by MrDotShop** [comment]
> /wooms/includes/ProductStocks.php:490 замените ` 'value' => checked( 1, get_config( 'stock_and_reserve' ) ),` на `'value' => checked( 1, get_config( 'stock_and_reserve' ), false ),` ![2024-05-18_162008](https://private-user-images.githubusercontent.com/19875910/331803956-6faf4a91-1761-4912-aa56-01ace717dc52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNDM1NDIsIm5iZiI6MTcxNjE0MzI0MiwicGF0aCI6Ii8xOTg3NTkxMC8zMzE4MDM5NTYtNmZhZjRhOTEtMTc2MS00OTEyLWFhNTYtMDFhY2U3MTdkYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE4MjcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYTgyYzJlYzBhYjU1ZGQzMzg5NzM4ZTE2MmM2NzQ3ODdhMTc0YmY4YWZkYzg4NTQ3NDg2NTMxYzU3YjFiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6NyJEUOWmUXcAfTLqqxfPOdQ_VLyhGEtMin9cYh86lo)

спасибо, всё работает

**Comment by MariR2019** [comment]
@Spec-Gamer спасибо огромное!

**Comment by aiiddqd** [comment]
добавил правку сюда https://github.com/wpcraft-ru/wooms/pull/552
