### ISSUE TITLE
Bug: Здравствуйте, подскажите пожалуйста, позволяет ли WooMS при создании заказа на сайте, автоматически перекидывать заказ в мой склад, нужно чтобы он дополнительно не создавал контрагента, если таковой уже имеется, большое спасибо!

### ISSUE THREAD

**Issue by Dexon12** [wpcraft-ru/wooms#554]
**Как есть**
//Краткое описание проблемы и как ее воспроизвести

**Как надо**
//Краткое описание истории как должно быть

**Screenshots**
//Примеры и снимки которые могут прояснить суть проблемы

**Дополнительные детали**
//Все что может быть полезно для диагностики и поиска решений

**Бюджет**
//Сколько готовы заплатить за решение проблемы? Если интересует помощь за оплату.

**Comment by aiiddqd** [comment]
в теории да, так и задумано

если что то не так - то лучше создать отдельную задачу и описать кейс с проблемой
