### ISSUE TITLE
Передавать вес товара из МС

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#58]
Пожелание клиента

> Неплохо было бы переносить вес товара из моего склада. Но там есть нюанс - в МС десятичная часть отделяется запятой, а в вордпрессе точкой. Если в вукомерс занести вес с запятой, то при сохрании вес пустой будет.

**Comment by uptimizt** [comment]
в последней версии все ок.
надо чтобы была включена опция:
Включить синхронизацию доп. полей как атрибутов
