### ISSUE TITLE
Переключатель для импорта описания товаров

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#59]
Пожелание клиента

> В вукомерсе есть обычное описание товара и короткое описание. Некоторые темы выводят обычное описание, а некоторые короткое. Можно сделать выбор, какое описание использовать? То есть в Моем складе заполнено поле "Описание", а в вашем плагине выбираем, куда оно будет попадать, в полное описание или в короткое.

`

**Comment by uptimizt** [comment]
дубль https://github.com/wpcraft-ru/wooms/issues/126
