### ISSUE TITLE
Импорт услуг - первая версия

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#60]
# Вариант решения
В 7 версии сделано так что услуги начали попадать на сайт. Но как обычные товары.

Надо сделать так чтобы услуги залетали как виртуальные продукты.

# DoD
- продукты типа услуга из МС попадают в ИМ как виртуальные продукты
- при синке остатков если это услуга, то продукт не помечается как не доступный

# Заметки
Пожелание клиента

> Есть в продаже цифровые товары (видеокурсы) по идее по ним нет остатков и это не товары, а услуги. У услуг в Моем складе нет артикула, но есть код. 

Это скорее надо делать отдельным плагином, товар виртуальный

**Comment by uptimizt** [comment]
@artikus11 зачем? на мой взгляд это просто еще один слой синхронизации. по аналогии с вариациями, комплектами и т д.
делаем класс и опцию. если включено то система пробует забирать этот тип продукта. и создавать как виртуальные продукты в Woo

**Comment by artikus11** [comment]
@uptimizt Как зачем? Денег больше брать))) Шучу. Конечно можно и отдельным классом, я потом допер)

**Comment by uptimizt** [comment]
Возник еще один кейс - услуги типа туры. Нужно для отслеживания задолженности по услугам. Продажа услуг через сайт как виртуальные продукты.

ХД 1974

**Comment by uptimizt** [comment]
Возник вопрос по работе плагина WooMS XT.
У меня включено управление остатками, и на сайте показываются только товары с положительным остатком. Но также в Моёмскладе есть услуги которые нужно чтобы отображались на сайте. Но т.к. услуги нельзя поставить на приход у них считается нулевой остаток и они не отображаются на сайте. Помогите как исправить эту ситуацию.

HD::572-521101
