### ISSUE TITLE
Навигация в настройках

### ISSUE THREAD

**Issue by artikus11** [wpcraft-ru/wooms#62]
Повысить удобство навигации в настройках.

Думаю лучше всего подойдет решение на базе летающего TOC.

обернутый в класс stuffbox где то справа.

**Comment by artikus11** [comment]
@uptimizt В отдельной ветке, могу запушить. Выглядит вот так

![image](https://user-images.githubusercontent.com/16116688/45921486-a1f8b300-bec7-11e8-968d-6fe991a552d2.png)

На тестовом сейчас включено, можешь посмотреть

Пока в прототипе, так как надо разнести еще по типу плагина: платный бесплатный

**Comment by uptimizt** [comment]
Табы - круто! :)
Но кмк надо пока сделаем лишь 2 таба:
1. Основные - там только пароль, и те что в базовой версии + инструкции можно добавить
2. Дополнительные - включается если XT версия активирована.

Ну и затем мб еще табы добавлять.

@artikus11

**Comment by uptimizt** [comment]
@artikus11 вынос МойСклад в верхний уровень - меня сначала смутил - захотел поспорить. Но то как ты это сделал - круто ) Скорее всего ты прав и так будет круче :)

**Comment by uptimizt** [comment]
после того как внедрим эти 2 изменения предлагаю начать оба плагина начать нумеровать так:
- базовая версия 3.0
- xt версия 3.0

чтобы затем пробовать развивать их в синхронности. чтобы версии дергались одинаково по ходу развития и совпадение версии означало что оба плагина совместимы и нет отстования.

@artikus11

**Comment by artikus11** [comment]
@uptimizt Отлично. Это пока прототип. А табы  делил по сущьностям, но можно и так, по типам плагинов

С версиями согласен, но все равно может быть рассогласование. Если только при любый изменениях синхронно номера версий менять. А так может быть, что вносим изменения в один а в другом нет ничего. Надо еще подумать, будет правильней

**Comment by uptimizt** [comment]
@artikus11 надо просто попробовать этот вариант. я вижу что может лишь иногда отставать XT версия. но делать подгонку версии думаю не сложно )

**Comment by artikus11** [comment]
@uptimizt Без проблем, сделаем
