### ISSUE TITLE
Создалась старшая категория

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#63]
на сайте выбрана группа Колясочные запчасти для синка с магазином 

все было ок, но с утра все товары пропали, а когда попытались повторить обмен то она появилась на сайте:
![image](https://user-images.githubusercontent.com/1852897/45927571-e7f05e00-bf3d-11e8-914e-97fbea6e120a.png)

**Comment by uptimizt** [comment]
@artikus11 можно ли написать алгоритм при котором эта категория вообще не будет создаваться?

**Comment by artikus11** [comment]
@uptimizt Не понял как алгоритм синка происходит. Сначала из отдельной рубрики, потом полный делается?

**Comment by uptimizt** [comment]
@artikus11 как сейчас или как надо?

как сейчас - создается базовая и иногда остается на сайте
как надо - не создавать если она выбрана в качестве основы

**Comment by artikus11** [comment]
@uptimizt А синк из отдельной рубрики постоянно включен?
