### ISSUE TITLE
Добавить хук в изменение цены

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#66]
> Добрый день. Есть плагин Woo MS (мой склад) на WP обычный и расширенный. Товары на моем складе в евро есть 2 цены оптом и в розницу, а нам нужно, что бы при импорте розничной цены они переводились в Бел рубли, т.е. все цены умножались на необходимый коэффициент. Какую переменную и где нужно умножить на коэффициент в файле class-import-prices.php. Спасибо

Нужно добавить хук-фильтр, который позволит менять цену более простым способом.

**Comment by artikus11** [comment]
@uptimizt Фильтр `wooms_product_price` не подойдет? Или это речь про спеццены?

**Comment by uptimizt** [comment]
@artikus11 для базовой цены и для распродажи. нужно менять их обе по ситуации.
можно одним хуком или двумя

**Comment by artikus11** [comment]
@uptimizt Ок, понял. Сделаю
