### ISSUE TITLE
Опция - Всегда заменять описание на Сайте данными из Склада

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#68]
сейчас Описание продукта обновляется из Склада только если на Сайте пустое.
Если же на Сайте что то есть, то из ничего не обновляется.
Это правильно по умолчанию.
Но есть те кто описание правит на Складе.

для таких нужна опция "Менять описание на Сайте" и добавить что описание будет всегда перетираться тем что на Складе.

**Comment by artikus11** [comment]
@uptimizt Эта опция для бесплатной версии или платной?

**Comment by uptimizt** [comment]
@artikus11 для бесплатной

**Comment by artikus11** [comment]
@uptimizt Понял

**Comment by uptimizt** [comment]
test ok
