### ISSUE TITLE
Снизить нагрузку на БД

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#69]
# Решения
- убрать множество product->save() и др save операций
- передавать объект в хуке
- чтобы вспомогательные хуки его меняли
- сохранять 1 раз на 1 объект за сессию

# Проблема

Плагин создает много обращений к БД MySQL на каталоге в 1000 товаров.
Надо подумать над оптимизацией. Минимизировать нагрузку на БД.

Отключаем ежедневный синк товаров и нагрузка падает. См снимок.

![image](https://user-images.githubusercontent.com/1852897/46429790-fc0f3900-c74f-11e8-9362-50b30e65da64.png)

**Comment by artikus11** [comment]
@uptimizt Ну логично все. Крон же работает, постоянно записывает и перезаписывает БД. На текущий момент придется пока реже синк ставить.

Хотя проблема оптимизации этого процесса есть. Как ее решить в коде пока не знаю,но предлагаю  алгоритм:

- АПИ позволяет загружить только обновленные сущности
- при повторной снхронизации надо обновлять только те товары, которые изменились

**Comment by uptimizt** [comment]
не ожидал, но плагин реально убивал БД.
в новой версии снижение нагрузки в 10-20 раз.

![image](https://user-images.githubusercontent.com/1852897/50075527-400ec780-01f0-11e9-8cc7-e198e7cfb0dd.png)

**Comment by artikus11** [comment]
@uptimizt И что так нагружало? Как решил?
