### ISSUE TITLE
Может не удалять родительскую категорию?

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#73]
Сейчас если мы в настройках выбрали группу из которой брать товары, то сама группа удаляется.

В целом это правильно. 

Но есть ситуации когда это создает проблему.

Например: у категории было описание и картинка. Случайно выбрали не ту группу, сделали синк, поменяли. Категория, ее описание и картинка - удалены. Новая создана, но без описания и картинки. Данные потерян и восстановить их бывает не просто.

Потому можно попробовать сделать так:
1. Старый терм не удалять, а переименовывать. Добавлять слово "На удаление"
2. Все товары из него переносить или делать их как Uncategorized
3. Делать его верхним

Тогда он скроется с сайта. Но удален не будет. И будет возможность потом эти данные перетащить в новые. Без потери.

**Comment by artikus11** [comment]
@uptimizt МС не поддерживает картинки в рубриках и если добавить картинку и описание на сайте, то при синке в любом случае данные перезапишутся. Но как вариант, да можно так попробовать. Я пробовал просто родителя отвязывать от дочерних, но там такая чехарда начинается, шо пипец. Надо подумать, как уйти от удаления

**Comment by artikus11** [comment]
@uptimizt Переделал! Теперь родительская не удалятся, а разрываются связи с дочерними. И рубрика пропадает сразу в момент начала синка (поставил хук перед синком). 

Но вот какой момент. Если в рубрике нет дочерок, то тут или удалять рубрику или разрывать ее связи с товарами в ней?

Удаление - наиболее простая операция. Вжик и все)

Разрыв связей - довольно ресурсоемкая операция: надо получить все товары из категории, а потом у них связь с этой категорией разорвать. Результат тот же, но рубрика остается на сайте и соответственно все данные по ней, то же остаются. 

Тонкий момент - это обработка товаров, для разрыва. Опять придется по крону это делать, иначе при больших количествах товаров можем сайт уронить. И опять пока связи не разорвутся рубрика будет видна с фронта.

Как делать?

**Comment by uptimizt** [comment]
> Но есть тонкие места

что за места? @artikus11

**Comment by artikus11** [comment]
@uptimizt Для обновления рубрики требуется получать все посты из нее, чтобы связи оборвать. Вот это и есть тонкое место. 

Сейчас будет получать все посты сразу. Как это разбить на куски, не знаю пока. Но думаю надо пока оставить как есть, Потому как подобная ситуация может и не возникнуть

Еще переделал там немного апдейт рубрик, завтра запушу

**Comment by artikus11** [comment]
@uptimizt Проверь мерж на гитлабе. Исправил выборку количества товаров при синке из одной категории

Поставил получение всех товаров. Если начнут жаловаться на нехватку памяти, то придется какой-то финт ушами придумывать. Сейчас вроде все работает
