### ISSUE TITLE
При синке появляется лишняя категория

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#74]
Колясочные запчасти - это категория для синка с сайтом. Товаров много. И на время синка она появляется на сайте. Что пугает всех. Надо найти решение при котором она не будет появляться.

![image](https://user-images.githubusercontent.com/1852897/46594862-32e1a800-cade-11e8-8e42-2180938b80df.png)

**Comment by artikus11** [comment]
@uptimizt  Появляется, а потом пропадает? Или так и остается?
