### ISSUE TITLE
Опция замены картинок

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#80]
По аналогии с тем как сделано для Заголовков и Описания. Нужно также сделать для Картинок.
Бывают ситуации когда картинка в МойСклад меняется. И нужно чтобы при смене картинки на Складе менялась на Сайте.

Для этого надо опции Картинок вынести в отдельную группу "Изображения" и там уже разместить текущую опцию включения картинок. Плюс добавить опцию "Заменять картинки если изменились на Складе".

**Comment by artikus11** [comment]
@uptimizt Понял. Занимаюсь. 

Тогда старый[ тикет удали](https://github.com/wpcraft-ru/wooms/issues/28) а то путаться будем. Это одна и та же проблема

**Comment by uptimizt** [comment]
тест ок
