### ISSUE TITLE
Тесты Woo 3.5 & CRUD

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#83]
вышел https://woocommerce.wordpress.com/2018/10/23/woocommerce-3-5-is-here/

надо прогнать тесты с учетом новой механики кастомных таблиц

например вместо update_post_meta надо использовать $product->update_meta_data()

**Comment by artikus11** [comment]
@uptimizt Дак а тестовом уже месяц 3.5 юзаю, проблем не наблюдал. Но у меня доступа к базе нет и проверить как там что не могу. У себя проверю

**Comment by uptimizt** [comment]
@artikus11 без доп плагина который делает кастомные таблицы - это бесполезно.
надо именно ставить плагин, мигрировать данные и затем тестить.

**Comment by artikus11** [comment]
@uptimizt C чего бы? Не надо там никакого плагина, в релизе все и так переноситься, вот если база большая, тогда надо через WP-CLI, а так нет

Ну и на тестовом да, кода еще в бете было, отдельным плагином переносил. А в релизе не требуется

**Comment by uptimizt** [comment]
прописал вику https://github.com/wpcraft-ru/wooms/wiki
