### ISSUE TITLE
Прогнать тест Статуса Заказов

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#84]
есть замечания о том что обновление Статуса Заказов не работает.
Нужно проверить.

**Comment by artikus11** [comment]
@uptimizt Как это сделать? Статусы в МС платный функционал, а у нас бесплатная версия. Или нет?

**Comment by uptimizt** [comment]
надо проверить.
если нет то написать им и попросить включить.

**Comment by artikus11** [comment]
@uptimizt Функционала статусов в МС не наблюдаю. Это тебе надо им написать, типа разрабочик и все такое

**Comment by uptimizt** [comment]
@artikus11 они точно есть и работали.

плагин вебхуком создает обратный вебхук.
который стреляет в сторону сайта при смене Статуса Заказа на стороне Склада.
надо проврить работает смена статусов или нет.

**Comment by uptimizt** [comment]
тут подробнее 
https://support.moysklad.ru/hc/ru/community/posts/360016541014-%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0-post-%D0%BF%D1%80%D0%B8-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B8-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0

@artikus11

**Comment by artikus11** [comment]
@uptimizt Ткни меня в эти вебхуки в админе МС. Хоть убей не найду ТОлько вот это вычитал
![image](https://user-images.githubusercontent.com/16116688/48317450-f2f56f80-e60b-11e8-9dfa-64b877a38fd2.png)

**Comment by uptimizt** [comment]
@artikus11 
см код woom xt, который за это отвечает. надо его проверить. если что то не так - связаться с тех поддержкой МойСклад.

![image](https://user-images.githubusercontent.com/1852897/48568153-bda09880-e90f-11e8-972d-f57f45f404ff.png)

**Comment by artikus11** [comment]
@uptimizt Разобрался со статусами. Они работают, но почему-то старые вебхуки не удаляются. Например, когда создавался тестовый вебхук. Когда через постмен удалил старый хук, то все заработало.  
Разбираюсь с этим удалением сейчас

В МС 30 пробный период заканчивается, надо как-то его продлить

**Comment by uptimizt** [comment]
@artikus11 есть тут прогресс?

**Comment by artikus11** [comment]
@uptimizt Нет пока... Зато у клиентов есть хотелки чтобы статусы в обратную сторону шли с сайта в МС. Так вообще должно работать?

**Comment by uptimizt** [comment]
> Зато у клиентов есть хотелки чтобы статусы в обратную сторону шли с сайта в МС. Так вообще должно работать?

думаю да, надо создать задачу на эту тему 

@artikus11

**Comment by uptimizt** [comment]
поправил @artikus11

**Comment by artikus11** [comment]
@uptimizt ага, видел
