### ISSUE TITLE
Поддержка WP CLI

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#85]
надо сделать поддержку WP CLI.
для хостингов у которых есть поддержка WP CLI - оч хорошо.

**Comment by artikus11** [comment]
@uptimizt Как это сделать? Хоть скажи что почитать или как гуглить. Это для меня вообще темный лес

**Comment by uptimizt** [comment]
https://halfelf.org/2015/making-wp-cli-plugin/

@artikus11

**Comment by artikus11** [comment]
@artikus11 Статья Мики Эпщтейн) 

Какие команды ты хочешь сделать?

Кстати, тестовый на таймвебе, там вроде есть поддержка WP-CLI. Надо только разобраться как ее использовать

**Comment by uptimizt** [comment]
нашлось решение интересней #140
