### ISSUE TITLE
Использование кода в МойСклад как артикула в WooCommerce (код, code)

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#98]
Это решение будет работать в тех ситуациях, когда есть проблемы с артикулами, но можно делать связи продуктов ко коду товара из МойСклад.

# Решение

## Активировать опцию связи продуктов по коду 
![image](https://user-images.githubusercontent.com/1852897/84592323-7b25a180-ae4d-11ea-915c-a943448e361c.png)

## Указать код товара из МойСклад как артикул продукта на Сайте
![image](https://user-images.githubusercontent.com/1852897/84592311-55000180-ae4d-11ea-8088-678a76f4824a.png)

# DoD
- по умолчанию синкать продукты по артикулам
- доп опция - использовать код как артикул и создавать продукты
- доп опция что есть сейчас - использовать uuid

# Вопрос с тех поддержки:

> Интеграция woocommerce и мой склад происходит посредством так >> код мой склад = артикул woocommerce? 

Надо подумать над таким решением. Мб опцию сделать.

Цитата, которая отражает суть проблемы:
Я просто через какое-то время планирую перейти на Ecwid с другим сайтом но с этими же товарами и вот там реализовано синхронизация по вариантам товаров только если артикули разные, иначе считается просто что в наличии и всё, никак не учитывается именно сколько осталось. И вот чтобы правильно переводились остатки по размерам, то нужно заполнять в поле Внешний код на стороне МС - артикул и тогда по всем вариантам остатки правильно считаются. Вот я и думал пока сразу товары заводить с учетом их требований, чтобы через полгодика без проблем перейти. Поэтому для WooCommerce думаю это ни к чему и так работает. Это так для идеи подкинул, а для себя просто попробовал вбить во внешние коды артикли, в вашем плагине он я так понял не используется и ничего не ломается в синхронизации, я и буду пока вбивать, чтобы потом перейти на Ecwid и уже у меня всё будет подготовлено

**Comment by artikus11** [comment]
@uptimizt Да вроде так и происходит если uuid включено, или речь про другие коды?

**Comment by uptimizt** [comment]
у МойСклад есть 3 идентификатора товара:
1. uuid - внутренний
2. код товара - виден пользователю, цифровой, уникален
3. артикул

у нас либо 3, либо активируется 1.

есть клиенты которые не хотят артикулы, а хотят вместо них использовать коды.

что то в этом есть. надо будет попробовать опцию сделать

@artikus11

**Comment by 9in9er** [comment]
Данная опция так и не была реализована? Или только в расширенной версии?

**Comment by uptimizt** [comment]
@9in9er 
Пока нет. Мало кому нужно. 
Есть технический конфликт. Код в МойСклад может дублироваться. Один код может соответствовать 2м продуктам. А значит нельзя однозначно идентифицировать записи между Складом и Сайтом.
Птм пока проблемы решаются артикулами, лучше ими и решать.

**Comment by uptimizt** [comment]
> Пока нет. Мало кому нужно.
> Есть технический конфликт. Код в МойСклад может дублироваться. Один код может соответствовать 2м продуктам. А значит нельзя однозначно идентифицировать записи между Складом и Сайтом.
> Птм пока проблемы решаются артикулами, лучше ими и решать.

возможно что то поменялось. 
похоже код стал уникальным для всех товаров и услуг в МойСклад.
птм можно легко использовать его как артикул.
